---@class Private
local Private = select(2, ...)

local L = Private.L

L["Difficulty-1"] = "L"
L["Difficulty-3"] = "N"
L["Difficulty-4"] = "H"
L["Difficulty-5"] = "M"
L["DifficultyName-1"] = "LFR"
L["DifficultyName-3"] = "Normal"
L["DifficultyName-4"] = "Heroic"
L["DifficultyName-5"] = "Mythic"
L["AllStars"] = "All Stars"
L["Rank"] = "Rank"
L["Kills"] = "Kills"
L["Unknown"] = [[Unknown]]
L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
L["CopyProfileURL"] = [[Copy WCL URL]]
L["Subscriber"] = [[Subscriber]]
L["ShiftToExpand"] = [[<Shift> to Expand]]
L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
L["Main"] = [[Main]]
L["ClickToOpenSettings"] = [[Click to open Settings]]
L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
L["ShowRank"] = [[Show Rank]]
L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
L["ShowAsp"] = [[Show All Stars]]
L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
L["ShowShiftHint"] = [[Show Shift Hint]]
L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
L["MenuIntegration"] = [[Extend Menu Options]]
L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
L["SettingsLookupNoData"] = [[No data found.]]
L["SettingsLookupDataFor"] = [[%s for %s - %s]]
L["SettingsAvailableCommands"] = [[Available commands:]]
L["SettingsOpenSettingsLabel"] = [[opens the settings]]
L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

if Private.IsRetail then
    L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
    L["Encounter-3129"] = [[Plexus Sentinel]]
    L["Encounter-3131"] = [[Loom'ithar]]
    L["Encounter-3130"] = [[Soulbinder Naazindhri]]
    L["Encounter-3132"] = [[Forgeweaver Araz]]
    L["Encounter-3122"] = [[The Soul Hunters]]
    L["Encounter-3133"] = [[Fractillus]]
    L["Encounter-3134"] = [[Nexus-King Salhadaar]]
    L["Encounter-3135"] = [[Dimensius, the All-Devouring]]
elseif Private.IsMists then
    L["addon.parse-gate-description"] = "Parses shown after 10H kills"
    L["Encounter-51577"] = [[Jin'rokh the Breaker]]
    L["Encounter-51575"] = [[Horridon]]
    L["Encounter-51570"] = [[Council of Elders]]
    L["Encounter-51565"] = [[Tortos]]
    L["Encounter-51578"] = [[Megaera]]
    L["Encounter-51573"] = [[Ji-Kun]]
    L["Encounter-51572"] = [[Durumu the Forgotten]]
    L["Encounter-51574"] = [[Primordius]]
    L["Encounter-51576"] = [[Dark Animus]]
    L["Encounter-51559"] = [[Iron Qon]]
    L["Encounter-51560"] = [[Twin Empyreans]]
    L["Encounter-51579"] = [[Lei Shen]]
    L["Encounter-51580"] = [[Ra-den]]
    L["addon.parse-gate-description"] = "Parses shown after 10H kills"
    L["Encounter-51507"] = [[Imperial Vizier Zor'lok]]
    L["Encounter-51504"] = [[Blade Lord Ta'yak]]
    L["Encounter-51463"] = [[Garalon]]
    L["Encounter-51498"] = [[Wind Lord Mel'jarak]]
    L["Encounter-51499"] = [[Amber-Shaper Un'sok]]
    L["Encounter-51501"] = [[Grand Empress Shek'zeer]]
    L["Encounter-51409"] = [[Protectors of the Endless]]
    L["Encounter-51505"] = [[Tsulong]]
    L["Encounter-51506"] = [[Lei Shi]]
    L["Encounter-51431"] = [[Sha of Fear]]
elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
    L["addon.parse-gate-description"] = ""
    L["Encounter-3185"] = [[Balnazzar]]
    L["Encounter-3187"] = [[Beatrix]]
    L["Encounter-3186"] = [[Solistrasza]]
    L["Encounter-3197"] = [[Mason]]
    L["Encounter-3196"] = [[Beastmaster]]
    L["Encounter-3188"] = [[Reborn Council]]
    L["Encounter-3190"] = [[Lillian Voss]]
    L["Encounter-3189"] = [[Caldoran]]
elseif C_Seasons.GetActiveSeason() == 109 then
    L["addon.parse-gate-description"] = "Parses shown after 10H kills"
    L["Encounter-50623"] = [[Hydross the Unstable]]
    L["Encounter-50624"] = [[The Lurker Below]]
    L["Encounter-50625"] = [[Leotheras the Blind]]
    L["Encounter-50626"] = [[Fathom-Lord Karathress]]
    L["Encounter-50627"] = [[Morogrim Tidewalker]]
    L["Encounter-50628"] = [[Lady Vashj]]
    L["Encounter-50730"] = [[Al'ar]]
    L["Encounter-50731"] = [[Void Reaver]]
    L["Encounter-50732"] = [[High Astromancer Solarian]]
    L["Encounter-50733"] = [[Kael'thas Sunstrider]]
elseif Private.IsClassicEra and (C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh or C_Seasons.GetActiveSeason() == 125) then
    L["addon.parse-gate-description"] = "Parses shown after 10H kills"
    L["Encounter-50649"] = [[High King Maulgar]]
    L["Encounter-50650"] = [[Gruul the Dragonkiller]]
    L["Encounter-50651"] = [[Magtheridon]]
end

local locale = GAME_LOCALE or GetLocale()

if locale == "deDE" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "Schlachtzugsbrowser"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroisch"
    L["DifficultyName-5"] = "Mythisch"
    L["AllStars"] = "Bestplatzierte"
    L["Rank"] = "Rang"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unbekannt]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Abonnent]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Nutzung: /%s lookup <name> <welt>]]
    L["SettingsLookupNoData"] = [[Keine Daten gefunden]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3129"] = [[Plexuswache]]
        L["Encounter-3131"] = [[Loom'ithar]]
        L["Encounter-3130"] = [[Seelenbinderin Naazindhri]]
        L["Encounter-3132"] = [[Schmiedeweber Araz]]
        L["Encounter-3122"] = [[Die Seelenjäger]]
        L["Encounter-3133"] = [[Fraktillus]]
        L["Encounter-3134"] = [[Nexuskönig Salhadaar]]
        L["Encounter-3135"] = [[Dimensius der alles Verschlingende]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-51577"] = [[Jin'rokh der Zerstörer]]
        L["Encounter-51575"] = [[Horridon]]
        L["Encounter-51570"] = [[Rat der Ältesten]]
        L["Encounter-51565"] = [[Tortos]]
        L["Encounter-51578"] = [[Megaera]]
        L["Encounter-51573"] = [[Ji-Kun]]
        L["Encounter-51572"] = [[Durumu der Vergessene]]
        L["Encounter-51574"] = [[Primordius]]
        L["Encounter-51576"] = [[Dunkler Animus]]
        L["Encounter-51559"] = [[Der eiserne Qon]]
        L["Encounter-51560"] = [[Zwillingsempyreanerinnen]]
        L["Encounter-51579"] = [[Lei Shen]]
        L["Encounter-51580"] = [[Ra-den]]
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-51507"] = [[Kaiserlicher Wesir Zor'lok]]
        L["Encounter-51504"] = [[Klingenfürst Ta'yak]]
        L["Encounter-51463"] = [[Garalon]]
        L["Encounter-51498"] = [[Windfürst Mel'jarak]]
        L["Encounter-51499"] = [[Bernformer Un'sok]]
        L["Encounter-51501"] = [[Großkaiserin Shek'zeer]]
        L["Encounter-51409"] = [[Beschützer des Endlosen]]
        L["Encounter-51505"] = [[Tsulong]]
        L["Encounter-51506"] = [[Lei Shi]]
        L["Encounter-51431"] = [[Sha der Angst]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Bestienmeister]]
        L["Encounter-3188"] = [[Wiedergeborener Rat]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif C_Seasons.GetActiveSeason() == 109 then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-50623"] = [[Hydross der Unstete]]
        L["Encounter-50624"] = [[Das Grauen aus der Tiefe]]
        L["Encounter-50625"] = [[Leotheras der Blinde]]
        L["Encounter-50626"] = [[Tiefenlord Karathress]]
        L["Encounter-50627"] = [[Morogrim Gezeitenwandler]]
        L["Encounter-50628"] = [[Lady Vashj]]
        L["Encounter-50730"] = [[Al'ar]]
        L["Encounter-50731"] = [[Leerhäscher]]
        L["Encounter-50732"] = [[Hochastromantin Solarian]]
        L["Encounter-50733"] = [[Kael'thas Sonnenwanderer]]
    elseif Private.IsClassicEra and (C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh or C_Seasons.GetActiveSeason() == 125) then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-50649"] = [[Hochkönig Maulgar]]
        L["Encounter-50650"] = [[Gruul der Drachenschlächter]]
        L["Encounter-50651"] = [[Magtheridon]]
    end
elseif locale == "esES" or locale == "esMX" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "BDB"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroico"
    L["DifficultyName-5"] = "Mítico"
    L["AllStars"] = "Los Mejores"
    L["Rank"] = "Rango"
    L["Kills"] = "Asesinatos"
    L["Unknown"] = [[Desconocido]]
    L["UnknownRealm"] = [[[%s] El reino '%s' (id %d) no está en la base de datos. Por favor, informa al equipo de Warcraft Logs.]]
    L["CopyProfileURL"] = [[Copiar URL de WCL]]
    L["Subscriber"] = [[Suscriptor ]]
    L["ShiftToExpand"] = [[<Shift> para expandir]]
    L["SubAddonMissing"] = [[[%s] Falta la base de datos de '%s' (%s). Puede que hayas iniciado sesión en el juego mientras el addon se estaba actualizando. Comprueba en la aplicación de escritorio si la actualización ha terminado y, después, ejecuta '/reload' para intentarlo de nuevo.]]
    L["DBLoadError"] = [[[%s] No se ha podido cargar la base de datos de '%s'. Motivo: %s ]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Haz clic para abrir la configuración]]
    L["ShowTooltipInCombat"] = [[Mostrar Tips de herramientas en Combate]]
    L["ShowTooltipInCombatDescription"] = [[Si extender los consejos de herramienta en combate también. Está desactivado de manera predeterminada como optimización]]
    L["AllowShiftExpansionInCombat"] = [[Mostrar extensión de shift en combate
]]
    L["AllowShiftExpansionInCombatDescription"] = [[Si cargar datos extendidos en combate también. Activa la configuración de arriba]]
    L["ShowRank"] = [[Mostrar rango]]
    L["ShowRankDescription"] = [[Activa o desactiva la inclusión del rango en la información emergente.]]
    L["ShowAsp"] = [[Mostrar todas las estrellas]]
    L["ShowAspDescription"] = [[Activa o desactiva la inclusión de los puntos de Todas las Estrellas en el tooltip.]]
    L["ShowShiftHint"] = [[Mostrar tips de Shift]]
    L["ShowShiftHintDescription"] = [[Activa o desactiva la sugerencia de mantener Shift para ampliar la información.]]
    L["MenuIntegration"] = [[Opciones de menú extendidas]]
    L["MenuIntegrationDescription"] = [[Si extender los menús con una opción para copiar el URL del perfil del personaje]]
    L["SettingsLookupUsage"] = [[Uso /%s buscar <name> <realm>]]
    L["SettingsLookupNoData"] = [[Datos no encontrados]]
    L["SettingsLookupDataFor"] = [[%s para %s - %s]]
    L["SettingsAvailableCommands"] = [[Comandos disponibles:]]
    L["SettingsOpenSettingsLabel"] = [[Abre la configuración]]
    L["SettingsLookupLabel"] = [[buscar perfil por nombre y región]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses mostrados después de muertes en 20H o 5M"
        L["Encounter-3129"] = [[Centinela del plexo]]
        L["Encounter-3131"] = [[Loom'ithar]]
        L["Encounter-3130"] = [[Vinculadora de almas Naazindhri]]
        L["Encounter-3132"] = [[Tejeforjas Araz]]
        L["Encounter-3122"] = [[Los cazaalmas]]
        L["Encounter-3133"] = [[Fractillus]]
        L["Encounter-3134"] = [[Rey-nexo Salhadaar]]
        L["Encounter-3135"] = [[Dimensius el Devoratodo]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses mostrados tras 10H muertes"
        L["Encounter-51577"] = [[Jin'rokh el Rompedor]]
        L["Encounter-51575"] = [[Horridonte]]
        L["Encounter-51570"] = [[Consejo de Ancianos]]
        L["Encounter-51565"] = [[Tortos]]
        L["Encounter-51578"] = [[Megaera]]
        L["Encounter-51573"] = [[Ji Kun]]
        L["Encounter-51572"] = [[Durumu el Olvidado]]
        L["Encounter-51574"] = [[Primordius]]
        L["Encounter-51576"] = [[Animus oscuro]]
        L["Encounter-51559"] = [[Qon el Tenaz]]
        L["Encounter-51560"] = [[Empíreas Gemelas]]
        L["Encounter-51579"] = [[Lei Shen]]
        L["Encounter-51580"] = [[Ra Den]]
        L["addon.parse-gate-description"] = "Parses mostrados tras 10H muertes"
        L["Encounter-51507"] = [[Visir imperial Zor'lok]]
        L["Encounter-51504"] = [[Señor de las espadas Ta'yak]]
        L["Encounter-51463"] = [[Garalon]]
        L["Encounter-51498"] = [[Señor del viento Mel'jarak]]
        L["Encounter-51499"] = [[Formador de ámbar Un'sok]]
        L["Encounter-51501"] = [[Gran emperatriz Shek'zeer]]
        L["Encounter-51409"] = [[Protectores de la Eternidad]]
        L["Encounter-51505"] = [[Tsulong]]
        L["Encounter-51506"] = [[Lei Shi]]
        L["Encounter-51431"] = [[Sha del miedo]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Maestro de bestias]]
        L["Encounter-3188"] = [[Consejo renacido]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif C_Seasons.GetActiveSeason() == 109 then
        L["addon.parse-gate-description"] = "Parses mostrados tras 10H muertes"
        L["Encounter-50623"] = [[Hydross el Inestable]]
        L["Encounter-50624"] = [[El Rondador de abajo]]
        L["Encounter-50625"] = [[Leotheras el Ciego]]
        L["Encounter-50626"] = [[Señor de las profundidades Karathress]]
        L["Encounter-50627"] = [[Morogrim Levantamareas]]
        L["Encounter-50628"] = [[Lady Vashj]]
        L["Encounter-50730"] = [[Al'ar]]
        L["Encounter-50731"] = [[Atracador del Vacío]]
        L["Encounter-50732"] = [[Gran astromante Solarian]]
        L["Encounter-50733"] = [[Kael'thas Caminante del Sol]]
    elseif Private.IsClassicEra and (C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh or C_Seasons.GetActiveSeason() == 125) then
        L["addon.parse-gate-description"] = "Parses mostrados tras 10H muertes"
        L["Encounter-50649"] = [[Su majestad Maulgar]]
        L["Encounter-50650"] = [[Gruul el Asesino de Dragones]]
        L["Encounter-50651"] = [[Magtheridon]]
    end
elseif locale == "frFR" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "LFR"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Héroïque"
    L["DifficultyName-5"] = "Mythique"
    L["AllStars"] = "All Stars"
    L["Rank"] = "Rang"
    L["Kills"] = "kills"
    L["Unknown"] = [[Inconnu]]
    L["UnknownRealm"] = [[[%s] Le royaume '%s' (identifiant %d) n'est pas dans la base de données. Merci de contacter l'équipe de Warcraft Logs.]]
    L["CopyProfileURL"] = [[Copier l'URL WarcraftLogs]]
    L["Subscriber"] = [[Abonné]]
    L["ShiftToExpand"] = [[<Maj> pour déplier]]
    L["SubAddonMissing"] = [[[%s] La base de données pour '%s' (%s) est manquante. Peut-être que vous vous êtes connecté au jeu pendant que l'addon était pleine mise à jour. Vérifiez l'application du bureau pour voir si la mise à jour est terminée, puis faites un '/reload' pour réessayer.]]
    L["DBLoadError"] = [[[%s] Impossible de charger la base de données de '%s'. Raison : %s]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Cliquez pour ouvrir les Paramètres]]
    L["ShowTooltipInCombat"] = [[Afficher l'Infobulle en Combat]]
    L["ShowTooltipInCombatDescription"] = [[Choisir si l'infobulle doit également être affichée en combat. Désactivé par défaut pour des raisons de performance.]]
    L["AllowShiftExpansionInCombat"] = [[Autoriser l'extension avec Shift en combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Choisir si les données étendues doivent également être affichées en combat. Active le paramètre ci-dessus.]]
    L["ShowRank"] = [[Afficher le rang]]
    L["ShowRankDescription"] = [[Active/Désactive l'ajout du rang à l'infobulle.]]
    L["ShowAsp"] = [[Montrer les All Stars]]
    L["ShowAspDescription"] = [[Active/Désactive l'ajout des points All Stars à l'infobulle.]]
    L["ShowShiftHint"] = [[Afficher l'astuce avec Shift]]
    L["ShowShiftHintDescription"] = [[Active/Désactive l'ajout de l'astuce pour étendre l'info en maintenant Shift.]]
    L["MenuIntegration"] = [[Étendre les options du menu]]
    L["MenuIntegrationDescription"] = [[Choisir si les menus doivent être étendus avec l'option de copier l'URL de profil du personnage.]]
    L["SettingsLookupUsage"] = [[Utilisation: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[Aucune donnée trouvée.]]
    L["SettingsLookupDataFor"] = [[%s pour %s - %s]]
    L["SettingsAvailableCommands"] = [[Commandes disponibles : ]]
    L["SettingsOpenSettingsLabel"] = [[ouvre les paramètres]]
    L["SettingsLookupLabel"] = [[rechercher un profil par nom  et royaume]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Les parses seront affichés après 20H ou 5M boss tués"
        L["Encounter-3129"] = [[Sentinelle du Plexus]]
        L["Encounter-3131"] = [[Rou’ethar]]
        L["Encounter-3130"] = [[Lieuse d’âme Naazindhri]]
        L["Encounter-3132"] = [[Tisseforge Araz]]
        L["Encounter-3122"] = [[Chasseurs d’âmes]]
        L["Encounter-3133"] = [[Fractillus]]
        L["Encounter-3134"] = [[Roi-nexus Salhadaar]]
        L["Encounter-3135"] = [[Dimensius l’Omni-dévoreur]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-51577"] = [[Jin’rokh le Briseur]]
        L["Encounter-51575"] = [[Horridon]]
        L["Encounter-51570"] = [[Conseil des anciens]]
        L["Encounter-51565"] = [[Tortos]]
        L["Encounter-51578"] = [[Megaera]]
        L["Encounter-51573"] = [[Ji Kun]]
        L["Encounter-51572"] = [[Durumu l’Oublié]]
        L["Encounter-51574"] = [[Primordius]]
        L["Encounter-51576"] = [[Sombre animus]]
        L["Encounter-51559"] = [[Qwon de fer]]
        L["Encounter-51560"] = [[Jumelles empyréennes]]
        L["Encounter-51579"] = [[Lei Shen]]
        L["Encounter-51580"] = [[Ra Den]]
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-51507"] = [[Vizir impérial Zor’lok]]
        L["Encounter-51504"] = [[Seigneur des lames Ta’yak]]
        L["Encounter-51463"] = [[Garalon]]
        L["Encounter-51498"] = [[Seigneur du Vent Mel’jarak]]
        L["Encounter-51499"] = [[Sculpte-ambre Un’sok]]
        L["Encounter-51501"] = [[Grande impératrice Shek’zeer]]
        L["Encounter-51409"] = [[Protecteurs de l’Éternel]]
        L["Encounter-51505"] = [[Tsulong]]
        L["Encounter-51506"] = [[Lei Shi]]
        L["Encounter-51431"] = [[Sha de la peur]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Maçon]]
        L["Encounter-3196"] = [[Belluaire]]
        L["Encounter-3188"] = [[Le conseil ressuscité]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif C_Seasons.GetActiveSeason() == 109 then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-50623"] = [[Hydross l'Instable]]
        L["Encounter-50624"] = [[Le Rôdeur d'En bas]]
        L["Encounter-50625"] = [[Leotheras l'Aveugle]]
        L["Encounter-50626"] = [[Seigneur des fonds Karathress]]
        L["Encounter-50627"] = [[Morogrim Marcheur-des-flots]]
        L["Encounter-50628"] = [[Dame Vashj]]
        L["Encounter-50730"] = [[Al'ar]]
        L["Encounter-50731"] = [[Saccageur du Vide]]
        L["Encounter-50732"] = [[Grande astromancienne Solarian]]
        L["Encounter-50733"] = [[Kael’thas Haut-Soleil]]
    elseif Private.IsClassicEra and (C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh or C_Seasons.GetActiveSeason() == 125) then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-50649"] = [[Haut Roi Maulgar]]
        L["Encounter-50650"] = [[Gruul le Tue-Dragon]]
        L["Encounter-50651"] = [[Magtheridon]]
    end
elseif locale == "itIT" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "LFR"
    L["DifficultyName-3"] = "Normale"
    L["DifficultyName-4"] = "Eroico"
    L["DifficultyName-5"] = "Mitico"
    L["AllStars"] = "Classificazione All-Stars"
    L["Rank"] = "Rango"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unknown]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Subscriber]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3129"] = [[Sentinella del Plesso]]
        L["Encounter-3131"] = [[Loom'ithar]]
        L["Encounter-3130"] = [[Vincolatrice d'Anime Naazindhri]]
        L["Encounter-3132"] = [[Tessiforgia Araz]]
        L["Encounter-3122"] = [[I Cacciatori d'Anime]]
        L["Encounter-3133"] = [[Fractillus]]
        L["Encounter-3134"] = [[Re del Nexus Salhadaar]]
        L["Encounter-3135"] = [[Dimensius il Divoratore]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-51577"] = [[Jin'rokh il Demolitore]]
        L["Encounter-51575"] = [[Horridon]]
        L["Encounter-51570"] = [[Concilio degli Anziani]]
        L["Encounter-51565"] = [[Tortos]]
        L["Encounter-51578"] = [[Megaera]]
        L["Encounter-51573"] = [[Ji-Kun]]
        L["Encounter-51572"] = [[Durumu il Dimenticato]]
        L["Encounter-51574"] = [[Primordius]]
        L["Encounter-51576"] = [[Animus Oscuro]]
        L["Encounter-51559"] = [[Qon il Tenace]]
        L["Encounter-51560"] = [[Empiree Gemelle]]
        L["Encounter-51579"] = [[Lei Shen]]
        L["Encounter-51580"] = [[Ra-Den]]
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-51507"] = [[Visir Imperiale Zor'lok]]
        L["Encounter-51504"] = [[Signore delle Lame Ta'yak]]
        L["Encounter-51463"] = [[Garalon]]
        L["Encounter-51498"] = [[Signore del Vento Mel'jarak]]
        L["Encounter-51499"] = [[Un'sok il Plasmatore d'Ambra]]
        L["Encounter-51501"] = [[Grande Imperatrice Shek'zeer]]
        L["Encounter-51409"] = [[Protettori dell'Eterno]]
        L["Encounter-51505"] = [[Tsulong]]
        L["Encounter-51506"] = [[Lei Shi]]
        L["Encounter-51431"] = [[Sha della Paura]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Beastmaster]]
        L["Encounter-3188"] = [[Reborn Council]]
        L["Encounter-3190"] = [[Lillian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif C_Seasons.GetActiveSeason() == 109 then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-50623"] = [[Idross l'Instabile]]
        L["Encounter-50624"] = [[Mostro degli Abissi]]
        L["Encounter-50625"] = [[Leotheras il Cieco]]
        L["Encounter-50626"] = [[Karathress il Signore degli Abissi]]
        L["Encounter-50627"] = [[Morogrim Calcamaree]]
        L["Encounter-50628"] = [[Dama Vashj]]
        L["Encounter-50730"] = [[Al'ar]]
        L["Encounter-50731"] = [[Razziatore del Vuoto]]
        L["Encounter-50732"] = [[Gran Astromante Solarian]]
        L["Encounter-50733"] = [[Kael'thas Solealto]]
    elseif Private.IsClassicEra and (C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh or C_Seasons.GetActiveSeason() == 125) then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-50649"] = [[Gran Sovrano Maulgar]]
        L["Encounter-50650"] = [[Gruul l'Ammazzadraghi]]
        L["Encounter-50651"] = [[Magtheridon]]
    end
elseif locale == "koKO" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "일반"
    L["Difficulty-4"] = "영웅"
    L["Difficulty-5"] = "신화"
    L["DifficultyName-1"] = "공격대 찾기"
    L["DifficultyName-3"] = "일반"
    L["DifficultyName-4"] = "영웅"
    L["DifficultyName-5"] = "신화"
    L["AllStars"] = "올스타"
    L["Rank"] = "등급"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unknown]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Subscriber]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3129"] = [[흐름망 파수꾼]]
        L["Encounter-3131"] = [[룸이타르]]
        L["Encounter-3130"] = [[영혼술사 나진드리]]
        L["Encounter-3132"] = [[제련직공 아라즈]]
        L["Encounter-3122"] = [[영혼 사냥꾼]]
        L["Encounter-3133"] = [[프랙틸루스]]
        L["Encounter-3134"] = [[연합왕 살라다르]]
        L["Encounter-3135"] = [[만물의 포식자 디멘시우스]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-51577"] = [[파괴자 진로크]]
        L["Encounter-51575"] = [[호리돈]]
        L["Encounter-51570"] = [[장로회]]
        L["Encounter-51565"] = [[토르토스]]
        L["Encounter-51578"] = [[메가이라]]
        L["Encounter-51573"] = [[지쿤]]
        L["Encounter-51572"] = [[잊혀진 두루무]]
        L["Encounter-51574"] = [[프리모디우스]]
        L["Encounter-51576"] = [[암흑 원령]]
        L["Encounter-51559"] = [[강철의 퀀]]
        L["Encounter-51560"] = [[쌍둥이 왕비]]
        L["Encounter-51579"] = [[레이 션]]
        L["Encounter-51580"] = [[라덴]]
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-51507"] = [[황실 장로 조르로크]]
        L["Encounter-51504"] = [[칼날군주 타야크]]
        L["Encounter-51463"] = [[가랄론]]
        L["Encounter-51498"] = [[바람군주 멜자라크]]
        L["Encounter-51499"] = [[호박석구체자 운속]]
        L["Encounter-51501"] = [[위대한 여제 셰크지르]]
        L["Encounter-51409"] = [[영원의 수호병]]
        L["Encounter-51505"] = [[출롱]]
        L["Encounter-51506"] = [[레이 스]]
        L["Encounter-51431"] = [[공포의 샤]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[발나자르]]
        L["Encounter-3187"] = [[베아트릭스]]
        L["Encounter-3186"] = [[솔리스트라자]]
        L["Encounter-3197"] = [[석공]]
        L["Encounter-3196"] = [[야수조련사]]
        L["Encounter-3188"] = [[부활의 의회]]
        L["Encounter-3190"] = [[릴리안 보스]]
        L["Encounter-3189"] = [[칼도란]]
    elseif C_Seasons.GetActiveSeason() == 109 then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-50623"] = [[불안정한 히드로스]]
        L["Encounter-50624"] = [[심연의 잠복꾼]]
        L["Encounter-50625"] = [[눈먼 레오테라스]]
        L["Encounter-50626"] = [[심해군주 카라드레스]]
        L["Encounter-50627"] = [[겅둥파도 모로그림]]
        L["Encounter-50628"] = [[여군주 바쉬]]
        L["Encounter-50730"] = [[알라르]]
        L["Encounter-50731"] = [[공허의 절단기]]
        L["Encounter-50732"] = [[고위 점성술사 솔라리안]]
        L["Encounter-50733"] = [[캘타스 선스트라이더]]
    elseif Private.IsClassicEra and (C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh or C_Seasons.GetActiveSeason() == 125) then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-50649"] = [[왕중왕 마울가르]]
        L["Encounter-50650"] = [[용 학살자 그룰]]
        L["Encounter-50651"] = [[마그테리돈]]
    end
elseif locale == "ptBR" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "D"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "PPR"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroico"
    L["DifficultyName-5"] = "Mítico"
    L["AllStars"] = "Maiores Estrelas"
    L["Rank"] = "Ranque"
    L["Kills"] = "Abates"
    L["Unknown"] = [[Desconhecido]]
    L["UnknownRealm"] = [[[%s] Domínio '%s' (id %d) não está no banco de dados. Por favor, reporte-se à equipe do Warcraft Logs.]]
    L["CopyProfileURL"] = [[Copiar URL do WCL]]
    L["Subscriber"] = [[Assinante]]
    L["ShiftToExpand"] = [[<Shift> para expandir]]
    L["SubAddonMissing"] = [[[%s] Base de dados para '%s' (%s) está ausente. Pode ser que você tenha entrado no jogo enquanto o 'addon' estava no meio de uma atualização. Verifique o aplicativo no 'desktop' para ver se a atualização foi concluída, e então execute '/reload' para tentar novamente.]]
    L["DBLoadError"] = [[[%s] Não foi possível carregar a base de dados '%s'. Motivo: %s]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Clique para abrir as Configurações]]
    L["ShowTooltipInCombat"] = [[Mostrar Dicas de Ferramenta durante o combate]]
    L["ShowTooltipInCombatDescription"] = [[Escolha de ampliar as dicas de ferramenta também durante o combate. Desativado por padrão como medida de desempenho.]]
    L["AllowShiftExpansionInCombat"] = [[Permitir expansão de Shift durante o combate]]
    L["AllowShiftExpansionInCombatDescription"] = [[Escolha de processar os dados ampliados também durante o combate. Habilita a opção acima.]]
    L["ShowRank"] = [[Mostrar Grau]]
    L["ShowRankDescription"] = [[Ativar/desativas mostrar o grau às dicas de ferramenta.]]
    L["ShowAsp"] = [[Mostrar All Stars]]
    L["ShowAspDescription"] = [[Ativar/desativar mostrar os Pontos All Star às dicas de ferramenta.]]
    L["ShowShiftHint"] = [[Mostrar Dica de Shift]]
    L["ShowShiftHintDescription"] = [[Ativar/desativar a dica para expandir informações enquanto pressionar a tecla Shift.]]
    L["MenuIntegration"] = [[Ampliar Opções de Menu]]
    L["MenuIntegrationDescription"] = [[Escolha de ampliar os menus com uma opção de copiar a URL do perfil de um personagem.]]
    L["SettingsLookupUsage"] = [[Uso: /%s procurar <name> <realm>]]
    L["SettingsLookupNoData"] = [[Nenhum dado encontrado.]]
    L["SettingsLookupDataFor"] = [[%s para %s - %s]]
    L["SettingsAvailableCommands"] = [[Comandos disponíveis:]]
    L["SettingsOpenSettingsLabel"] = [[abre as configurações]]
    L["SettingsLookupLabel"] = [[procurar um perfil por nome e reino]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Análises apresentadas após 20H ou 5M mortes"
        L["Encounter-3129"] = [[Sentinela do Plexo]]
        L["Encounter-3131"] = [[Fian'dhar]]
        L["Encounter-3130"] = [[Atalmas Naazindhri]]
        L["Encounter-3132"] = [[Tece-forja Araz]]
        L["Encounter-3122"] = [[Os Caça-almas]]
        L["Encounter-3133"] = [[Fractillus]]
        L["Encounter-3134"] = [[Rei do Nexus Salhadaar]]
        L["Encounter-3135"] = [[Dimensius, que Tudo Devora]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Análises apresentadas após: mortes por limiar "
        L["Encounter-51577"] = [[Jin'rokh, o Rebentador]]
        L["Encounter-51575"] = [[Horridon]]
        L["Encounter-51570"] = [[Conselho dos Anciãos]]
        L["Encounter-51565"] = [[Tórtus]]
        L["Encounter-51578"] = [[Megaira]]
        L["Encounter-51573"] = [[Ji-Kun]]
        L["Encounter-51572"] = [[Durumu, o Esquecido]]
        L["Encounter-51574"] = [[Primordius]]
        L["Encounter-51576"] = [[Animus Sombrio]]
        L["Encounter-51559"] = [[Qon de Ferro]]
        L["Encounter-51560"] = [[Empíreas Gêmeas]]
        L["Encounter-51579"] = [[Lei Shen]]
        L["Encounter-51580"] = [[Ra-den]]
        L["addon.parse-gate-description"] = "Análises apresentadas após: mortes por limiar "
        L["Encounter-51507"] = [[Vizir Imperial Zor'lok]]
        L["Encounter-51504"] = [[Senhor das Lâminas Ta'yak]]
        L["Encounter-51463"] = [[Garalon]]
        L["Encounter-51498"] = [[Senhor do Vento Mel'jarak]]
        L["Encounter-51499"] = [[Molda-âmbar Un'sok]]
        L["Encounter-51501"] = [[Grã-imperatriz Shek'zeer]]
        L["Encounter-51409"] = [[Protetores do Infinito]]
        L["Encounter-51505"] = [[Tsulong]]
        L["Encounter-51506"] = [[Lei Shi]]
        L["Encounter-51431"] = [[Sha do Medo]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Alvano]]
        L["Encounter-3196"] = [[Senhor das Feras]]
        L["Encounter-3188"] = [[Conselho Renascido]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif C_Seasons.GetActiveSeason() == 109 then
        L["addon.parse-gate-description"] = "Análises apresentadas após: mortes por limiar "
        L["Encounter-50623"] = [[Hidross, o Instável]]
        L["Encounter-50624"] = [[O Tocaieiro Subterrâneo]]
        L["Encounter-50625"] = [[Leóteras, o Cego]]
        L["Encounter-50626"] = [[Senhor do Abismo Karathress]]
        L["Encounter-50627"] = [[Morogrim Andamaré]]
        L["Encounter-50628"] = [[Lady Vashj]]
        L["Encounter-50730"] = [[Al'ar]]
        L["Encounter-50731"] = [[Aniquilador do Caos]]
        L["Encounter-50732"] = [[Alta-astromante Solarian]]
        L["Encounter-50733"] = [[Kael'thas Andassol]]
    elseif Private.IsClassicEra and (C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh or C_Seasons.GetActiveSeason() == 125) then
        L["addon.parse-gate-description"] = "Análises apresentadas após: mortes por limiar "
        L["Encounter-50649"] = [[Alto-rei Maulgar]]
        L["Encounter-50650"] = [[Gruul, o Matador de Dragões]]
        L["Encounter-50651"] = [[Magtheridon]]
    end
elseif locale == "ruRU" then
    L["Difficulty-1"] = "ПР"
    L["Difficulty-3"] = "Н"
    L["Difficulty-4"] = "Г"
    L["Difficulty-5"] = "Э"
    L["DifficultyName-1"] = "СПР"
    L["DifficultyName-3"] = "Обычный"
    L["DifficultyName-4"] = "Героический"
    L["DifficultyName-5"] = "Эпохальный"
    L["AllStars"] = "Все звезды"
    L["Rank"] = "Ранг"
    L["Kills"] = "Убийств"
    L["Unknown"] = [[Неизвестно]]
    L["UnknownRealm"] = [[[%s] Реалм '%s' (id %d) отсутствует в базе данных. Пожалуйста, сообщите об этом команде Warcraft Logs.]]
    L["CopyProfileURL"] = [[Скопировать WCL URL]]
    L["Subscriber"] = [[Подписчик]]
    L["ShiftToExpand"] = [[<Shift> чтобы расширить]]
    L["SubAddonMissing"] = [[[%s] База данных для '%s' (%s) отсутствует. Возможно, вы вошли в игру, когда аддон находился в процессе обновления. Проверьте в настольном приложении, завершилось ли обновление, а затем выполните команду '/reload', чтобы повторить попытку.]]
    L["DBLoadError"] = [[[%s] Не удалось загрузить базу данных для '%s'. Причина: %s]]
    L["Main"] = [[Главная]]
    L["ClickToOpenSettings"] = [[Нажмите, чтобы открыть Настройки]]
    L["ShowTooltipInCombat"] = [[Показывать тултип в бою]]
    L["ShowTooltipInCombatDescription"] = [[Нужно ли расширять всплывающую подсказку и в бою. По умолчанию отключено в качестве меры производительности.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Нужно ли отображать расширенные данные и в бою. Включает настройку выше.]]
    L["ShowRank"] = [[Показать ранг]]
    L["ShowRankDescription"] = [[Переключает добавление ранга во всплывающую подсказку.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Переключает добавление подсказки для раскрытия информации при удержании Shift.]]
    L["MenuIntegration"] = [[Расширение опций меню]]
    L["MenuIntegrationDescription"] = [[Нужно ли расширять меню опцией копирования URL-адреса профиля персонажа.]]
    L["SettingsLookupUsage"] = [[Использование: /%s lookup <имя> <реалм>]]
    L["SettingsLookupNoData"] = [[Данные не найдены.]]
    L["SettingsLookupDataFor"] = [[%s для %s - %s]]
    L["SettingsAvailableCommands"] = [[Доступные команды:]]
    L["SettingsOpenSettingsLabel"] = [[открывает настройки]]
    L["SettingsLookupLabel"] = [[поиск профиля по имени и региону]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Парсы показываются после 20Г или 5M убийств"
        L["Encounter-3129"] = [[Сплетенный страж]]
        L["Encounter-3131"] = [[Ткан'итар]]
        L["Encounter-3130"] = [[Стражница душ Наазиндри]]
        L["Encounter-3132"] = [[Ткач горна Араз]]
        L["Encounter-3122"] = [[Ловцы душ]]
        L["Encounter-3133"] = [[Разломий]]
        L["Encounter-3134"] = [[Соправитель Салхадаар]]
        L["Encounter-3135"] = [[Пространствус Всепоглощающий]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-51577"] = [[Джин'рок Разрушитель]]
        L["Encounter-51575"] = [[Хорридон]]
        L["Encounter-51570"] = [[Совет старейшин]]
        L["Encounter-51565"] = [[Тортос]]
        L["Encounter-51578"] = [[Мегера]]
        L["Encounter-51573"] = [[Цзи-Кунь]]
        L["Encounter-51572"] = [[Дуруму Позабытый]]
        L["Encounter-51574"] = [[Изначалий]]
        L["Encounter-51576"] = [[Темный Анимус]]
        L["Encounter-51559"] = [[Кон Железный]]
        L["Encounter-51560"] = [[Небесные сестры]]
        L["Encounter-51579"] = [[Лэй Шэнь]]
        L["Encounter-51580"] = [[Ра-ден]]
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-51507"] = [[Императорский визирь Зор'лок]]
        L["Encounter-51504"] = [[Повелитель клинков Та'як]]
        L["Encounter-51463"] = [[Гаралон]]
        L["Encounter-51498"] = [[Повелитель ветров Мел'джарак]]
        L["Encounter-51499"] = [[Ваятель янтаря Ун'сок]]
        L["Encounter-51501"] = [[Великая императрица Шек'зир]]
        L["Encounter-51409"] = [[Вечные защитники]]
        L["Encounter-51505"] = [[Цулон]]
        L["Encounter-51506"] = [[Лэй Ши]]
        L["Encounter-51431"] = [[Ша Страха]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Балназзар]]
        L["Encounter-3187"] = [[Беатриса]]
        L["Encounter-3186"] = [[Солистраза]]
        L["Encounter-3197"] = [[Мейсон]]
        L["Encounter-3196"] = [[Повелитель зверей]]
        L["Encounter-3188"] = [[Возрожденный совет]]
        L["Encounter-3190"] = [[Лилиан Восс]]
        L["Encounter-3189"] = [[Калдоран]]
    elseif C_Seasons.GetActiveSeason() == 109 then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-50623"] = [[Гидросс Нестабильный]]
        L["Encounter-50624"] = [[Скрытень из глубин]]
        L["Encounter-50625"] = [[Леотерас Слепец]]
        L["Encounter-50626"] = [[Повелитель глубин Каратресс]]
        L["Encounter-50627"] = [[Морогрим Волноступ]]
        L["Encounter-50628"] = [[Леди Вайш]]
        L["Encounter-50730"] = [[Ал'ар]]
        L["Encounter-50731"] = [[Страж Бездны]]
        L["Encounter-50732"] = [[Верховный звездочет Солариан]]
        L["Encounter-50733"] = [[Кель'тас Солнечный Скиталец]]
    elseif Private.IsClassicEra and (C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh or C_Seasons.GetActiveSeason() == 125) then
        L["addon.parse-gate-description"] = "Parses shown after 10H kills"
        L["Encounter-50649"] = [[Король Молгар]]
        L["Encounter-50650"] = [[Груул Драконобой]]
        L["Encounter-50651"] = [[Магтеридон]]
    end
elseif locale == "zhCN" then
    L["Difficulty-1"] = "随机"
    L["Difficulty-3"] = "普通"
    L["Difficulty-4"] = "英雄"
    L["Difficulty-5"] = "史诗"
    L["DifficultyName-1"] = "团队查找器"
    L["DifficultyName-3"] = "普通"
    L["DifficultyName-4"] = "英雄级"
    L["DifficultyName-5"] = "史诗级"
    L["AllStars"] = "全明星分"
    L["Rank"] = "排名"
    L["Kills"] = "击杀"
    L["Unknown"] = [[未知]]
    L["UnknownRealm"] = [[[%s] 服务器 '%s' (id %d) 不在数据库中。请报告给WCL团队。]]
    L["CopyProfileURL"] = [[复制 WCL 链接]]
    L["Subscriber"] = [[WCL会员]]
    L["ShiftToExpand"] = [[按住 <Shift> 展开]]
    L["SubAddonMissing"] = [[[%s] '%s' (%s) 的数据库缺失。可能是因为您在插件更新过程中登录了游戏。请检查WCL客户端以确认更新是否已完成，然后运行 '/reload' 再次尝试。]]
    L["DBLoadError"] = [[[%s] 无法加载 '%s' 的数据库。原因：%s]]
    L["Main"] = [[大号]]
    L["ClickToOpenSettings"] = [[点击打开设置]]
    L["ShowTooltipInCombat"] = [[在战斗中显示插件]]
    L["ShowTooltipInCombatDescription"] = [[是否在战斗中也显示插件。默认禁用以提高性能。]]
    L["AllowShiftExpansionInCombat"] = [[允许在战斗中按 Shift 扩展]]
    L["AllowShiftExpansionInCombatDescription"] = [[是否在战斗中也渲染扩展数据。需要先启用上述设置]]
    L["ShowRank"] = [[显示排名]]
    L["ShowRankDescription"] = [[切换在工具提示中添加排名的选项。]]
    L["ShowAsp"] = [[显示全明星分]]
    L["ShowAspDescription"] = [[切换在工具提示中添加全明星积分的选项。]]
    L["ShowShiftHint"] = [[显示 Shift 提示]]
    L["ShowShiftHintDescription"] = [[切换在按住Shift键时附加提示以展开信息的选项。]]
    L["MenuIntegration"] = [[扩展菜单选项]]
    L["MenuIntegrationDescription"] = [[是否扩展菜单以添加复制角色信息链接的选项。]]
    L["SettingsLookupUsage"] = [[用法: /%s 查找 <名字> <服务器>]]
    L["SettingsLookupNoData"] = [[没有找到数据]]
    L["SettingsLookupDataFor"] = [[%s 的 %s - %s]]
    L["SettingsAvailableCommands"] = [[可用命令：]]
    L["SettingsOpenSettingsLabel"] = [[打开设置]]
    L["SettingsLookupLabel"] = [[按角色名和服务器查找资料]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "分数在20次H或5次M击杀后显示"
        L["Encounter-3129"] = [[集能哨兵]]
        L["Encounter-3131"] = [[卢米萨尔]]
        L["Encounter-3130"] = [[缚魂者娜欣达利]]
        L["Encounter-3132"] = [[熔炉编织者阿拉兹]]
        L["Encounter-3122"] = [[狩魂猎手]]
        L["Encounter-3133"] = [[弗兰克提鲁斯]]
        L["Encounter-3134"] = [[节点之王萨哈达尔]]
        L["Encounter-3135"] = [[诸界吞噬者迪门修斯]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "分数在 10H 击杀后显示"
        L["Encounter-51577"] = [[击碎者金罗克]]
        L["Encounter-51575"] = [[赫利东]]
        L["Encounter-51570"] = [[长者议会]]
        L["Encounter-51565"] = [[托多斯]]
        L["Encounter-51578"] = [[墨格瑞拉]]
        L["Encounter-51573"] = [[季鹍]]
        L["Encounter-51572"] = [[遗忘者杜鲁姆]]
        L["Encounter-51574"] = [[普利莫修斯]]
        L["Encounter-51576"] = [[黑暗意志]]
        L["Encounter-51559"] = [[铁穹]]
        L["Encounter-51560"] = [[神女双天]]
        L["Encounter-51579"] = [[雷神]]
        L["Encounter-51580"] = [[莱登]]
        L["addon.parse-gate-description"] = "分数在 10H 击杀后显示"
        L["Encounter-51507"] = [[皇家宰相佐尔洛克]]
        L["Encounter-51504"] = [[刀锋领主塔亚克]]
        L["Encounter-51463"] = [[加拉隆]]
        L["Encounter-51498"] = [[风领主梅尔加拉克]]
        L["Encounter-51499"] = [[琥珀塑形者昂舒克]]
        L["Encounter-51501"] = [[大女皇夏柯希尔]]
        L["Encounter-51409"] = [[无尽守护者]]
        L["Encounter-51505"] = [[烛龙]]
        L["Encounter-51506"] = [[雷施]]
        L["Encounter-51431"] = [[惧之煞]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[巴纳扎尔]]
        L["Encounter-3187"] = [[碧阿崔克丝]]
        L["Encounter-3186"] = [[瑟莉斯塔萨]]
        L["Encounter-3197"] = [[梅森]]
        L["Encounter-3196"] = [[兽王]]
        L["Encounter-3188"] = [[复生议会]]
        L["Encounter-3190"] = [[莉莉安·沃斯]]
        L["Encounter-3189"] = [[凯尔多兰]]
    elseif C_Seasons.GetActiveSeason() == 109 then
        L["addon.parse-gate-description"] = "分数在 10H 击杀后显示"
        L["Encounter-50623"] = [[不稳定的海度斯]]
        L["Encounter-50624"] = [[鱼斯拉]]
        L["Encounter-50625"] = [[盲眼者莱欧瑟拉斯]]
        L["Encounter-50626"] = [[深水领主卡拉瑟雷斯]]
        L["Encounter-50627"] = [[莫洛格里·踏潮者]]
        L["Encounter-50628"] = [[瓦丝琪]]
        L["Encounter-50730"] = [[奥]]
        L["Encounter-50731"] = [[空灵机甲]]
        L["Encounter-50732"] = [[大星术师索兰莉安]]
        L["Encounter-50733"] = [[凯尔萨斯·逐日者]]
    elseif Private.IsClassicEra and (C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh or C_Seasons.GetActiveSeason() == 125) then
        L["addon.parse-gate-description"] = "分数在 10H 击杀后显示"
        L["Encounter-50649"] = [[莫加尔大王]]
        L["Encounter-50650"] = [[屠龙者格鲁尔]]
        L["Encounter-50651"] = [[玛瑟里顿]]
    end
elseif locale == "zhTW" then
    L["Difficulty-1"] = "隨團"
    L["Difficulty-3"] = "普通"
    L["Difficulty-4"] = "英雄"
    L["Difficulty-5"] = "傳奇"
    L["DifficultyName-1"] = "隨機團隊"
    L["DifficultyName-3"] = "普通"
    L["DifficultyName-4"] = "英雄"
    L["DifficultyName-5"] = "傳奇"
    L["AllStars"] = "全明星"
    L["Rank"] = "階級"
    L["Kills"] = "Kills"
    L["Unknown"] = [[未知]]
    L["UnknownRealm"] = [[[%s] 伺服器『%s』(ID %d) 不存在於資料庫，請向戰鬥紀錄團隊回報]]
    L["CopyProfileURL"] = [[複製WCL網址]]
    L["Subscriber"] = [[訂閱者]]
    L["ShiftToExpand"] = [[按住 <Shift> 展開]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] 無法載入資料庫 '%s'。原因: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[點擊開啟設定]]
    L["ShowTooltipInCombat"] = [[戰鬥中顯示工具提示]]
    L["ShowTooltipInCombatDescription"] = [[是否在戰鬥中延伸工具提示。預設停用以提升效能。]]
    L["AllowShiftExpansionInCombat"] = [[允許戰鬥中使用Shift擴展]]
    L["AllowShiftExpansionInCombatDescription"] = [[是否在戰鬥中渲染延伸資料。啟用上方設定。]]
    L["ShowRank"] = [[顯示排名]]
    L["ShowRankDescription"] = [[切換在工具提示中顯示排名]]
    L["ShowAsp"] = [[顯示所有星數]]
    L["ShowAspDescription"] = [[切換在工具提示中顯示所有星數點數]]
    L["ShowShiftHint"] = [[顯示Shift提示]]
    L["ShowShiftHintDescription"] = [[切換按住Shift時附加提示擴展資訊]]
    L["MenuIntegration"] = [[延伸選單選項]]
    L["MenuIntegrationDescription"] = [[是否延伸選單以複製角色個人檔案URL選項]]
    L["SettingsLookupUsage"] = [[使用方式：/%s 查詢 <名稱> <伺服器>]]
    L["SettingsLookupNoData"] = [[找不到資料]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[可用指令：]]
    L["SettingsOpenSettingsLabel"] = [[開啟設定]]
    L["SettingsLookupLabel"] = [[依據名稱與伺服器查詢角色個人檔案]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "戰績解鎖條件：累積20小時或500萬擊殺"
        L["Encounter-3129"] = [[Plexus Sentinel]]
        L["Encounter-3131"] = [[Loom'ithar]]
        L["Encounter-3130"] = [[Soulbinder Naazindhri]]
        L["Encounter-3132"] = [[Forgeweaver Araz]]
        L["Encounter-3122"] = [[The Soul Hunters]]
        L["Encounter-3133"] = [[Fractillus]]
        L["Encounter-3134"] = [[Nexus-King Salhadaar]]
        L["Encounter-3135"] = [[Dimensius, the All-Devouring]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "擊殺數達 後顯示解析數據"
        L["Encounter-51577"] = [[Jin'rokh the Breaker]]
        L["Encounter-51575"] = [[Horridon]]
        L["Encounter-51570"] = [[Council of Elders]]
        L["Encounter-51565"] = [[Tortos]]
        L["Encounter-51578"] = [[Megaera]]
        L["Encounter-51573"] = [[Ji-Kun]]
        L["Encounter-51572"] = [[Durumu the Forgotten]]
        L["Encounter-51574"] = [[Primordius]]
        L["Encounter-51576"] = [[Dark Animus]]
        L["Encounter-51559"] = [[Iron Qon]]
        L["Encounter-51560"] = [[Twin Empyreans]]
        L["Encounter-51579"] = [[Lei Shen]]
        L["Encounter-51580"] = [[Ra-den]]
        L["addon.parse-gate-description"] = "擊殺數達 後顯示解析數據"
        L["Encounter-51507"] = [[Imperial Vizier Zor'lok]]
        L["Encounter-51504"] = [[Blade Lord Ta'yak]]
        L["Encounter-51463"] = [[Garalon]]
        L["Encounter-51498"] = [[Wind Lord Mel'jarak]]
        L["Encounter-51499"] = [[Amber-Shaper Un'sok]]
        L["Encounter-51501"] = [[Grand Empress Shek'zeer]]
        L["Encounter-51409"] = [[Protectors of the Endless]]
        L["Encounter-51505"] = [[Tsulong]]
        L["Encounter-51506"] = [[Lei Shi]]
        L["Encounter-51431"] = [[Sha of Fear]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Beastmaster]]
        L["Encounter-3188"] = [[Reborn Council]]
        L["Encounter-3190"] = [[Lillian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif C_Seasons.GetActiveSeason() == 109 then
        L["addon.parse-gate-description"] = "擊殺數達 後顯示解析數據"
        L["Encounter-50623"] = [[Hydross the Unstable]]
        L["Encounter-50624"] = [[The Lurker Below]]
        L["Encounter-50625"] = [[Leotheras the Blind]]
        L["Encounter-50626"] = [[Fathom-Lord Karathress]]
        L["Encounter-50627"] = [[Morogrim Tidewalker]]
        L["Encounter-50628"] = [[Lady Vashj]]
        L["Encounter-50730"] = [[Al'ar]]
        L["Encounter-50731"] = [[Void Reaver]]
        L["Encounter-50732"] = [[High Astromancer Solarian]]
        L["Encounter-50733"] = [[Kael'thas Sunstrider]]
    elseif Private.IsClassicEra and (C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh or C_Seasons.GetActiveSeason() == 125) then
        L["addon.parse-gate-description"] = "擊殺數達 後顯示解析數據"
        L["Encounter-50649"] = [[High King Maulgar]]
        L["Encounter-50650"] = [[Gruul the Dragonkiller]]
        L["Encounter-50651"] = [[Magtheridon]]
    end
end
