---@class Private
local Private = select(2, ...)

local L = Private.L

L["Difficulty-1"] = "L"
L["Difficulty-3"] = "N"
L["Difficulty-4"] = "H"
L["Difficulty-5"] = "M"
L["DifficultyName-1"] = "LFR"
L["DifficultyName-3"] = "Normal"
L["DifficultyName-4"] = "Heroic"
L["DifficultyName-5"] = "Mythic"
L["AllStars"] = "All Stars"
L["Rank"] = "Rank"
L["Kills"] = "Kills"
L["Unknown"] = [[Unknown]]
L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
L["CopyProfileURL"] = [[Copy WCL URL]]
L["Subscriber"] = [[Subscriber]]
L["ShiftToExpand"] = [[<Shift> to Expand]]
L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
L["Main"] = [[Main]]
L["ClickToOpenSettings"] = [[Click to open Settings]]
L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
L["ShowRank"] = [[Show Rank]]
L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
L["ShowAsp"] = [[Show All Stars]]
L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
L["ShowShiftHint"] = [[Show Shift Hint]]
L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
L["MenuIntegration"] = [[Extend Menu Options]]
L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
L["SettingsLookupNoData"] = [[No data found.]]
L["SettingsLookupDataFor"] = [[%s for %s - %s]]
L["SettingsAvailableCommands"] = [[Available commands:]]
L["SettingsOpenSettingsLabel"] = [[opens the settings]]
L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

if Private.IsRetail then
    L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
    L["Encounter-3009"] = [[Vexie and the Geargrinders]]
    L["Encounter-3010"] = [[Cauldron of Carnage]]
    L["Encounter-3011"] = [[Rik Reverb]]
    L["Encounter-3012"] = [[Stix Bunkjunker]]
    L["Encounter-3013"] = [[Sprocketmonger Lockenstock]]
    L["Encounter-3014"] = [[One-Armed Bandit]]
    L["Encounter-3015"] = [[Mug'Zee, Heads of Security]]
    L["Encounter-3016"] = [[Chrome King Gallywix]]
elseif Private.IsCata then
    L["addon.parse-gate-description"] = "Parses shown after 20H kills"
    L["Encounter-1292"] = [[Morchok]]
    L["Encounter-1294"] = [[Warlord Zon'ozz]]
    L["Encounter-1295"] = [[Yor'sahj the Unsleeping]]
    L["Encounter-1296"] = [[Hagara the Stormbinder]]
    L["Encounter-1297"] = [[Ultraxion]]
    L["Encounter-1298"] = [[Warmaster Blackhorn]]
    L["Encounter-1291"] = [[Spine of Deathwing]]
    L["Encounter-1299"] = [[Madness of Deathwing]]
elseif Private.IsWrath then
    L["addon.parse-gate-description"] = "Parses shown after 20H kills"
    L["Encounter-50845"] = [[Lord Marrowgar]]
    L["Encounter-50846"] = [[Lady Deathwhisper]]
    L["Encounter-50847"] = [[Icecrown Gunship Battle]]
    L["Encounter-50848"] = [[Deathbringer Saurfang]]
    L["Encounter-50849"] = [[Festergut]]
    L["Encounter-50850"] = [[Rotface]]
    L["Encounter-50851"] = [[Professor Putricide]]
    L["Encounter-50852"] = [[Blood Council]]
    L["Encounter-50853"] = [[Queen Lana'thel]]
    L["Encounter-50854"] = [[Valithria Dreamwalker]]
    L["Encounter-50855"] = [[Sindragosa]]
    L["Encounter-50856"] = [[The Lich King]]
elseif Private.IsClassicEra then
    L["addon.parse-gate-description"] = ""
    L["Encounter-3185"] = [[Balnazzar]]
    L["Encounter-3187"] = [[Beatrix]]
    L["Encounter-3186"] = [[Solistrasza]]
    L["Encounter-3197"] = [[Mason]]
    L["Encounter-3196"] = [[Beastmaster]]
    L["Encounter-3188"] = [[Reborn Council]]
    L["Encounter-3190"] = [[Lilian Voss]]
    L["Encounter-3189"] = [[Caldoran]]
end

local locale = GAME_LOCALE or GetLocale()

if locale == "deDE" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "Schlachtzugsbrowser"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroisch"
    L["DifficultyName-5"] = "Mythisch"
    L["AllStars"] = "Bestplatzierte"
    L["Rank"] = "Rang"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unbekannt]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Abonnent]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3009"] = [[Strolch und die Gangzwinger]]
        L["Encounter-3010"] = [[Kessel des Gemetzels]]
        L["Encounter-3011"] = [[Rik Resonanz]]
        L["Encounter-3012"] = [[Stix Kojenschrotter]]
        L["Encounter-3013"] = [[Ritzelkrämer Lockenstock]]
        L["Encounter-3014"] = [[Einarmiger Bandit]]
        L["Encounter-3015"] = [[Mug'Zee, Wachleitung]]
        L["Encounter-3016"] = [[Chromkönig Gallywix]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-1292"] = [[Morchok]]
        L["Encounter-1294"] = [[Kriegsherr Zon'ozz]]
        L["Encounter-1295"] = [[Yor'sahj der Unermüdliche]]
        L["Encounter-1296"] = [[Hagara die Sturmbinderin]]
        L["Encounter-1297"] = [[Ultraxion]]
        L["Encounter-1298"] = [[Kriegsmeister Schwarzhorn]]
        L["Encounter-1291"] = [[Todesschwinges Rückgrat]]
        L["Encounter-1299"] = [[Todesschwinges Wahnsinn]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[Lord Mark'gar]]
        L["Encounter-50846"] = [[Lady Todeswisper]]
        L["Encounter-50847"] = [[Kanonenschiffsschlacht von Eiskrone]]
        L["Encounter-50848"] = [[Todesbringer Saurfang]]
        L["Encounter-50849"] = [[Fauldarm]]
        L["Encounter-50850"] = [[Modermiene]]
        L["Encounter-50851"] = [[Professor Seuchenmord]]
        L["Encounter-50852"] = [[Rat des Blutes]]
        L["Encounter-50853"] = [[Blutkönigin Lana'thel]]
        L["Encounter-50854"] = [[Valithria Traumwandler]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[Der Lichkönig]]
    elseif Private.IsClassicEra then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Bestienmeister]]
        L["Encounter-3188"] = [[Wiedergeborener Rat]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    end
elseif locale == "esES" or locale == "esMX" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "BDB"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroico"
    L["DifficultyName-5"] = "Mítico"
    L["AllStars"] = "Los Mejores"
    L["Rank"] = "Rango"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Desconocido]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copiar URL de WCL]]
    L["Subscriber"] = [[Subscriptor ]]
    L["ShiftToExpand"] = [[<Shift> para expandir]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] No se ha podido cargar la base de datos de '%s'. Motivo: %s ]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3009"] = [[Vexie y los Cadenas]]
        L["Encounter-3010"] = [[Caldera de la Carnicería]]
        L["Encounter-3011"] = [[Rik Reverberación]]
        L["Encounter-3012"] = [[Stix Chatarracatre]]
        L["Encounter-3013"] = [[Piñonero Todolisto]]
        L["Encounter-3014"] = [[Bandido manco]]
        L["Encounter-3015"] = [[Mug'Zee, responsable de seguridad]]
        L["Encounter-3016"] = [[Rey Cromado Gallywix]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-1292"] = [[Morchok]]
        L["Encounter-1294"] = [[Señor de la guerra Zon'ozz]]
        L["Encounter-1295"] = [[Yor'sahj el Velador]]
        L["Encounter-1296"] = [[Hagara la Vinculatormentas]]
        L["Encounter-1297"] = [[Ultraxion]]
        L["Encounter-1298"] = [[Maestro de guerra Cuerno Negro]]
        L["Encounter-1291"] = [[Espinazo de Alamuerte]]
        L["Encounter-1299"] = [[Locura de Alamuerte]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[Lord Tuétano]]
        L["Encounter-50846"] = [[Lady Susurramuerte]]
        L["Encounter-50847"] = [[Batalla de naves de guerra de Corona de Hielo]]
        L["Encounter-50848"] = [[Libramorte Colmillosauro]]
        L["Encounter-50849"] = [[Panzachancro]]
        L["Encounter-50850"] = [[Carapútrea]]
        L["Encounter-50851"] = [[Profesor Putricidio]]
        L["Encounter-50852"] = [[Consejo de Sangre]]
        L["Encounter-50853"] = [[Reina Lana'thel]]
        L["Encounter-50854"] = [[Valithria Caminasueños]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[El Rey Exánime]]
    elseif Private.IsClassicEra then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Maestro de bestias]]
        L["Encounter-3188"] = [[Consejo renacido]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    end
elseif locale == "frFR" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "LFR"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Héroïque"
    L["DifficultyName-5"] = "Mythique"
    L["AllStars"] = "All Stars"
    L["Rank"] = "Rang"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Inconnu]]
    L["UnknownRealm"] = [[[%s] Le royaume '%s' (identifiant %d) n'est pas dans la base de données. Merci de contacter l'équipe de Warcraft Logs.]]
    L["CopyProfileURL"] = [[Copier l'URL WarcraftLogs]]
    L["Subscriber"] = [[Abonné]]
    L["ShiftToExpand"] = [[<Maj> pour déplier]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Impossible de charger la base de données de '%s'. Raison : %s]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Cliquez pour ouvrir les Paramètres]]
    L["ShowTooltipInCombat"] = [[Afficher l'Infobulle en Combat]]
    L["ShowTooltipInCombatDescription"] = [[Choisir si l'infobulle doit également être affichée en combat. Désactivé par défaut pour des raisons de performance.]]
    L["AllowShiftExpansionInCombat"] = [[Autoriser l'extension avec Shift en combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Choisir si les données étendues doivent également être affichées en combat. Active le paramètre ci-dessus.]]
    L["ShowRank"] = [[Afficher le rang]]
    L["ShowRankDescription"] = [[Active/Désactive l'ajout du rang à l'infobulle.]]
    L["ShowAsp"] = [[Montrer les All Stars]]
    L["ShowAspDescription"] = [[Active/Désactive l'ajout des points All Stars à l'infobulle.]]
    L["ShowShiftHint"] = [[Afficher l'astuce avec Shift]]
    L["ShowShiftHintDescription"] = [[Active/Désactive l'ajout de l'astuce pour étendre l'info en maintenant Shift.]]
    L["MenuIntegration"] = [[Étendre les options du menu]]
    L["MenuIntegrationDescription"] = [[Choisir si les menus doivent être étendus avec l'option de copier l'URL de profil du personnage.]]
    L["SettingsLookupUsage"] = [[Utilisation: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[Aucune donnée trouvée.]]
    L["SettingsLookupDataFor"] = [[%s pour %s - %s]]
    L["SettingsAvailableCommands"] = [[Commandes disponibles : ]]
    L["SettingsOpenSettingsLabel"] = [[ouvre les paramètres]]
    L["SettingsLookupLabel"] = [[rechercher un profil par nom  et royaume]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Les parses seront affichés après 20H ou 5M boss tués"
        L["Encounter-3009"] = [[Vexie et les Écrouabouilles]]
        L["Encounter-3010"] = [[Chaudron du carnage]]
        L["Encounter-3011"] = [[Rik Rebond]]
        L["Encounter-3012"] = [[Stix Jettetout]]
        L["Encounter-3013"] = [[Pignonneur Crosseplatine]]
        L["Encounter-3014"] = [[Bandit manchot]]
        L["Encounter-3015"] = [[Verr’Minh, chefs de la sécurité]]
        L["Encounter-3016"] = [[Roi du chrome Gallywix]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Les parses seront affichés après 20H boss tués"
        L["Encounter-1292"] = [[Morchok]]
        L["Encounter-1294"] = [[Seigneur de guerre Zon’ozz]]
        L["Encounter-1295"] = [[Yor'sahj l’Insomniaque]]
        L["Encounter-1296"] = [[Hagara la Lieuse des tempêtes]]
        L["Encounter-1297"] = [[Ultraxion]]
        L["Encounter-1298"] = [[Maître de guerre Corne-Noire]]
        L["Encounter-1291"] = [[Échine d’Aile de mort]]
        L["Encounter-1299"] = [[Folie d’Aile de mort]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Les parses seront affichés après 20H boss tués"
        L["Encounter-50845"] = [[Seigneur Gargamoelle]]
        L["Encounter-50846"] = [[Dame Murmemort]]
        L["Encounter-50847"] = [[Bataille des canonnières de la Couronne de glace]]
        L["Encounter-50848"] = [[Porte-mort Saurcroc]]
        L["Encounter-50849"] = [[Pulentraille]]
        L["Encounter-50850"] = [[Trognepus]]
        L["Encounter-50851"] = [[Professeur Putricide]]
        L["Encounter-50852"] = [[Conseil de sang]]
        L["Encounter-50853"] = [[Reine Lana’thel]]
        L["Encounter-50854"] = [[Valithria Marcherêve]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[Roi-liche]]
    elseif Private.IsClassicEra then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Maçon]]
        L["Encounter-3196"] = [[Belluaire]]
        L["Encounter-3188"] = [[Le conseil ressuscité]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    end
elseif locale == "itIT" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "LFR"
    L["DifficultyName-3"] = "Normale"
    L["DifficultyName-4"] = "Eroico"
    L["DifficultyName-5"] = "Mitico"
    L["AllStars"] = "Classificazione All-Stars"
    L["Rank"] = "Rango"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unknown]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Subscriber]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3009"] = [[Vexie e i Pestaruote]]
        L["Encounter-3010"] = [[Calderone del Massacro]]
        L["Encounter-3011"] = [[Rik Riverbero]]
        L["Encounter-3012"] = [[Stix Tritabrande]]
        L["Encounter-3013"] = [[Ingraniere Lockenstock]]
        L["Encounter-3014"] = [[Bandito con un Braccio Solo]]
        L["Encounter-3015"] = [[Mug'zee, Capi della Sicurezza]]
        L["Encounter-3016"] = [[Re Cromato Gallywix]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-1292"] = [[Morchok]]
        L["Encounter-1294"] = [[Zon'ozz il Signore della Guerra]]
        L["Encounter-1295"] = [[Yor'sahj il Senza Sonno]]
        L["Encounter-1296"] = [[Hagara la Tempestosa]]
        L["Encounter-1297"] = [[Ultraxion]]
        L["Encounter-1298"] = [[Maestro di Guerra Corno Nero]]
        L["Encounter-1291"] = [[Spina Dorsale di Alamorte]]
        L["Encounter-1299"] = [[Follia di Alamorte]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[Lord Marrowgar]]
        L["Encounter-50846"] = [[Lady Deathwhisper]]
        L["Encounter-50847"] = [[Icecrown Gunship Battle]]
        L["Encounter-50848"] = [[Deathbringer Saurfang]]
        L["Encounter-50849"] = [[Festergut]]
        L["Encounter-50850"] = [[Rotface]]
        L["Encounter-50851"] = [[Professor Putricide]]
        L["Encounter-50852"] = [[Blood Council]]
        L["Encounter-50853"] = [[Queen Lana'thel]]
        L["Encounter-50854"] = [[Valithria Dreamwalker]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[The Lich King]]
    elseif Private.IsClassicEra then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Beastmaster]]
        L["Encounter-3188"] = [[Reborn Council]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    end
elseif locale == "koKO" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "일반"
    L["Difficulty-4"] = "영웅"
    L["Difficulty-5"] = "신화"
    L["DifficultyName-1"] = "공격대 찾기"
    L["DifficultyName-3"] = "일반"
    L["DifficultyName-4"] = "영웅"
    L["DifficultyName-5"] = "신화"
    L["AllStars"] = "올스타"
    L["Rank"] = "등급"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unknown]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Subscriber]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3009"] = [[벡시와 연마공]]
        L["Encounter-3010"] = [[살육의 도가니]]
        L["Encounter-3011"] = [[리크 리버브]]
        L["Encounter-3012"] = [[스틱스 벙크정커]]
        L["Encounter-3013"] = [[스프로켓몽거 로켄스톡]]
        L["Encounter-3014"] = [[외팔이 좀도둑]]
        L["Encounter-3015"] = [[보안 책임자 머그지]]
        L["Encounter-3016"] = [[크롬왕 갤리윅스]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-1292"] = [[모르초크]]
        L["Encounter-1294"] = [[장군 존오즈]]
        L["Encounter-1295"] = [[잠들지 않는 요르사지]]
        L["Encounter-1296"] = [[하가라]]
        L["Encounter-1297"] = [[울트락시온]]
        L["Encounter-1298"] = [[전투대장 블랙혼]]
        L["Encounter-1291"] = [[데스윙의 등]]
        L["Encounter-1299"] = [[데스윙의 광기]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[군주 매로우가르]]
        L["Encounter-50846"] = [[여교주 데스위스퍼]]
        L["Encounter-50847"] = [[얼음왕관 비행포격선 전투]]
        L["Encounter-50848"] = [[죽음의 인도자 사울팽]]
        L["Encounter-50849"] = [[구린속]]
        L["Encounter-50850"] = [[썩은얼굴]]
        L["Encounter-50851"] = [[교수 퓨트리사이드]]
        L["Encounter-50852"] = [[피의 의회]]
        L["Encounter-50853"] = [[여왕 라나텔]]
        L["Encounter-50854"] = [[발리스리아 드림워커]]
        L["Encounter-50855"] = [[신드라고사]]
        L["Encounter-50856"] = [[리치 왕]]
    elseif Private.IsClassicEra then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[발나자르]]
        L["Encounter-3187"] = [[베아트릭스]]
        L["Encounter-3186"] = [[솔리스트라자]]
        L["Encounter-3197"] = [[석공]]
        L["Encounter-3196"] = [[야수조련사]]
        L["Encounter-3188"] = [[부활의 의회]]
        L["Encounter-3190"] = [[릴리안 보스]]
        L["Encounter-3189"] = [[칼도란]]
    end
elseif locale == "ptBR" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "D"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "PPR"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroico"
    L["DifficultyName-5"] = "Mítico"
    L["AllStars"] = "Maiores Estrelas"
    L["Rank"] = "Ranque"
    L["Kills"] = "Abates"
    L["Unknown"] = [[Desconhecido]]
    L["UnknownRealm"] = [[[%s] Domínio '%s' (id %d) não está no banco de dados. Por favor, reporte-se à equipe do Warcraft Logs.]]
    L["CopyProfileURL"] = [[Copiar URL do WCL]]
    L["Subscriber"] = [[Assinante]]
    L["ShiftToExpand"] = [[<Shift> para expandir]]
    L["SubAddonMissing"] = [[[%s] Base de dados para '%s' (%s) está ausente. Pode ser que você tenha entrado no jogo enquanto o 'addon' estava no meio de uma atualização. Verifique o aplicativo no 'desktop' para ver se a atualização foi concluída, e então execute '/reload' para tentar novamente.]]
    L["DBLoadError"] = [[[%s] Não foi possível carregar a base de dados '%s'. Motivo: %s]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Clique para abrir as Configurações]]
    L["ShowTooltipInCombat"] = [[Mostrar Dicas de Ferramenta durante o combate]]
    L["ShowTooltipInCombatDescription"] = [[Escolha de ampliar as dicas de ferramenta também durante o combate. Desativado por padrão como medida de desempenho.]]
    L["AllowShiftExpansionInCombat"] = [[Permitir expansão de Shift durante o combate]]
    L["AllowShiftExpansionInCombatDescription"] = [[Escolha de processar os dados ampliados também durante o combate. Habilita a opção acima.]]
    L["ShowRank"] = [[Mostrar Grau]]
    L["ShowRankDescription"] = [[Ativar/desativas mostrar o grau às dicas de ferramenta.]]
    L["ShowAsp"] = [[Mostrar All Stars]]
    L["ShowAspDescription"] = [[Ativar/desativar mostrar os Pontos All Star às dicas de ferramenta.]]
    L["ShowShiftHint"] = [[Mostrar Dica de Shift]]
    L["ShowShiftHintDescription"] = [[Ativar/desativar a dica para expandir informações enquanto pressionar a tecla Shift.]]
    L["MenuIntegration"] = [[Ampliar Opções de Menu]]
    L["MenuIntegrationDescription"] = [[Escolha de ampliar os menus com uma opção de copiar a URL do perfil de um personagem.]]
    L["SettingsLookupUsage"] = [[Uso: /%s procurar <name> <realm>]]
    L["SettingsLookupNoData"] = [[Nenhum dado encontrado.]]
    L["SettingsLookupDataFor"] = [[%s para %s - %s]]
    L["SettingsAvailableCommands"] = [[Comandos disponíveis:]]
    L["SettingsOpenSettingsLabel"] = [[abre as configurações]]
    L["SettingsLookupLabel"] = [[procurar um perfil por nome e reino]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Análises apresentadas após 20H ou 5M mortes"
        L["Encounter-3009"] = [[Vexie e os Trincatracas]]
        L["Encounter-3010"] = [[Caldeirão da Carnificina]]
        L["Encounter-3011"] = [[Rik Reverb]]
        L["Encounter-3012"] = [[Stix Sucateiro]]
        L["Encounter-3013"] = [[Rebimbocador Travaguarda]]
        L["Encounter-3014"] = [[Bandido de Um Braço]]
        L["Encounter-3015"] = [[Mag'Guila, Chefes de Segurança]]
        L["Encounter-3016"] = [[Rei do Cromo Gallywix]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Análises apresentadas após 20H mortes"
        L["Encounter-1292"] = [[Morchok]]
        L["Encounter-1294"] = [[Senhor da Guerra Zon'ozz]]
        L["Encounter-1295"] = [[Yor'sahj, o Vígil]]
        L["Encounter-1296"] = [[Hagara, a Tempestigadora]]
        L["Encounter-1297"] = [[Ultraxion]]
        L["Encounter-1298"] = [[Mestre Guerreiro Chifre Negro]]
        L["Encounter-1291"] = [[Espinhaço do Asa da Morte]]
        L["Encounter-1299"] = [[Loucura do Asa da Morte]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Análises apresentadas após 20H mortes"
        L["Encounter-50845"] = [[Lorde Medulante]]
        L["Encounter-50846"] = [[Lady Sibilamorte]]
        L["Encounter-50847"] = [[Batalha da Belonave da Coroa de Gelo]]
        L["Encounter-50848"] = [[Carrasco Saurfang]]
        L["Encounter-50849"] = [[Tripapútrida]]
        L["Encounter-50850"] = [[Rostorroto]]
        L["Encounter-50851"] = [[Professor Putricida]]
        L["Encounter-50852"] = [[Concílio de Sangue]]
        L["Encounter-50853"] = [[Rainha Lana'thel]]
        L["Encounter-50854"] = [[Valithria Andassonho]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[O Lich Rei]]
    elseif Private.IsClassicEra then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Alvano]]
        L["Encounter-3196"] = [[Senhor das Feras]]
        L["Encounter-3188"] = [[Conselho Renascido]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    end
elseif locale == "ruRU" then
    L["Difficulty-1"] = "ПР"
    L["Difficulty-3"] = "Н"
    L["Difficulty-4"] = "Г"
    L["Difficulty-5"] = "Э"
    L["DifficultyName-1"] = "СПР"
    L["DifficultyName-3"] = "Обычный"
    L["DifficultyName-4"] = "Героический"
    L["DifficultyName-5"] = "Эпохальный"
    L["AllStars"] = "Все звезды"
    L["Rank"] = "Ранг"
    L["Kills"] = "Убийств"
    L["Unknown"] = [[Неизвестно]]
    L["UnknownRealm"] = [[[%s] Реалм '%s' (id %d) отсутствует в базе данных. Пожалуйста, сообщите об этом команде Warcraft Logs.]]
    L["CopyProfileURL"] = [[Скопировать WCL URL]]
    L["Subscriber"] = [[Подписчик]]
    L["ShiftToExpand"] = [[<Shift> чтобы расширить]]
    L["SubAddonMissing"] = [[[%s] База данных для '%s' (%s) отсутствует. Возможно, вы вошли в игру, когда аддон находился в процессе обновления. Проверьте в настольном приложении, завершилось ли обновление, а затем выполните команду '/reload', чтобы повторить попытку.]]
    L["DBLoadError"] = [[[%s] Не удалось загрузить базу данных для '%s'. Причина: %s]]
    L["Main"] = [[Главная]]
    L["ClickToOpenSettings"] = [[Нажмите, чтобы открыть Настройки]]
    L["ShowTooltipInCombat"] = [[Показывать тултип в бою]]
    L["ShowTooltipInCombatDescription"] = [[Нужно ли расширять всплывающую подсказку и в бою. По умолчанию отключено в качестве меры производительности.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Нужно ли отображать расширенные данные и в бою. Включает настройку выше.]]
    L["ShowRank"] = [[Показать ранг]]
    L["ShowRankDescription"] = [[Переключает добавление ранга во всплывающую подсказку.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Переключает добавление подсказки для раскрытия информации при удержании Shift.]]
    L["MenuIntegration"] = [[Расширение опций меню]]
    L["MenuIntegrationDescription"] = [[Нужно ли расширять меню опцией копирования URL-адреса профиля персонажа.]]
    L["SettingsLookupUsage"] = [[Использование: /%s lookup <имя> <реалм>]]
    L["SettingsLookupNoData"] = [[Данные не найдены.]]
    L["SettingsLookupDataFor"] = [[%s для %s - %s]]
    L["SettingsAvailableCommands"] = [[Доступные команды:]]
    L["SettingsOpenSettingsLabel"] = [[открывает настройки]]
    L["SettingsLookupLabel"] = [[поиск профиля по имени и региону]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Парсы показываются после 20Г или 5M убийств"
        L["Encounter-3009"] = [[Векси и зуботочеры]]
        L["Encounter-3010"] = [[Котел смерти]]
        L["Encounter-3011"] = [[Рик Ревербер]]
        L["Encounter-3012"] = [[Стикс Бункохламзень]]
        L["Encounter-3013"] = [[Зубцеторг Всесхватс]]
        L["Encounter-3014"] = [[Однорукий бандит]]
        L["Encounter-3015"] = [[Граб'Зи, главы отдела охраны]]
        L["Encounter-3016"] = [[Хромовый король Галливикс]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Парсы показываются после 20Г убийств"
        L["Encounter-1292"] = [[Морхок]]
        L["Encounter-1294"] = [[Полководец Зон'озз]]
        L["Encounter-1295"] = [[Йор'садж Неспящий]]
        L["Encounter-1296"] = [[Хагара Владычица Штормов]]
        L["Encounter-1297"] = [[Ультраксион]]
        L["Encounter-1298"] = [[Воевода Черный Рог]]
        L["Encounter-1291"] = [[Хребет Смертокрыла]]
        L["Encounter-1299"] = [[Безумие Смертокрыла]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Парсы показываются после 20Г убийств"
        L["Encounter-50845"] = [[Лорд Ребрад]]
        L["Encounter-50846"] = [[Леди Смертный Шепот]]
        L["Encounter-50847"] = [[Битва на кораблях в Ледяной Короне]]
        L["Encounter-50848"] = [[Саурфанг Смертоносный]]
        L["Encounter-50849"] = [[Тухлопуз]]
        L["Encounter-50850"] = [[Гниломорд]]
        L["Encounter-50851"] = [[Профессор Мерзоцид]]
        L["Encounter-50852"] = [[Кровавый Совет]]
        L["Encounter-50853"] = [[Королева Лана'тель]]
        L["Encounter-50854"] = [[Валитрия Сноходица]]
        L["Encounter-50855"] = [[Синдрагоса]]
        L["Encounter-50856"] = [[Король-лич]]
    elseif Private.IsClassicEra then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Балназзар]]
        L["Encounter-3187"] = [[Беатриса]]
        L["Encounter-3186"] = [[Солистраза]]
        L["Encounter-3197"] = [[Мейсон]]
        L["Encounter-3196"] = [[Повелитель зверей]]
        L["Encounter-3188"] = [[Возрожденный совет]]
        L["Encounter-3190"] = [[Лилиан Восс]]
        L["Encounter-3189"] = [[Калдоран]]
    end
elseif locale == "zhCN" then
    L["Difficulty-1"] = "随机"
    L["Difficulty-3"] = "普通"
    L["Difficulty-4"] = "英雄"
    L["Difficulty-5"] = "史诗"
    L["DifficultyName-1"] = "团队查找器"
    L["DifficultyName-3"] = "普通"
    L["DifficultyName-4"] = "英雄级"
    L["DifficultyName-5"] = "史诗级"
    L["AllStars"] = "全明星分"
    L["Rank"] = "排名"
    L["Kills"] = "击杀"
    L["Unknown"] = [[未知]]
    L["UnknownRealm"] = [[[%s] 服务器 '%s' (id %d) 不在数据库中。请报告给WCL团队。]]
    L["CopyProfileURL"] = [[复制 WCL 链接]]
    L["Subscriber"] = [[WCL会员]]
    L["ShiftToExpand"] = [[按住 <Shift> 展开]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] 无法加载 '%s' 的数据库。原因：%s]]
    L["Main"] = [[大号]]
    L["ClickToOpenSettings"] = [[点击打开设置]]
    L["ShowTooltipInCombat"] = [[在战斗中显示插件]]
    L["ShowTooltipInCombatDescription"] = [[是否在战斗中也显示插件。默认禁用以提高性能。]]
    L["AllowShiftExpansionInCombat"] = [[允许在战斗中按 Shift 扩展]]
    L["AllowShiftExpansionInCombatDescription"] = [[是否在战斗中也渲染扩展数据。需要先启用上述设置]]
    L["ShowRank"] = [[显示排名]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[显示全明星分]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[显示 Shift 提示]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[没有找到数据]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "分数在20次H或5次M击杀后显示"
        L["Encounter-3009"] = [[维克茜和磨轮]]
        L["Encounter-3010"] = [[血腥大熔炉]]
        L["Encounter-3011"] = [[里克·混响]]
        L["Encounter-3012"] = [[斯提克斯·堆渣]]
        L["Encounter-3013"] = [[链齿狂人洛肯斯多]]
        L["Encounter-3014"] = [[独臂盗匪]]
        L["Encounter-3015"] = [[穆格·兹伊，安保头子]]
        L["Encounter-3016"] = [[铬武大王加里维克斯]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "分数在20次H击杀后显示"
        L["Encounter-1292"] = [[莫卓克]]
        L["Encounter-1294"] = [[督军佐诺兹]]
        L["Encounter-1295"] = [[不眠的约萨希]]
        L["Encounter-1296"] = [[缚风者哈格拉]]
        L["Encounter-1297"] = [[奥卓克希昂]]
        L["Encounter-1298"] = [[战争大师黑角]]
        L["Encounter-1291"] = [[死亡之翼的背脊]]
        L["Encounter-1299"] = [[疯狂的死亡之翼]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "分数在20次H击杀后显示"
        L["Encounter-50845"] = [[玛洛加尔领主]]
        L["Encounter-50846"] = [[亡语者女士]]
        L["Encounter-50847"] = [[冰冠冰川炮舰战]]
        L["Encounter-50848"] = [[死亡使者萨鲁法尔]]
        L["Encounter-50849"] = [[烂肠]]
        L["Encounter-50850"] = [[腐面]]
        L["Encounter-50851"] = [[普崔塞德教授]]
        L["Encounter-50852"] = [[鲜血议会]]
        L["Encounter-50853"] = [[兰娜瑟尔女王]]
        L["Encounter-50854"] = [[踏梦者瓦莉瑟瑞娅]]
        L["Encounter-50855"] = [[辛达苟萨]]
        L["Encounter-50856"] = [[巫妖王]]
    elseif Private.IsClassicEra then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[巴纳扎尔]]
        L["Encounter-3187"] = [[碧阿崔克丝]]
        L["Encounter-3186"] = [[瑟莉斯塔萨]]
        L["Encounter-3197"] = [[梅森]]
        L["Encounter-3196"] = [[兽王]]
        L["Encounter-3188"] = [[复生议会]]
        L["Encounter-3190"] = [[莉莉安·沃斯]]
        L["Encounter-3189"] = [[凯尔多兰]]
    end
elseif locale == "zhTW" then
    L["Difficulty-1"] = "隨團"
    L["Difficulty-3"] = "普通"
    L["Difficulty-4"] = "英雄"
    L["Difficulty-5"] = "傳奇"
    L["DifficultyName-1"] = "隨機團隊"
    L["DifficultyName-3"] = "普通"
    L["DifficultyName-4"] = "英雄"
    L["DifficultyName-5"] = "傳奇"
    L["AllStars"] = "全明星"
    L["Rank"] = "階級"
    L["Kills"] = "Kills"
    L["Unknown"] = [[未知]]
    L["UnknownRealm"] = [[[%s] 伺服器『%s』(ID %d) 不存在於資料庫，請向戰鬥紀錄團隊回報]]
    L["CopyProfileURL"] = [[複製WCL網址]]
    L["Subscriber"] = [[訂閱者]]
    L["ShiftToExpand"] = [[按住 <Shift> 展開]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "戰績解鎖條件：累積20小時或500萬擊殺"
        L["Encounter-3009"] = [[Vexie and the Geargrinders]]
        L["Encounter-3010"] = [[Cauldron of Carnage]]
        L["Encounter-3011"] = [[Rik Reverb]]
        L["Encounter-3012"] = [[Stix Bunkjunker]]
        L["Encounter-3013"] = [[Sprocketmonger Lockenstock]]
        L["Encounter-3014"] = [[One-Armed Bandit]]
        L["Encounter-3015"] = [[Mug'Zee, Heads of Security]]
        L["Encounter-3016"] = [[Chrome King Gallywix]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "戰績解鎖：累積20小時擊殺"
        L["Encounter-1292"] = [[Morchok]]
        L["Encounter-1294"] = [[Warlord Zon'ozz]]
        L["Encounter-1295"] = [[Yor'sahj the Unsleeping]]
        L["Encounter-1296"] = [[Hagara the Stormbinder]]
        L["Encounter-1297"] = [[Ultraxion]]
        L["Encounter-1298"] = [[Warmaster Blackhorn]]
        L["Encounter-1291"] = [[Spine of Deathwing]]
        L["Encounter-1299"] = [[Madness of Deathwing]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "戰績解鎖：累積20小時擊殺"
        L["Encounter-50845"] = [[Lord Marrowgar]]
        L["Encounter-50846"] = [[Lady Deathwhisper]]
        L["Encounter-50847"] = [[Icecrown Gunship Battle]]
        L["Encounter-50848"] = [[Deathbringer Saurfang]]
        L["Encounter-50849"] = [[Festergut]]
        L["Encounter-50850"] = [[Rotface]]
        L["Encounter-50851"] = [[Professor Putricide]]
        L["Encounter-50852"] = [[Blood Council]]
        L["Encounter-50853"] = [[Queen Lana'thel]]
        L["Encounter-50854"] = [[Valithria Dreamwalker]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[The Lich King]]
    elseif Private.IsClassicEra then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Beastmaster]]
        L["Encounter-3188"] = [[Reborn Council]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    end
end
