---@class Private
local Private = select(2, ...)

local L = Private.L

L["Difficulty-1"] = "L"
L["Difficulty-3"] = "N"
L["Difficulty-4"] = "H"
L["Difficulty-5"] = "M"
L["DifficultyName-1"] = "LFR"
L["DifficultyName-3"] = "Normal"
L["DifficultyName-4"] = "Heroic"
L["DifficultyName-5"] = "Mythic"
L["AllStars"] = "All Stars"
L["Rank"] = "Rank"
L["Kills"] = "Kills"
L["Unknown"] = [[Unknown]]
L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
L["CopyProfileURL"] = [[Copy WCL URL]]
L["Subscriber"] = [[Subscriber]]
L["ShiftToExpand"] = [[<Shift> to Expand]]
L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
L["Main"] = [[Main]]
L["ClickToOpenSettings"] = [[Click to open Settings]]
L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
L["ShowRank"] = [[Show Rank]]
L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
L["ShowAsp"] = [[Show All Stars]]
L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
L["ShowShiftHint"] = [[Show Shift Hint]]
L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
L["MenuIntegration"] = [[Extend Menu Options]]
L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
L["SettingsLookupNoData"] = [[No data found.]]
L["SettingsLookupDataFor"] = [[%s for %s - %s]]
L["SettingsAvailableCommands"] = [[Available commands:]]
L["SettingsOpenSettingsLabel"] = [[opens the settings]]
L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

if Private.IsRetail then
    L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
    L["Encounter-3009"] = [[Vexie and the Geargrinders]]
    L["Encounter-3010"] = [[Cauldron of Carnage]]
    L["Encounter-3011"] = [[Rik Reverb]]
    L["Encounter-3012"] = [[Stix Bunkjunker]]
    L["Encounter-3013"] = [[Sprocketmonger Lockenstock]]
    L["Encounter-3014"] = [[One-Armed Bandit]]
    L["Encounter-3015"] = [[Mug'Zee, Heads of Security]]
    L["Encounter-3016"] = [[Chrome King Gallywix]]
elseif Private.IsMists then
    L["addon.parse-gate-description"] = "Parses shown after 15H kills"
    L["Encounter-1395"] = [[The Stone Guard]]
    L["Encounter-1390"] = [[Feng the Accursed]]
    L["Encounter-1434"] = [[Gara'jal the Spiritbinder]]
    L["Encounter-1436"] = [[The Spirit Kings]]
    L["Encounter-1500"] = [[Elegon]]
    L["Encounter-1407"] = [[Will of the Emperor]]
elseif Private.IsWrath then
    L["addon.parse-gate-description"] = "Parses shown after 20H kills"
    L["Encounter-50845"] = [[Lord Marrowgar]]
    L["Encounter-50846"] = [[Lady Deathwhisper]]
    L["Encounter-50847"] = [[Icecrown Gunship Battle]]
    L["Encounter-50848"] = [[Deathbringer Saurfang]]
    L["Encounter-50849"] = [[Festergut]]
    L["Encounter-50850"] = [[Rotface]]
    L["Encounter-50851"] = [[Professor Putricide]]
    L["Encounter-50852"] = [[Blood Council]]
    L["Encounter-50853"] = [[Queen Lana'thel]]
    L["Encounter-50854"] = [[Valithria Dreamwalker]]
    L["Encounter-50855"] = [[Sindragosa]]
    L["Encounter-50856"] = [[The Lich King]]
elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
    L["addon.parse-gate-description"] = ""
    L["Encounter-3185"] = [[Balnazzar]]
    L["Encounter-3187"] = [[Beatrix]]
    L["Encounter-3186"] = [[Solistrasza]]
    L["Encounter-3197"] = [[Mason]]
    L["Encounter-3196"] = [[Beastmaster]]
    L["Encounter-3188"] = [[Reborn Council]]
    L["Encounter-3190"] = [[Lillian Voss]]
    L["Encounter-3189"] = [[Caldoran]]
elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
    L["addon.parse-gate-description"] = "Parses shown after 20H kills"
    L["Encounter-150709"] = [[The Prophet Skeram]]
    L["Encounter-150710"] = [[Silithid Royalty]]
    L["Encounter-150711"] = [[Battleguard Sartura]]
    L["Encounter-150712"] = [[Fankriss the Unyielding]]
    L["Encounter-150713"] = [[Viscidus]]
    L["Encounter-150714"] = [[Princess Huhuran]]
    L["Encounter-150715"] = [[Twin Emperors]]
    L["Encounter-150716"] = [[Ouro]]
    L["Encounter-150717"] = [[C'Thun]]
end

local locale = GAME_LOCALE or GetLocale()

if locale == "deDE" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "Schlachtzugsbrowser"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroisch"
    L["DifficultyName-5"] = "Mythisch"
    L["AllStars"] = "Bestplatzierte"
    L["Rank"] = "Rang"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unbekannt]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Abonnent]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[Keine Daten gefunden]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3009"] = [[Strolch und die Gangzwinger]]
        L["Encounter-3010"] = [[Kessel des Gemetzels]]
        L["Encounter-3011"] = [[Rik Resonanz]]
        L["Encounter-3012"] = [[Stix Kojenschrotter]]
        L["Encounter-3013"] = [[Ritzelkrämer Lockenstock]]
        L["Encounter-3014"] = [[Einarmiger Bandit]]
        L["Encounter-3015"] = [[Mug'Zee, Wachleitung]]
        L["Encounter-3016"] = [[Chromkönig Gallywix]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 15H kills"
        L["Encounter-1395"] = [[Die Steinwache]]
        L["Encounter-1390"] = [[Feng der Verfluchte]]
        L["Encounter-1434"] = [[Gara'jal der Geisterbinder]]
        L["Encounter-1436"] = [[Die Geisterkönige]]
        L["Encounter-1500"] = [[Elegon]]
        L["Encounter-1407"] = [[Der Wille des Kaisers]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[Lord Mark'gar]]
        L["Encounter-50846"] = [[Lady Todeswisper]]
        L["Encounter-50847"] = [[Kanonenschiffsschlacht von Eiskrone]]
        L["Encounter-50848"] = [[Todesbringer Saurfang]]
        L["Encounter-50849"] = [[Fauldarm]]
        L["Encounter-50850"] = [[Modermiene]]
        L["Encounter-50851"] = [[Professor Seuchenmord]]
        L["Encounter-50852"] = [[Rat des Blutes]]
        L["Encounter-50853"] = [[Blutkönigin Lana'thel]]
        L["Encounter-50854"] = [[Valithria Traumwandler]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[Der Lichkönig]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Bestienmeister]]
        L["Encounter-3188"] = [[Wiedergeborener Rat]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-150709"] = [[Der Prophet Skeram]]
        L["Encounter-150710"] = [[Adel der Silithiden]]
        L["Encounter-150711"] = [[Schlachtwache Sartura]]
        L["Encounter-150712"] = [[Fankriss der Unnachgiebige]]
        L["Encounter-150713"] = [[Viscidus]]
        L["Encounter-150714"] = [[Prinzessin Huhuran]]
        L["Encounter-150715"] = [[Zwillingsimperatoren]]
        L["Encounter-150716"] = [[Ouro]]
        L["Encounter-150717"] = [[C'Thun]]
    end
elseif locale == "esES" or locale == "esMX" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "BDB"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroico"
    L["DifficultyName-5"] = "Mítico"
    L["AllStars"] = "Los Mejores"
    L["Rank"] = "Rango"
    L["Kills"] = "Asesinatos"
    L["Unknown"] = [[Desconocido]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copiar URL de WCL]]
    L["Subscriber"] = [[Suscriptor ]]
    L["ShiftToExpand"] = [[<Shift> para expandir]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] No se ha podido cargar la base de datos de '%s'. Motivo: %s ]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Haz clic para abrir la configuración]]
    L["ShowTooltipInCombat"] = [[Mostrar Tips de herramientas en Combate]]
    L["ShowTooltipInCombatDescription"] = [[Si extender los consejos de herramienta en combate también. Está desactivado de manera predeterminada como optimización]]
    L["AllowShiftExpansionInCombat"] = [[Mostrar extensión de shift en combate
]]
    L["AllowShiftExpansionInCombatDescription"] = [[Si cargar datos extendidos en combate también. Activa la configuración de arriba]]
    L["ShowRank"] = [[Mostrar rango]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Mostrar tips de Shift]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Opciones de menú extendidas]]
    L["MenuIntegrationDescription"] = [[Si extender los menús con una opción para copiar el URL del perfil del personaje]]
    L["SettingsLookupUsage"] = [[Uso /%s buscar <name> <realm>]]
    L["SettingsLookupNoData"] = [[Datos no encontrados]]
    L["SettingsLookupDataFor"] = [[%s para %s - %s]]
    L["SettingsAvailableCommands"] = [[Comandos disponibles:]]
    L["SettingsOpenSettingsLabel"] = [[Abre la configuración]]
    L["SettingsLookupLabel"] = [[buscar perfil por nombre y región]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3009"] = [[Vexie y los Cadenas]]
        L["Encounter-3010"] = [[Caldera de la Carnicería]]
        L["Encounter-3011"] = [[Rik Reverberación]]
        L["Encounter-3012"] = [[Stix Chatarracatre]]
        L["Encounter-3013"] = [[Piñonero Todolisto]]
        L["Encounter-3014"] = [[Bandido manco]]
        L["Encounter-3015"] = [[Mug'Zee, responsable de seguridad]]
        L["Encounter-3016"] = [[Rey Cromado Gallywix]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 15H kills"
        L["Encounter-1395"] = [[La guardia de piedra]]
        L["Encounter-1390"] = [[Feng el Detestable]]
        L["Encounter-1434"] = [[Gara'jal el Vinculador de Espíritus]]
        L["Encounter-1436"] = [[Los Reyes Espíritu]]
        L["Encounter-1500"] = [[Elegon]]
        L["Encounter-1407"] = [[Voluntad del Emperador]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[Lord Tuétano]]
        L["Encounter-50846"] = [[Lady Susurramuerte]]
        L["Encounter-50847"] = [[Batalla de naves de guerra de Corona de Hielo]]
        L["Encounter-50848"] = [[Libramorte Colmillosauro]]
        L["Encounter-50849"] = [[Panzachancro]]
        L["Encounter-50850"] = [[Carapútrea]]
        L["Encounter-50851"] = [[Profesor Putricidio]]
        L["Encounter-50852"] = [[Consejo de Sangre]]
        L["Encounter-50853"] = [[Reina Lana'thel]]
        L["Encounter-50854"] = [[Valithria Caminasueños]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[El Rey Exánime]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Maestro de bestias]]
        L["Encounter-3188"] = [[Consejo renacido]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-150709"] = [[El profeta Skeram]]
        L["Encounter-150710"] = [[Realeza silítida]]
        L["Encounter-150711"] = [[Guardia de batalla Sartura]]
        L["Encounter-150712"] = [[Fankriss el Implacable]]
        L["Encounter-150713"] = [[Viscidus]]
        L["Encounter-150714"] = [[Princesa Huhuran]]
        L["Encounter-150715"] = [[Emperadores Gemelos]]
        L["Encounter-150716"] = [[Ouro]]
        L["Encounter-150717"] = [[C'Thun]]
    end
elseif locale == "frFR" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "LFR"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Héroïque"
    L["DifficultyName-5"] = "Mythique"
    L["AllStars"] = "All Stars"
    L["Rank"] = "Rang"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Inconnu]]
    L["UnknownRealm"] = [[[%s] Le royaume '%s' (identifiant %d) n'est pas dans la base de données. Merci de contacter l'équipe de Warcraft Logs.]]
    L["CopyProfileURL"] = [[Copier l'URL WarcraftLogs]]
    L["Subscriber"] = [[Abonné]]
    L["ShiftToExpand"] = [[<Maj> pour déplier]]
    L["SubAddonMissing"] = [[[%s] La base de données pour '%s' (%s) est manquante. Peut-être que vous vous êtes connecté au jeu pendant que l'addon était pleine mise à jour. Vérifiez l'application du bureau pour voir si la mise à jour est terminée, puis faites un '/reload' pour réessayer.]]
    L["DBLoadError"] = [[[%s] Impossible de charger la base de données de '%s'. Raison : %s]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Cliquez pour ouvrir les Paramètres]]
    L["ShowTooltipInCombat"] = [[Afficher l'Infobulle en Combat]]
    L["ShowTooltipInCombatDescription"] = [[Choisir si l'infobulle doit également être affichée en combat. Désactivé par défaut pour des raisons de performance.]]
    L["AllowShiftExpansionInCombat"] = [[Autoriser l'extension avec Shift en combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Choisir si les données étendues doivent également être affichées en combat. Active le paramètre ci-dessus.]]
    L["ShowRank"] = [[Afficher le rang]]
    L["ShowRankDescription"] = [[Active/Désactive l'ajout du rang à l'infobulle.]]
    L["ShowAsp"] = [[Montrer les All Stars]]
    L["ShowAspDescription"] = [[Active/Désactive l'ajout des points All Stars à l'infobulle.]]
    L["ShowShiftHint"] = [[Afficher l'astuce avec Shift]]
    L["ShowShiftHintDescription"] = [[Active/Désactive l'ajout de l'astuce pour étendre l'info en maintenant Shift.]]
    L["MenuIntegration"] = [[Étendre les options du menu]]
    L["MenuIntegrationDescription"] = [[Choisir si les menus doivent être étendus avec l'option de copier l'URL de profil du personnage.]]
    L["SettingsLookupUsage"] = [[Utilisation: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[Aucune donnée trouvée.]]
    L["SettingsLookupDataFor"] = [[%s pour %s - %s]]
    L["SettingsAvailableCommands"] = [[Commandes disponibles : ]]
    L["SettingsOpenSettingsLabel"] = [[ouvre les paramètres]]
    L["SettingsLookupLabel"] = [[rechercher un profil par nom  et royaume]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Les parses seront affichés après 20H ou 5M boss tués"
        L["Encounter-3009"] = [[Vexie et les Écrouabouilles]]
        L["Encounter-3010"] = [[Chaudron du carnage]]
        L["Encounter-3011"] = [[Rik Rebond]]
        L["Encounter-3012"] = [[Stix Jettetout]]
        L["Encounter-3013"] = [[Pignonneur Crosseplatine]]
        L["Encounter-3014"] = [[Bandit manchot]]
        L["Encounter-3015"] = [[Verr’Minh, chefs de la sécurité]]
        L["Encounter-3016"] = [[Roi du chrome Gallywix]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 15H kills"
        L["Encounter-1395"] = [[La garde de pierre]]
        L["Encounter-1390"] = [[Feng le Maudit]]
        L["Encounter-1434"] = [[Gara’jal le Lieur d’esprit]]
        L["Encounter-1436"] = [[Les esprits-rois]]
        L["Encounter-1500"] = [[Elegon]]
        L["Encounter-1407"] = [[Volonté de l’empereur]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[Seigneur Gargamoelle]]
        L["Encounter-50846"] = [[Dame Murmemort]]
        L["Encounter-50847"] = [[Bataille des canonnières de la Couronne de glace]]
        L["Encounter-50848"] = [[Porte-mort Saurcroc]]
        L["Encounter-50849"] = [[Pulentraille]]
        L["Encounter-50850"] = [[Trognepus]]
        L["Encounter-50851"] = [[Professeur Putricide]]
        L["Encounter-50852"] = [[Conseil de sang]]
        L["Encounter-50853"] = [[Reine Lana’thel]]
        L["Encounter-50854"] = [[Valithria Marcherêve]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[Roi-liche]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Maçon]]
        L["Encounter-3196"] = [[Belluaire]]
        L["Encounter-3188"] = [[Le conseil ressuscité]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-150709"] = [[Le prophète Skeram]]
        L["Encounter-150710"] = [[Famille royale silithide]]
        L["Encounter-150711"] = [[Garde de guerre Sartura]]
        L["Encounter-150712"] = [[Fankriss l'Inflexible]]
        L["Encounter-150713"] = [[Viscidus]]
        L["Encounter-150714"] = [[Princesse Huhuran]]
        L["Encounter-150715"] = [[Empereurs jumeaux]]
        L["Encounter-150716"] = [[Ouro]]
        L["Encounter-150717"] = [[C’Thun]]
    end
elseif locale == "itIT" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "LFR"
    L["DifficultyName-3"] = "Normale"
    L["DifficultyName-4"] = "Eroico"
    L["DifficultyName-5"] = "Mitico"
    L["AllStars"] = "Classificazione All-Stars"
    L["Rank"] = "Rango"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unknown]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Subscriber]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3009"] = [[Vexie e i Pestaruote]]
        L["Encounter-3010"] = [[Calderone del Massacro]]
        L["Encounter-3011"] = [[Rik Riverbero]]
        L["Encounter-3012"] = [[Stix Tritabrande]]
        L["Encounter-3013"] = [[Ingraniere Lockenstock]]
        L["Encounter-3014"] = [[Bandito con un Braccio Solo]]
        L["Encounter-3015"] = [[Mug'zee, Capi della Sicurezza]]
        L["Encounter-3016"] = [[Re Cromato Gallywix]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 15H kills"
        L["Encounter-1395"] = [[Guardia di Pietra]]
        L["Encounter-1390"] = [[Feng il Maledetto]]
        L["Encounter-1434"] = [[Gara'jal il Vincolaspiriti]]
        L["Encounter-1436"] = [[Reggenti Spirituali]]
        L["Encounter-1500"] = [[Elegon]]
        L["Encounter-1407"] = [[Volontà dell'Imperatore]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[Lord Marrowgar]]
        L["Encounter-50846"] = [[Lady Deathwhisper]]
        L["Encounter-50847"] = [[Icecrown Gunship Battle]]
        L["Encounter-50848"] = [[Deathbringer Saurfang]]
        L["Encounter-50849"] = [[Festergut]]
        L["Encounter-50850"] = [[Rotface]]
        L["Encounter-50851"] = [[Professor Putricide]]
        L["Encounter-50852"] = [[Blood Council]]
        L["Encounter-50853"] = [[Queen Lana'thel]]
        L["Encounter-50854"] = [[Valithria Dreamwalker]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[The Lich King]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Beastmaster]]
        L["Encounter-3188"] = [[Reborn Council]]
        L["Encounter-3190"] = [[Lillian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-150709"] = [[Profeta Skeram]]
        L["Encounter-150710"] = [[Reale Silitide]]
        L["Encounter-150711"] = [[Guardiana Sartura]]
        L["Encounter-150712"] = [[Fankriss l'Inflessibile]]
        L["Encounter-150713"] = [[Viscidus]]
        L["Encounter-150714"] = [[Principessa Huhuran]]
        L["Encounter-150715"] = [[Imperatori Gemelli]]
        L["Encounter-150716"] = [[Ouro]]
        L["Encounter-150717"] = [[C'thun]]
    end
elseif locale == "koKO" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "일반"
    L["Difficulty-4"] = "영웅"
    L["Difficulty-5"] = "신화"
    L["DifficultyName-1"] = "공격대 찾기"
    L["DifficultyName-3"] = "일반"
    L["DifficultyName-4"] = "영웅"
    L["DifficultyName-5"] = "신화"
    L["AllStars"] = "올스타"
    L["Rank"] = "등급"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unknown]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Subscriber]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3009"] = [[벡시와 연마공]]
        L["Encounter-3010"] = [[살육의 도가니]]
        L["Encounter-3011"] = [[리크 리버브]]
        L["Encounter-3012"] = [[스틱스 벙크정커]]
        L["Encounter-3013"] = [[스프로켓몽거 로켄스톡]]
        L["Encounter-3014"] = [[외팔이 좀도둑]]
        L["Encounter-3015"] = [[보안 책임자 머그지]]
        L["Encounter-3016"] = [[크롬왕 갤리윅스]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 15H kills"
        L["Encounter-1395"] = [[바위 수호자]]
        L["Encounter-1390"] = [[저주받은 펑]]
        L["Encounter-1434"] = [[영혼결속자 가라잘]]
        L["Encounter-1436"] = [[유령 왕]]
        L["Encounter-1500"] = [[엘레곤]]
        L["Encounter-1407"] = [[황제의 의지]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[군주 매로우가르]]
        L["Encounter-50846"] = [[여교주 데스위스퍼]]
        L["Encounter-50847"] = [[얼음왕관 비행포격선 전투]]
        L["Encounter-50848"] = [[죽음의 인도자 사울팽]]
        L["Encounter-50849"] = [[구린속]]
        L["Encounter-50850"] = [[썩은얼굴]]
        L["Encounter-50851"] = [[교수 퓨트리사이드]]
        L["Encounter-50852"] = [[피의 의회]]
        L["Encounter-50853"] = [[여왕 라나텔]]
        L["Encounter-50854"] = [[발리스리아 드림워커]]
        L["Encounter-50855"] = [[신드라고사]]
        L["Encounter-50856"] = [[리치 왕]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[발나자르]]
        L["Encounter-3187"] = [[베아트릭스]]
        L["Encounter-3186"] = [[솔리스트라자]]
        L["Encounter-3197"] = [[석공]]
        L["Encounter-3196"] = [[야수조련사]]
        L["Encounter-3188"] = [[부활의 의회]]
        L["Encounter-3190"] = [[릴리안 보스]]
        L["Encounter-3189"] = [[칼도란]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-150709"] = [[예언자 스케람]]
        L["Encounter-150710"] = [[실리시드 왕실]]
        L["Encounter-150711"] = [[전투감시병 살투라]]
        L["Encounter-150712"] = [[불굴의 판크리스]]
        L["Encounter-150713"] = [[비시두스]]
        L["Encounter-150714"] = [[공주 후후란]]
        L["Encounter-150715"] = [[쌍둥이 제왕]]
        L["Encounter-150716"] = [[아우로]]
        L["Encounter-150717"] = [[크툰]]
    end
elseif locale == "ptBR" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "D"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "PPR"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroico"
    L["DifficultyName-5"] = "Mítico"
    L["AllStars"] = "Maiores Estrelas"
    L["Rank"] = "Ranque"
    L["Kills"] = "Abates"
    L["Unknown"] = [[Desconhecido]]
    L["UnknownRealm"] = [[[%s] Domínio '%s' (id %d) não está no banco de dados. Por favor, reporte-se à equipe do Warcraft Logs.]]
    L["CopyProfileURL"] = [[Copiar URL do WCL]]
    L["Subscriber"] = [[Assinante]]
    L["ShiftToExpand"] = [[<Shift> para expandir]]
    L["SubAddonMissing"] = [[[%s] Base de dados para '%s' (%s) está ausente. Pode ser que você tenha entrado no jogo enquanto o 'addon' estava no meio de uma atualização. Verifique o aplicativo no 'desktop' para ver se a atualização foi concluída, e então execute '/reload' para tentar novamente.]]
    L["DBLoadError"] = [[[%s] Não foi possível carregar a base de dados '%s'. Motivo: %s]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Clique para abrir as Configurações]]
    L["ShowTooltipInCombat"] = [[Mostrar Dicas de Ferramenta durante o combate]]
    L["ShowTooltipInCombatDescription"] = [[Escolha de ampliar as dicas de ferramenta também durante o combate. Desativado por padrão como medida de desempenho.]]
    L["AllowShiftExpansionInCombat"] = [[Permitir expansão de Shift durante o combate]]
    L["AllowShiftExpansionInCombatDescription"] = [[Escolha de processar os dados ampliados também durante o combate. Habilita a opção acima.]]
    L["ShowRank"] = [[Mostrar Grau]]
    L["ShowRankDescription"] = [[Ativar/desativas mostrar o grau às dicas de ferramenta.]]
    L["ShowAsp"] = [[Mostrar All Stars]]
    L["ShowAspDescription"] = [[Ativar/desativar mostrar os Pontos All Star às dicas de ferramenta.]]
    L["ShowShiftHint"] = [[Mostrar Dica de Shift]]
    L["ShowShiftHintDescription"] = [[Ativar/desativar a dica para expandir informações enquanto pressionar a tecla Shift.]]
    L["MenuIntegration"] = [[Ampliar Opções de Menu]]
    L["MenuIntegrationDescription"] = [[Escolha de ampliar os menus com uma opção de copiar a URL do perfil de um personagem.]]
    L["SettingsLookupUsage"] = [[Uso: /%s procurar <name> <realm>]]
    L["SettingsLookupNoData"] = [[Nenhum dado encontrado.]]
    L["SettingsLookupDataFor"] = [[%s para %s - %s]]
    L["SettingsAvailableCommands"] = [[Comandos disponíveis:]]
    L["SettingsOpenSettingsLabel"] = [[abre as configurações]]
    L["SettingsLookupLabel"] = [[procurar um perfil por nome e reino]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Análises apresentadas após 20H ou 5M mortes"
        L["Encounter-3009"] = [[Vexie e os Trincatracas]]
        L["Encounter-3010"] = [[Caldeirão da Carnificina]]
        L["Encounter-3011"] = [[Rik Reverb]]
        L["Encounter-3012"] = [[Stix Sucateiro]]
        L["Encounter-3013"] = [[Rebimbocador Travaguarda]]
        L["Encounter-3014"] = [[Bandido de Um Braço]]
        L["Encounter-3015"] = [[Mag'Guila, Chefes de Segurança]]
        L["Encounter-3016"] = [[Rei do Cromo Gallywix]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 15H kills"
        L["Encounter-1395"] = [[Sentinela Pétrea]]
        L["Encounter-1390"] = [[Feng, o Amaldiçoado]]
        L["Encounter-1434"] = [[Gara'jal, o Atador de Almas]]
        L["Encounter-1436"] = [[Espectros dos Reis]]
        L["Encounter-1500"] = [[Elegon]]
        L["Encounter-1407"] = [[Vontade do Imperador]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[Lorde Medulante]]
        L["Encounter-50846"] = [[Lady Sibilamorte]]
        L["Encounter-50847"] = [[Batalha da Belonave da Coroa de Gelo]]
        L["Encounter-50848"] = [[Carrasco Saurfang]]
        L["Encounter-50849"] = [[Tripapútrida]]
        L["Encounter-50850"] = [[Rostorroto]]
        L["Encounter-50851"] = [[Professor Putricida]]
        L["Encounter-50852"] = [[Concílio de Sangue]]
        L["Encounter-50853"] = [[Rainha Lana'thel]]
        L["Encounter-50854"] = [[Valithria Andassonho]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[O Lich Rei]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Alvano]]
        L["Encounter-3196"] = [[Senhor das Feras]]
        L["Encounter-3188"] = [[Conselho Renascido]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-150709"] = [[Profeta Skeram]]
        L["Encounter-150710"] = [[Realeza Silítidea]]
        L["Encounter-150711"] = [[Guarda de Batalha Sartura]]
        L["Encounter-150712"] = [[Fankriss, o Obstinado]]
        L["Encounter-150713"] = [[Viscidus]]
        L["Encounter-150714"] = [[Princesa Huhuran]]
        L["Encounter-150715"] = [[Imperadores Gêmeos]]
        L["Encounter-150716"] = [[Ouroboros]]
        L["Encounter-150717"] = [[C'Thun]]
    end
elseif locale == "ruRU" then
    L["Difficulty-1"] = "ПР"
    L["Difficulty-3"] = "Н"
    L["Difficulty-4"] = "Г"
    L["Difficulty-5"] = "Э"
    L["DifficultyName-1"] = "СПР"
    L["DifficultyName-3"] = "Обычный"
    L["DifficultyName-4"] = "Героический"
    L["DifficultyName-5"] = "Эпохальный"
    L["AllStars"] = "Все звезды"
    L["Rank"] = "Ранг"
    L["Kills"] = "Убийств"
    L["Unknown"] = [[Неизвестно]]
    L["UnknownRealm"] = [[[%s] Реалм '%s' (id %d) отсутствует в базе данных. Пожалуйста, сообщите об этом команде Warcraft Logs.]]
    L["CopyProfileURL"] = [[Скопировать WCL URL]]
    L["Subscriber"] = [[Подписчик]]
    L["ShiftToExpand"] = [[<Shift> чтобы расширить]]
    L["SubAddonMissing"] = [[[%s] База данных для '%s' (%s) отсутствует. Возможно, вы вошли в игру, когда аддон находился в процессе обновления. Проверьте в настольном приложении, завершилось ли обновление, а затем выполните команду '/reload', чтобы повторить попытку.]]
    L["DBLoadError"] = [[[%s] Не удалось загрузить базу данных для '%s'. Причина: %s]]
    L["Main"] = [[Главная]]
    L["ClickToOpenSettings"] = [[Нажмите, чтобы открыть Настройки]]
    L["ShowTooltipInCombat"] = [[Показывать тултип в бою]]
    L["ShowTooltipInCombatDescription"] = [[Нужно ли расширять всплывающую подсказку и в бою. По умолчанию отключено в качестве меры производительности.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Нужно ли отображать расширенные данные и в бою. Включает настройку выше.]]
    L["ShowRank"] = [[Показать ранг]]
    L["ShowRankDescription"] = [[Переключает добавление ранга во всплывающую подсказку.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Переключает добавление подсказки для раскрытия информации при удержании Shift.]]
    L["MenuIntegration"] = [[Расширение опций меню]]
    L["MenuIntegrationDescription"] = [[Нужно ли расширять меню опцией копирования URL-адреса профиля персонажа.]]
    L["SettingsLookupUsage"] = [[Использование: /%s lookup <имя> <реалм>]]
    L["SettingsLookupNoData"] = [[Данные не найдены.]]
    L["SettingsLookupDataFor"] = [[%s для %s - %s]]
    L["SettingsAvailableCommands"] = [[Доступные команды:]]
    L["SettingsOpenSettingsLabel"] = [[открывает настройки]]
    L["SettingsLookupLabel"] = [[поиск профиля по имени и региону]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Парсы показываются после 20Г или 5M убийств"
        L["Encounter-3009"] = [[Векси и зуботочеры]]
        L["Encounter-3010"] = [[Котел смерти]]
        L["Encounter-3011"] = [[Рик Ревербер]]
        L["Encounter-3012"] = [[Стикс Бункохламзень]]
        L["Encounter-3013"] = [[Зубцеторг Всесхватс]]
        L["Encounter-3014"] = [[Однорукий бандит]]
        L["Encounter-3015"] = [[Граб'Зи, главы отдела охраны]]
        L["Encounter-3016"] = [[Хромовый король Галливикс]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 15H kills"
        L["Encounter-1395"] = [[Каменные стражи]]
        L["Encounter-1390"] = [[Фэн Проклятый]]
        L["Encounter-1434"] = [[Душелов Гара'джал]]
        L["Encounter-1436"] = [[Призрачные короли]]
        L["Encounter-1500"] = [[Элегон]]
        L["Encounter-1407"] = [[Воля императора]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[Лорд Ребрад]]
        L["Encounter-50846"] = [[Леди Смертный Шепот]]
        L["Encounter-50847"] = [[Битва на кораблях в Ледяной Короне]]
        L["Encounter-50848"] = [[Саурфанг Смертоносный]]
        L["Encounter-50849"] = [[Тухлопуз]]
        L["Encounter-50850"] = [[Гниломорд]]
        L["Encounter-50851"] = [[Профессор Мерзоцид]]
        L["Encounter-50852"] = [[Кровавый Совет]]
        L["Encounter-50853"] = [[Королева Лана'тель]]
        L["Encounter-50854"] = [[Валитрия Сноходица]]
        L["Encounter-50855"] = [[Синдрагоса]]
        L["Encounter-50856"] = [[Король-лич]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Балназзар]]
        L["Encounter-3187"] = [[Беатриса]]
        L["Encounter-3186"] = [[Солистраза]]
        L["Encounter-3197"] = [[Мейсон]]
        L["Encounter-3196"] = [[Повелитель зверей]]
        L["Encounter-3188"] = [[Возрожденный совет]]
        L["Encounter-3190"] = [[Лилиан Восс]]
        L["Encounter-3189"] = [[Калдоран]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-150709"] = [[Пророк Скерам]]
        L["Encounter-150710"] = [[Царственность силитида]]
        L["Encounter-150711"] = [[Боевой страж Сартура]]
        L["Encounter-150712"] = [[Фанкрисс Непреклонный]]
        L["Encounter-150713"] = [[Нечистотон]]
        L["Encounter-150714"] = [[Принцесса Хухуран]]
        L["Encounter-150715"] = [[Императоры-близнецы]]
        L["Encounter-150716"] = [[Оуро]]
        L["Encounter-150717"] = [[К'Тун]]
    end
elseif locale == "zhCN" then
    L["Difficulty-1"] = "随机"
    L["Difficulty-3"] = "普通"
    L["Difficulty-4"] = "英雄"
    L["Difficulty-5"] = "史诗"
    L["DifficultyName-1"] = "团队查找器"
    L["DifficultyName-3"] = "普通"
    L["DifficultyName-4"] = "英雄级"
    L["DifficultyName-5"] = "史诗级"
    L["AllStars"] = "全明星分"
    L["Rank"] = "排名"
    L["Kills"] = "击杀"
    L["Unknown"] = [[未知]]
    L["UnknownRealm"] = [[[%s] 服务器 '%s' (id %d) 不在数据库中。请报告给WCL团队。]]
    L["CopyProfileURL"] = [[复制 WCL 链接]]
    L["Subscriber"] = [[WCL会员]]
    L["ShiftToExpand"] = [[按住 <Shift> 展开]]
    L["SubAddonMissing"] = [[[%s] '%s' (%s) 的数据库缺失。可能是因为您在插件更新过程中登录了游戏。请检查WCL客户端以确认更新是否已完成，然后运行 '/reload' 再次尝试。]]
    L["DBLoadError"] = [[[%s] 无法加载 '%s' 的数据库。原因：%s]]
    L["Main"] = [[大号]]
    L["ClickToOpenSettings"] = [[点击打开设置]]
    L["ShowTooltipInCombat"] = [[在战斗中显示插件]]
    L["ShowTooltipInCombatDescription"] = [[是否在战斗中也显示插件。默认禁用以提高性能。]]
    L["AllowShiftExpansionInCombat"] = [[允许在战斗中按 Shift 扩展]]
    L["AllowShiftExpansionInCombatDescription"] = [[是否在战斗中也渲染扩展数据。需要先启用上述设置]]
    L["ShowRank"] = [[显示排名]]
    L["ShowRankDescription"] = [[切换在工具提示中添加排名的选项。]]
    L["ShowAsp"] = [[显示全明星分]]
    L["ShowAspDescription"] = [[切换在工具提示中添加全明星积分的选项。]]
    L["ShowShiftHint"] = [[显示 Shift 提示]]
    L["ShowShiftHintDescription"] = [[切换在按住Shift键时附加提示以展开信息的选项。]]
    L["MenuIntegration"] = [[扩展菜单选项]]
    L["MenuIntegrationDescription"] = [[是否扩展菜单以添加复制角色信息链接的选项。]]
    L["SettingsLookupUsage"] = [[用法: /%s 查找 <名字> <服务器>]]
    L["SettingsLookupNoData"] = [[没有找到数据]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[可用命令：]]
    L["SettingsOpenSettingsLabel"] = [[打开设置]]
    L["SettingsLookupLabel"] = [[按角色名和服务器查找资料]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "分数在20次H或5次M击杀后显示"
        L["Encounter-3009"] = [[维克茜和磨轮]]
        L["Encounter-3010"] = [[血腥大熔炉]]
        L["Encounter-3011"] = [[里克·混响]]
        L["Encounter-3012"] = [[斯提克斯·堆渣]]
        L["Encounter-3013"] = [[链齿狂人洛肯斯多]]
        L["Encounter-3014"] = [[独臂盗匪]]
        L["Encounter-3015"] = [[穆格·兹伊，安保头子]]
        L["Encounter-3016"] = [[铬武大王加里维克斯]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 15H kills"
        L["Encounter-1395"] = [[石头守卫]]
        L["Encounter-1390"] = [[受诅者魔封]]
        L["Encounter-1434"] = [[缚灵者戈拉亚]]
        L["Encounter-1436"] = [[先王之魂]]
        L["Encounter-1500"] = [[伊拉贡]]
        L["Encounter-1407"] = [[皇帝的意志]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[玛洛加尔领主]]
        L["Encounter-50846"] = [[亡语者女士]]
        L["Encounter-50847"] = [[冰冠冰川炮舰战]]
        L["Encounter-50848"] = [[死亡使者萨鲁法尔]]
        L["Encounter-50849"] = [[烂肠]]
        L["Encounter-50850"] = [[腐面]]
        L["Encounter-50851"] = [[普崔塞德教授]]
        L["Encounter-50852"] = [[鲜血议会]]
        L["Encounter-50853"] = [[兰娜瑟尔女王]]
        L["Encounter-50854"] = [[踏梦者瓦莉瑟瑞娅]]
        L["Encounter-50855"] = [[辛达苟萨]]
        L["Encounter-50856"] = [[巫妖王]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[巴纳扎尔]]
        L["Encounter-3187"] = [[碧阿崔克丝]]
        L["Encounter-3186"] = [[瑟莉斯塔萨]]
        L["Encounter-3197"] = [[梅森]]
        L["Encounter-3196"] = [[兽王]]
        L["Encounter-3188"] = [[复生议会]]
        L["Encounter-3190"] = [[莉莉安·沃斯]]
        L["Encounter-3189"] = [[凯尔多兰]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-150709"] = [[预言者斯克拉姆]]
        L["Encounter-150710"] = [[安其拉三宝]]
        L["Encounter-150711"] = [[沙尔图拉]]
        L["Encounter-150712"] = [[顽强的范克瑞斯]]
        L["Encounter-150713"] = [[维希度斯]]
        L["Encounter-150714"] = [[哈霍兰公主]]
        L["Encounter-150715"] = [[双子皇帝]]
        L["Encounter-150716"] = [[奥罗]]
        L["Encounter-150717"] = [[克苏恩]]
    end
elseif locale == "zhTW" then
    L["Difficulty-1"] = "隨團"
    L["Difficulty-3"] = "普通"
    L["Difficulty-4"] = "英雄"
    L["Difficulty-5"] = "傳奇"
    L["DifficultyName-1"] = "隨機團隊"
    L["DifficultyName-3"] = "普通"
    L["DifficultyName-4"] = "英雄"
    L["DifficultyName-5"] = "傳奇"
    L["AllStars"] = "全明星"
    L["Rank"] = "階級"
    L["Kills"] = "Kills"
    L["Unknown"] = [[未知]]
    L["UnknownRealm"] = [[[%s] 伺服器『%s』(ID %d) 不存在於資料庫，請向戰鬥紀錄團隊回報]]
    L["CopyProfileURL"] = [[複製WCL網址]]
    L["Subscriber"] = [[訂閱者]]
    L["ShiftToExpand"] = [[按住 <Shift> 展開]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "戰績解鎖條件：累積20小時或500萬擊殺"
        L["Encounter-3009"] = [[Vexie and the Geargrinders]]
        L["Encounter-3010"] = [[Cauldron of Carnage]]
        L["Encounter-3011"] = [[Rik Reverb]]
        L["Encounter-3012"] = [[Stix Bunkjunker]]
        L["Encounter-3013"] = [[Sprocketmonger Lockenstock]]
        L["Encounter-3014"] = [[One-Armed Bandit]]
        L["Encounter-3015"] = [[Mug'Zee, Heads of Security]]
        L["Encounter-3016"] = [[Chrome King Gallywix]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 15H kills"
        L["Encounter-1395"] = [[The Stone Guard]]
        L["Encounter-1390"] = [[Feng the Accursed]]
        L["Encounter-1434"] = [[Gara'jal the Spiritbinder]]
        L["Encounter-1436"] = [[The Spirit Kings]]
        L["Encounter-1500"] = [[Elegon]]
        L["Encounter-1407"] = [[Will of the Emperor]]
    elseif Private.IsWrath then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-50845"] = [[Lord Marrowgar]]
        L["Encounter-50846"] = [[Lady Deathwhisper]]
        L["Encounter-50847"] = [[Icecrown Gunship Battle]]
        L["Encounter-50848"] = [[Deathbringer Saurfang]]
        L["Encounter-50849"] = [[Festergut]]
        L["Encounter-50850"] = [[Rotface]]
        L["Encounter-50851"] = [[Professor Putricide]]
        L["Encounter-50852"] = [[Blood Council]]
        L["Encounter-50853"] = [[Queen Lana'thel]]
        L["Encounter-50854"] = [[Valithria Dreamwalker]]
        L["Encounter-50855"] = [[Sindragosa]]
        L["Encounter-50856"] = [[The Lich King]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Beastmaster]]
        L["Encounter-3188"] = [[Reborn Council]]
        L["Encounter-3190"] = [[Lillian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-150709"] = [[The Prophet Skeram]]
        L["Encounter-150710"] = [[Silithid Royalty]]
        L["Encounter-150711"] = [[Battleguard Sartura]]
        L["Encounter-150712"] = [[Fankriss the Unyielding]]
        L["Encounter-150713"] = [[Viscidus]]
        L["Encounter-150714"] = [[Princess Huhuran]]
        L["Encounter-150715"] = [[Twin Emperors]]
        L["Encounter-150716"] = [[Ouro]]
        L["Encounter-150717"] = [[C'Thun]]
    end
end
