Merfin = Merfin or {}
Merfin.Localizations = Merfin.Localizations or {}

Merfin.Localizations.deDE = {

  ["Mark"] = "Mal", -- Druid Mark
  ["AP"] = "Angriffskraft",
  ["MP5"] = "MP5",
  ["Haste"] = "Tempo",
  ["Swap"] = "Rüstungswechsel",
  ["%s is outdated. Update to version %s+."] = "%s ist veraltet. Bitte auf Version %s+ aktualisieren.",
  ["%s is not loaded. Install version %s or later."] = "%s ist nicht geladen. Installiere Version %s oder neuer.",
  ["Issues detected:"] = "Probleme erkannt:",
  ["Take %s"] = "%s nehmen",
  ["Eat %s"] = "%s essen",
  ["%s is up"] = "%s ist aktiv",
  ["Assist with Summon"] = "Beim Beschwören helfen",
  ["Ardent Procced"] = "Unbeugsamkeit ausgelöst",
  ["Seal"] = "Siegel",
  ["Aura"] = "Aura",
  ["Pet Food"] = "Begleiterbuff",
  ["%s asks for |cff40ff40[%s]|r %s"] = "%s bittet um |cff40ff40[%s]|r %s",
  ["Pull Timer by %s"] = "Pull-Timer von %s",
  ["Break Timer by %s"] = "Pause-Timer von %s",
  ["» %s « is being resurrected"] = "» %s « wird wiederbelebt",
  ["Scroll Page"] = "Aktionsseite wechseln",
  ["Drain Soul Phase"] = "Seelenentzug-Phase",
  ["Hold Ctrl for Release"] = "Strg halten zum Freilassen",
  ["Use %s on me, please!"] = "Bitte %s auf mich benutzen!",

  -- Dummy Auras
  ["BIG BANG"] = "BIG BANG",
  ["BIG BANG INC."] = "BIG BANG kommt!",
  ["DEPORTATION ON %s"] = "Verbannung auf %s",
  ["%s Huge Tariffs » %s %s"] = "%s Hohe Abgaben » %s %s",
  ["Dummy Bar"] = "Testleiste",
  ["Regular Cooldown Bar"] = "Standard-Cooldownleiste",
  ["Special #1 Cooldown Bar"] = "Spezial-Cooldownleiste #1",
  ["Special #2 Cooldown Bar"] = "Spezial-Cooldownleiste #2",
  ["Special #3 Cooldown Bar"] = "Spezial-Cooldownleiste #3",
  ["Special #4 Cooldown Bar"] = "Spezial-Cooldownleiste #4",
  ["Emphasized Cooldown Bar"] = "Hervorgehobene Cooldownleiste",
  ["Ready"] = "Bereit",
  ["Pre-warning"] = "Vorwarnung",

  -- Default replicas
  ["%s soon"] = "%s bald",
  ["GTFO"] = "@cffff8b17RAUS DA@r [%s]",
  ["GTFO |cffff4040[%s]|r"] = "|cffff4040RAUS|r [%s]",
  ["%s Removed"] = "%s entfernt",

  -- Flow / Timing
  ["AOE Soon"] = "AOE bald",
  ["Adds Incoming"] = "Adds inc",
  ["Boss Arrival"] = "Boss erscheint",
  ["Flight"] = "Flug",
  ["INC."] = "Kommt!",
  ["Phase"] = "Phase",
  ["Phase 1"] = "Phase 1",
  ["Phase 2"] = "Phase 2",
  ["Phase 3"] = "Phase 3",
  ["Phase 4"] = "Phase 4",
  ["Platform"] = "Plattform",
  ["Platform 2"] = "Plattform 2",
  ["Platform 3"] = "Plattform 3",
  ["Debuffs Soon"] = "Debuffs bald",

  -- Movement
  ["Behind"] = "Hinten",
  ["Dodge"] = "Ausweichen",
  ["Dodge to Left"] = "Links ausweichen",
  ["Dodge to Right"] = "Rechts ausweichen",
  ["Forward"] = "Vor",
  ["Frontal"] = "Frontal",
  ["Hide"] = "Verstecken",
  ["Inside"] = "Rein",
  ["Left"] = "Links",
  ["Move"] = "Bewegen",
  ["Move Out"] = "Raus",
  ["Out"] = "Raus",
  ["Right"] = "Rechts",
  ["Back"] = "Zurück",
  ["Spread Out"] = "Spreaden",
  ["Stack"] = "Stacken",
  ["Stack On Me"] = "Auf mir stacken",
  ["Stay Away"] = "Weg von der Gruppe",
  ["Prepare to Dodge"] = "Bereit zum Ausweichen",

  -- Actions
  ["Auto-Attack"] = "Autoangriff",
  ["Be Aware"] = "Achtung",
  ["Focus Target"] = "Fokusziel",
  ["Interrupt Now"] = "Interrupt jetzt!",
  ["Prepare to stack"] = "Bereit zum Stacken",
  ["Soak the Cast"] = "Soaken!",
  ["Stop Attack"] = "Stop DPS",
  ["Stop Attack Soon"] = "Gleich Stop DPS",
  ["Swap In"] = "Rein wechseln",
  ["Swap Out"] = "Raus wechseln",
  ["Switch Target"] = "Ziel wechseln",
  ["Switch Targets"] = "Ziele wechseln",
  ["Take the Add"] = "Add übernehmen",
  ["Target"] = "Ziel",
  ["You are next"] = "Du bist als Nächstes dran",
  ["Put Pet on %s Passive"] = "Begleiter auf %s passiv setzen",
  ["Burst the boss"] = "Burst auf Boss",

  -- Player Status (Debuffs)
  ["DoT"] = "DoT",
  ["Feared"] = "Gefürchtet",
  ["Fixated"] = "Fixiert",
  ["Silenced"] = "Zum Schweigen gebracht",
  ["Stunned"] = "Betäubt",
  ["Targetted"] = "Anvisiert",
  ["Trapped"] = "Gefangen",

  -- Buffs / Utility
  ["Mana Regen"] = "Manareg",
  ["Move Speed"] = "Bewegungstempo",
  ["Protected"] = "Geschützt",
  ["Reflect"] = "Reflektieren",

  -- Damage / Healing / Output
  ["AOE"] = "AOE",
  ["Boss Dmg"] = "Boss-Schaden",
  ["Damage"] = "Schaden",
  ["Damage Done"] = "Schadensoutput",
  ["Dmg Done"] = "Dmg",
  ["Dmg Tkn"] = "Erlittener Schaden",
  ["Dmg/Heal"] = "Schaden/Heilung",
  ["Heal Tkn"] = "Erhaltene Heilung",
  ["Heal to Full"] = "Voll heilen",
  ["Healing Done"] = "Heilung",

  -- Entities
  ["Add"] = "Add",
  ["Adds"] = "Adds",
  ["Entrance"] = "Eingang",

  -- MSV: Trash
  ["Doors will be broken down"] = "Türen werden aufgebrochen",
  ["Frontal & Knockback"] = "Frontal + Rückstoß",
  ["Mobs active - East |cffffff80(1/4)|r"] = "Mobs aktiv – Osten |cffffff80(1/4)|r",
  ["Mobs active - North |cffffff80(3/4)|r"] = "Mobs aktiv – Norden |cffffff80(3/4)|r",
  ["Mobs active - South |cffffff80(4/4)|r"] = "Mobs aktiv – Süden |cffffff80(4/4)|r",
  ["Mobs active - West |cffffff80(2/4)|r"] = "Mobs aktiv – Westen |cffffff80(2/4)|r",

  -- MSV: The Stone Guard
  ["Amethyst"] = "Amethyst",
  ["Cobalt"] = "Kobalt",
  ["Jade"] = "Jade",
  ["Jasper"] = "Jaspis",
  ["Linked with %s"] = "Verbunden mit %s",
  ["Neutralize Traps"] = "Fallen entschärfen",
  ["Overload Soon"] = "Overload bald",
  ["Painters Leaderboard"] = "Steinmaler-Rangliste",
  ["SNAP"] = "REISS AB",
  ["Snap the chains"] = "Ketten zerreißen",

  -- MSV: Feng
  ["Arcane Phase"] = "Arkanphase (Stab)",
  ["Barrier"] = "Barriere",
  ["DEBUFFS INC."] = "Debuffs inc!",
  ["Flame Phase"] = "Flammenphase (Faust)",
  ["Lightning Phase"] = "Blitzphase (Speer)",
  ["Shadow Phase"] = "Schattenphase (Schild)",
  ["Shroud"] = "Schleier",

  -- MSV: Gara\'jal
  ["Shadowy Attack"] = "Schattenschlag",
  ["Adds Count"] = "Add-Zähler",
  ["Kill Severers"] = "Seelenreißer töten",
  ["Shared Damage"] = "Geteilter Schaden",
  ["Stats"] = "Stats",

  -- MSV: The Spirit Kings
  ["Kite Skull"] = "Totem kiten",
  ["Pinned"] = "Festgenagelt",

  -- Elegon
  ["Cant Soak"] = "Kann nicht soaken",
  ["Focus Charges"] = "Kugeln fokussen",
  ["Falling Floor"] = "Boden fällt ein",
  ["Gossip Available"] = "Dialog verfügbar",
  ["YOURE NEXT TO SOAK"] = "Du bist als Nächstes zum Soaken dran",

  -- Will of Emperor
  ["Prepare to Root"] = "Bereit zum Wurzeln",
  ["Building Up"] = "Energie lädt auf",
  ["Courage"] = "Mut",
  ["Dodge Combo"] = "Tanzphase",
  ["Jan-xi"] = "Jan-xi",
  ["Qin-xi"] = "Qin-xi",
  ["Rage"] = "Raserei",
  ["Strength"] = "Stärke",
  ["Bonus Attack"] = "Bonusangriff",

  -- HoF: Trash
  ["Extended CDs"] = "Verlängerte CDs",

  -- HoF: Zor'lok
  ["Echo"] = "Echo",
  ["Melee Boss"] = "Melee-Boss",
  ["Mind Control"] = "Mind Control",
  ["Mind Control Soon"] = "MC bald",
  ["Prepare to hide"] = "Bereit zum Verstecken",
  ["Sonic Rings Soon"] = "Schallringe bald",

  -- HoF: Tayak
  ["Gone with the Wind"] = "Sturm hebt dich hoch",

  -- HoF: Garalon
  ["Catch Pheromones"] = "Pheromone übernehmen",

  -- HoF: Mel\'jarak
  ["Adds Respawn Soon"] = "Adds respawnen bald",
  ["Cant Hit Prisons"] = "Gefängnisse unverwundbar",
  ["Dodge Blade"] = "Klinge ausweichen",
  ["Right Click Me"] = "Rechtsklick auf mich",

  -- HoF: Unsok
  ["Cross Globules"] = "Kugeln kreuzen",
  ["Press %d"] = "%d drücken",
  ["Player Explosion"] = "Spielerexplosion",

  -- HoF: Shekzeer
  ["Buff Players"] = "Spieler buffen",
  ["Come Get The Buff"] = "Buff abholen",
  ["Combine Resins"] = "Harz zusammenführen",
  ["Explosion Soon"] = "Explosion bald",
  ["Get Buff On Tank"] = "Buff beim Tank holen",
  ["Fears Soon"] = "Furcht bald",

  -- ToES: Protectors
  ["Your Group: Swap in"] = "Deine Gruppe: rein wechseln",
  ["Your Group: Swap Out"] = "Deine Gruppe: raus wechseln",

  -- ToES: Tsulong
  ["YOURE NEXT TO TAKE |cffffff40LIGHT|r"] = "Du bist als Nächstes dran, das |cffffff40Licht|r zu nehmen",
  ["Drop Stacks"] = "Stacks resetten",

  -- ToES: Lei Shi
  ["Special Ability"] = "Spezialfähigkeit",

  -- ToES: Sha of Fear
  ["Forms a Wall"] = "Lichtwand formt sich",
  ["Left Platform"] = "Linke Plattform",
  ["Middle Platform"] = "Mittlere Plattform",
  ["Move to %d"] = "Zu %d bewegen",
  ["Right Platform"] = "Rechte Plattform",
  ["Start in %d"] = "Start bei %d",
  ["Random Ability (1 of 3)"] = "Zufallsfähigkeit (1 von 3)",

  ---------------------------
  -- Throne of Thunder T15 --
  ---------------------------

  ["Comet Soon"] = "Komet bald",
  ["Red Add killed"] = "Rotes Add getötet",
  ["Drop Pool"] = "Pool ablegen",
  ["Get to Safe Range"] = "In sichere Range gehen",
  ["Dont Kill Orbs"] = "Keine Orbs töten",
  ["Arrival"] = "Ankunft",
  ["Unlocked"] = "Freigeschaltet",
  ["IMMUNED"] = "Immun",
  ["Celestial"] = "Himmlisch",
  ["Slows boss abilities"] = "Verlangsamt Bossfähigkeiten",
  ["Health / Mana Regen"] = "Leben/Mana-Regeneration",
  ["+50% HP"] = "+50% HP",
  ["Cranes Damage"] = "Kranichschaden",
  ["Taunt Big Add"] = "Großes Add spotten",
  ["AoE Dmg"] = "AOE-Schaden",
  ["Use Defensives"] = "Defensives benutzen",
  ["Breaths"] = "Atem",
  ["hold debuff"] = "Debuff halten",
  ["pass now"] = "Jetzt weitergeben",
  ["Tank Switch"] = "Tankwechsel",
  ["Tank Switch Soon"] = "Tankwechsel bald",
  ["Safe to Stack"] = "Sicher zum Stacken",
  ["Raid Damage"] = "Raid-Schaden",
  ["Order Reset"] = "Reihenfolge reset",
  ["Taunt Boss"] = "Boss spotten",
  ["Stack with me"] = "Bei mir stacken",
  ["Spread"] = "Spreaden",
  ["Big Add"] = "Großes Add",
  ["You Assigned"] = "Du bist dran",
  ["Beams Phase"] = "Strahlenphase",
  ["Dodge Spear"] = "Speer ausweichen",
  ["Watch Winds"] = "Auf Wind achten",
  ["Focus Adds"] = "Adds fokussen",
  ["Knockback"] = "Rückstoß",
  ["COME CLOSER"] = "NÄHER KOMMEN",
  ["Interrupting Cast"] = "Unterbrechung nötig",
  ["Interrupt Soon"] = "Interrupt bald",
  ["Windstorm"] = "Windsturm",
  ["Throw Turtle"] = "Schildkröte werfen",
  ["STOP CAST IN"] = "CAST STOPPEN IN",
  ["Fixate"] = "Fixierung",
  ["Control Orb"] = "Orb kontrollieren",
  ["Right Click Orb"] = "Rechtsklick auf Orb",
  ["Bell Destroyed"] = "Glocke zerstört",
  ["Kite Torrent"] = "Torrent kiten",
  ["+Dmg"] = "+Schaden",
  ["STOP CASTING"] = "STOPP CAST",
  ["Charge Soon"] = "Ansturm bald",
  ["KILL |cffffff80[AMBER FOG]|r ASSAP"] = "|cffffff80Bernnebel|r SO SCHNELL WIE MÖGLICH TÖTEN",
  ["Dodge Particles"] = "Partikeln ausweichen",
  ["MOVE BOSS FROM |cffff4040%s|r"] = "Boss weg von |cffff4040%s|r bewegen",
  ["Blue Beam On You"] = "Blauer Strahl auf dir",
  ["Yellow Beam on you"] = "Gelber Strahl auf dir",
  ["Red Beam On You"] = "Roter Strahl auf dir",
  ["New Waters"] = "Neues Wasser",
  ["Upper"] = "Oben",
  ["Lower"] = "Unten",
  ["Turtle Throw"] = "Schildkrötenwurf",
  ["Breath soon"] = "Atem bald",
  ["Soak Buff on the |cff3fc7ebPlatform|r"] = "Buff auf der |cff3fc7ebPlattform|r soaken",
  ["Soak Buff on the |cffff4040Nest|r"] = "Buff im |cffff4040Nest|r soaken",
  ["Soak buff on the Nest"] = "Im Nest soaken",
  ["Soak buff on the Platform"] = "Auf der Plattform soaken",
  ["ICE WALL IN"] = "EISWAND IN",
  ["Immune Soon"] = "Immun bald",
  ["Prepare to Stack"] = "Bereit zum Stacken",
  ["Next Flock"] = "Nächster Schwarm",
  ["Casting Breath"] = "Wirkt Atem",
  ["Stun the Add"] = "Add stunnen",
  ["Worms"] = "Würmer",
  ["Hide Behind Comet"] = "Hinter dem Kometen verstecken",
  ["Stay Still"] = "Nicht bewegen",
  ["Corrupted Balls"] = "Verderbte Kugeln",
  ["Use Movements"] = "Bewegungsfähigkeiten nutzen",
  ["New Add"] = "Neues Add",
  ["Stop Soak"] = "Soaken stoppen",
  ["%d yards"] = "%d Meter",
  ["-haste"] = "-Tempo",
  ["+ Attack and CD"] = "+ Angriff & CD",
  ["Feather"] = "Feder",
  ["MOVE ON {rt6} |cff40c7ebSQUARE|r"] = "Zu {rt6} |cff40c7ebQuadrat|r bewegen",
  ["MOVE ON {rt4} |cff00ff00TRIANGLE|r"] = "Zu {rt4} |cff00ff00Dreieck|r bewegen",
  ["Move to Square"] = "Zum Quadrat bewegen",
  ["Move to Triangle"] = "Zum Dreieck bewegen",
  ["KEEP |cffff4040%s|r AWAY!"] = "|cffff4040%s|r FERNHALTEN!",
  ["Balls"] = "Kugeln",
  ["Balls Soon"] = "Kugeln bald",
  ["Death Beam Spawn"] = "Todesstrahl erscheint",
  ["Death Beam"] = "Todesstrahl",
  ["New Adds"] = "Neue Adds",
  ["Dont Move"] = "Nicht bewegen",
  ["Jolt Obtained"] = "Schock erhalten",
  ["DONT MOVE TIL |cffff4040ADD|r IS DEAD"] = "NICHT BEWEGEN BIS |cffff4040ADD|r TOT IST",
  ["STOP MOVING"] = "SOFORT STILLSTEHEN",
  ["Death Ray"] = "Todeslaser",
  ["Stay Alone"] = "Allein stehen",
  ["Click"] = "Klicken",
  ["Head |cFF33AAFFup|r to %s"] = "Geh |cFF33AAFFhoch|r zu %s",
  ["Head |cFFFFAA33down|r to %s"] = "Geh |cFFFFAA33runter|r zu %s",
  ["M"] = "M",
  ["Head up to the |cFF33FF66middle|r"] = "Zur |cFF33FF66Mitte|r gehen",
  ["Dinomancer"] = "Dinomant",
  ["Dinomancer Incoming"] = "Dinomant kommt",
  ["Take Spot"] = "Position übernehmen",
  ["Raid Damage Soon"] = "Raid-Schaden bald",
  ["dmg tkn"] = "erlittener Schaden",
  ["Zapped"] = "Elektroschock",
  ["Right Click!"] = "Rechtsklick!",
  ["TANK THROW"] = "TANKWURF",
  ["Tank Throw Soon"] = "Tankwurf bald",
  ["Soak"] = "Soaken",
  ["Take Bats"] = "Fledermäuse übernehmen",
  ["Adds Spawning"] = "Adds erscheinen",
  ["Door Open"] = "Tür offen",
  ["Next Doors"] = "Nächste Türen",
  ["Melt Ice"] = "Eis schmelzen",
  ["Stay Out"] = "Draußen bleiben",
  ["Split Dmg"] = "Schaden aufteilen",
  ["Split Damage"] = "Schaden teilen",
  ["Run Forward"] = "Nach vorne laufen",
  ["Hold W"] = "W gedrückt halten",
  ["Intermission 1"] = "Zwischenphase 1",
  ["Intermission 2"] = "Zwischenphase 2",
  ["Intermission"] = "Zwischenphase",
  ["Full Power"] = "Volle Energie",
  ["New Balls"] = "Neue Kugeln",
  ["Throw"] = "Werfen",
  ["Tank Throw"] = "Tankwurf",
  ["Face Away"] = "Wegdrehen",
  ["Hit Crystal"] = "Kristall schlagen",
  ["Next Soak"] = "Nächstes Soaken",
  ["Stop Cast"] = "Cast stoppen",
  ["Plus Damage on Boss"] = "+Schaden auf Boss",
  ["Parasite"] = "Parasit",
  ["Run Out"] = "Rauslaufen",
  ["Run Over Frost Patch"] = "Über Frostfläche laufen",
  ["Damage Particles"] = "Schadenspartikel",
  ["Jalak"] = "Jalak",
  ["Immune Now"] = "Jetzt immun",
  ["Split Dmg 25 yards"] = "25m Schaden teilen",
  ["Spread 5 yards"] = "5m spreaden",
  ["cant pick up"] = "Kann nicht aufnehmen",
  ["feathers"] = "Federn",
  ["Stop Cast Soon"] = "Cast bald stoppen",
  ["Damage Buff Spew"] = "Schadensbuff-Auswurf",
  ["Prepare to Soak"] = "Bereit zum Soaken",
  ["Move Out of Waters"] = "Aus dem Wasser raus",
  ["{rt8} Spear near!"] = "{rt8} Speer in der Nähe!",
  ["Slow the Add"] = "Add verlangsamen",
  ["Drag Out"] = "Rausziehen",
  ["Take Max Range"] = "Maxrange nehmen",
  ["Kill Adds"] = "Adds töten",
  ["Add Soon"] = "Add bald",
  ["Soaked"] = "Gesoakt",
  ["START MOVING TO |ce6ff4040NEXT|r"] = "BEWEG DICH ZUM |ce6ff4040NÄCHSTEN|r",
  ["MOVE TO NEXT"] = "Zum Nächsten bewegen",
  ["Stun"] = "Stun",
  ["Stack on me"] = "Auf mir stacken",
  ["Big Bang"] = "Big Bang",
  ["Soon"] = "Bald",
  ["Switch to Add"] = "Auf Add switchen",
  ["Switch to |cffff4040Add|r"] = "Auf |cffff4040Add|r switchen",
  ["You are next at |cFF33AAFFupper|r %s in 30s"] = "Du bist in 30s oben bei %s dran",
  ["You are next at |cFFFFAA33lower|r %s in 30s"] = "Du bist in 30s unten bei %s dran",
  ["You are next at the |cFF33FF66middle|r"] = "Du bist als Nächstes in der |cFF33FF66Mitte|r",
  ["Middle"] = "Mitte",
  ["You Next at %s"] = "Du bist Nächster bei %s",
  ["Stack for Thunder"] = "Für Blitz stacken",
  ["Move in"] = "Rein bewegen",
  ["Spread Out for Quicksand"] = "Für Treibsand spreaden",
  ["mastery"] = "Meisterschaft",
  ["North"] = "Norden",
  ["East"] = "Osten",
  ["West"] = "Westen",
  ["South"] = "Süden",
  ["New Add Soon"] = "Neues Add bald",
  ["Move Forward"] = "Nach vorne bewegen",
  ["Beams Spawn"] = "Strahlen erscheinen",
  ["New Water"] = "Neues Wasser",
  ["Storm"] = "Sturm",
  ["Storm Soon"] = "Sturm bald",
  ["crit"] = "Krit",
  ["Life Drain"] = "Lebensentzug",
  ["Dodge Turtles"] = "Schildkröten ausweichen",
  ["Gaze Debuffs"] = "Blick-Debuffs",
  ["Build"] = "Stacks aufbauen",
  ["Dodge Swipe"] = "Hieb ausweichen",
  ["|ce6ff4040Red Add|r revealed"] = "|ce6ff4040Rotes Add|r sichtbar",
  ["Full"] = "Voll",
  ["|cffff4040Megaera|r Rises"] = "|cffff4040Megaera|r erhebt sich",
  ["{rt8} DODGE TO THE SIDES!"] = "{rt8} Zu den Seiten ausweichen!",
  ["Kill the add"] = "Add töten",
  ["Kill Beast"] = "Bestie töten",
  ["Reveal Adds"] = "Adds enthüllen",
  ["Big Ooze"] = "Großschlamm",
  ["Big Ooze Soon"] = "Großschlamm bald",
  ["boss dmg"] = "Boss dmg",
  ["Intermission End"] = "Zwischenphase Ende",
  ["Intermission End in"] = "Endet in",
  ["Stack for Overcharged"] = "Für Überladung stacken",
  ["Dispel"] = "Dispel",
  ["Slow Turtles"] = "Schildkröten verlangsamen",

  ["You're assigned to Control Orb"] = "Du bist für die Orb-Kontrolle eingeteilt",
  ["You're assigned to Stun the Adds"] = "Du bist zum Stunnen der Adds eingeteilt",
  ["You're assigned to Slow the Adds"] = "Du bist zum Verlangsamen der Adds eingeteilt",
  ["You're assigned to Max Range Twisted Fate"] = "Du bist für Max-Range Verdrehte Schicksale eingeteilt",
  ["You're assigned to %s Throw Turtle"] = "Du bist für %s Schildkrötenwurf eingeteilt",
  ["You're assigned to |cff9d9d9dbackup|r %s Throw Turtle"] = "Du bist als |cff9d9d9dBackup|r für %s Schildkrötenwurf eingeteilt",
  ["You're assigned to tank %s Boss"] = "Du bist als Tank für %s Boss eingeteilt",
  ["You're assigned to tank %s Bats"] = "Du bist als Tank für %s Fledermäuse eingeteilt",
  ["You're assigned to slow %s Turtles"] = "Du bist zum Verlangsamen der %s Schildkröten eingeteilt",

  ["Run Wth %s |cffff4040Red Beam|r"] = "Mit %s im |cffff4040Roten Strahl|r laufen",
  ["Run with %s |cff3fc7ebBlue Beam|r"] = "Mit %s im |cff3fc7ebBlauen Strahl|r laufen",
  ["Run with %s |cffffff00Yellow Beam|r"] = "Mit %s im |cffffff00Gelben Strahl|r laufen",

  ["You're assigned to %s |cffff4040Red|r Beam"] = "Du bist im |cffff4040Roten|r Strahl bei %s eingeteilt",
  ["You're assigned to %s |cff3fc7ebBlue|r Beam"] = "Du bist im |cff3fc7ebBlauen|r Strahl bei %s eingeteilt",
  ["You're assigned to %s |cffffff00Yellow|r Beam"] = "Du bist im |cffffff00Gelben|r Strahl bei %s eingeteilt",

  ["Current"] = "Aktuell",
  ["Next"] = "Nächster",
  ["Get Back under the Boss"] = "Zurück unter den Boss",
  ["Stack on %s"] = "Auf %s stacken",
  ["Perfect"] = "Perfekt",
  ["Dispelled"] = "Dispelled",
  ["Dark Energy"] = "Dunkle Energie",
  ["Absorb"] = "Absorb",
}
