Merfin = Merfin or {}
Merfin.Localizations = Merfin.Localizations or {}

Merfin.Localizations.koKR = {

  ["Mark"] = "표식", -- Druid Mark
  ["AP"] = "공격력", -- Attack Power
  ["MP5"] = "5초당 마나", -- MP5
  ["Haste"] = "가속",
  ["Swap"] = "장비 교체",
  ["%s is outdated. Update to version %s+."] = "%s 애드온이 오래되었습니다. %s+ 버전으로 업데이트하세요.",
  ["%s is not loaded. Install version %s or later."] = "%s 이(가) 로드되지 않았습니다. %s 버전 이상을 설치하세요.",
  ["Issues detected:"] = "문제가 발견되었습니다:",
  ["Take %s"] = "%s 가져가기",
  ["Eat %s"] = "%s 먹기",
  ["%s is up"] = "%s 사용 가능",
  ["Assist with Summon"] = "소환 도와주세요",
  ["Ardent Procced"] = "열정적인 수호 발동",
  ["Seal"] = "문장",
  ["Aura"] = "오라",
  ["Pet Food"] = "소환수 음식 버프",
  ["%s asks for |cff40ff40[%s]|r %s"] = "%s 님이 |cff40ff40[%s]|r %s을(를) 요청함",
  ["Pull Timer by %s"] = "%s 님이 풀 타이머 시작",
  ["Break Timer by %s"] = "%s 님이 휴식 타이머 시작",
  ["» %s « is being resurrected"] = "» %s « 부활 중",
  ["Scroll Page"] = "액션바 넘기기",
  ["Drain Soul Phase"] = "영혼 흡수 페이즈",
  ["Hold Ctrl for Release"] = "Ctrl를 눌러 해제",
  ["Use %s on me, please!"] = "%s 나에게 써 주세요!",

  -- Dummy Auras
  ["BIG BANG"] = "빅뱅",
  ["BIG BANG INC."] = "곧 빅뱅",
  ["DEPORTATION ON %s"] = "%s 추방",
  ["%s Huge Tariffs » %s %s"] = "%s 막대한 벌금 » %s %s",
  ["Dummy Bar"] = "테스트 바",
  ["Regular Cooldown Bar"] = "일반 쿨타임 바",
  ["Special #1 Cooldown Bar"] = "특수 #1 쿨타임 바",
  ["Special #2 Cooldown Bar"] = "특수 #2 쿨타임 바",
  ["Special #3 Cooldown Bar"] = "특수 #3 쿨타임 바",
  ["Special #4 Cooldown Bar"] = "특수 #4 쿨타임 바",
  ["Emphasized Cooldown Bar"] = "강조 쿨타임 바",
  ["Ready"] = "준비 완료", -- Cooldown
  ["Pre-warning"] = "사전 경고",

  -- Default replicas
  -- e.g. "Crush Soon" or "Blade Tempest Soon", %s is the mechanic name
  -- You can change the placement of %s if it's more convenient in your language
  ["%s soon"] = "곧 %s",
  ["GTFO"] = "@cffff8b17피하기@r [%s]",
  ["GTFO |cffff4040[%s]|r"] = "|cffff4040피하세요|r [%s]",
  ["%s Removed"] = "%s 해제됨", -- f.e. "Shield removed" on Lei Shi

  -- Flow / Timing
  ["AOE Soon"] = "곧 광역기",
  ["Adds Incoming"] = "쫄 등장",
  ["Boss Arrival"] = "보스 등장",
  ["Flight"] = "비행",
  ["INC."] = "곧 시작",
  ["Phase"] = "페이즈",
  ["Phase 1"] = "1페이즈",
  ["Phase 2"] = "2페이즈",
  ["Phase 3"] = "3페이즈",
  ["Phase 4"] = "4페이즈",
  ["Platform"] = "발판",
  ["Platform 2"] = "2번 발판",
  ["Platform 3"] = "3번 발판",
  ["Debuffs Soon"] = "곧 디버프",

  -- Movement
  ["Behind"] = "뒤쪽",
  ["Dodge"] = "피하기",
  ["Dodge to Left"] = "왼쪽으로 피하기",
  ["Dodge to Right"] = "오른쪽으로 피하기",
  ["Forward"] = "앞쪽",
  ["Frontal"] = "전방",
  ["Hide"] = "숨기",
  ["Inside"] = "안으로",
  ["Left"] = "왼쪽",
  ["Move"] = "이동",
  ["Move Out"] = "밖으로 이동",
  ["Out"] = "바깥",
  ["Right"] = "오른쪽",
  ["Back"] = "뒤로",
  ["Spread Out"] = "산개",
  ["Stack"] = "맞받기",
  ["Stack On Me"] = "나에게 붙기",
  ["Stay Away"] = "멀리 떨어지기",
  ["Prepare to Dodge"] = "피할 준비",

  -- Actions
  ["Auto-Attack"] = "자동 공격",
  ["Be Aware"] = "주의",
  ["Focus Target"] = "주시 대상",
  ["Interrupt Now"] = "지금 차단",
  ["Prepare to stack"] = "맞받을 준비",
  ["Soak the Cast"] = "맞받기",
  ["Stop Attack"] = "딜 중지",
  ["Stop Attack Soon"] = "곧 딜 중지",
  ["Swap In"] = "교대 들어오기",
  ["Swap Out"] = "교대 나가기",
  ["Switch Target"] = "대상 전환",
  ["Switch Targets"] = "대상 바꾸기",
  ["Take the Add"] = "쫄 가져가기",
  ["Target"] = "대상",
  ["You are next"] = "다음은 당신",
  ["Put Pet on %s Passive"] = "소환수 %s를 수동으로 전환",
  ["Burst the boss"] = "보스 폭딜",

  -- Player Status (Debuffs)
  ["DoT"] = "도트",
  ["Feared"] = "공포",
  ["Fixated"] = "주시 대상",
  ["Silenced"] = "침묵",
  ["Stunned"] = "기절",
  ["Targetted"] = "타겟 지정됨",
  ["Trapped"] = "함정에 갇힘",

  -- Buffs / Utility
  ["Mana Regen"] = "마나 회복",
  ["Move Speed"] = "이동 속도",
  ["Protected"] = "보호됨",
  ["Reflect"] = "반사",

  -- Damage / Healing / Output
  ["AOE"] = "광역",
  ["Boss Dmg"] = "보스 딜",
  ["Damage"] = "피해",
  ["Damage Done"] = "가한 피해",
  ["Dmg Done"] = "딜량",
  ["Dmg Tkn"] = "받은 피해",
  ["Dmg/Heal"] = "딜/힐",
  ["Heal Tkn"] = "받은 치유",
  ["Heal to Full"] = "풀피로 채우기",
  ["Healing Done"] = "치유량",

  -- Entities
  ["Add"] = "쫄",
  ["Adds"] = "쫄들",
  ["Entrance"] = "입구",

  -- MSV: Trash
  ["Doors will be broken down"] = "문이 파괴됩니다 (전투 시작)",
  ["Frontal & Knockback"] = "전방기 + 넉백",
  ["Mobs active - East |cffffff80(1/4)|r"] = "몹 활성화 - 동쪽 |cffffff80(1/4)|r",
  ["Mobs active - North |cffffff80(3/4)|r"] = "몹 활성화 - 북쪽 |cffffff80(3/4)|r",
  ["Mobs active - South |cffffff80(4/4)|r"] = "몹 활성화 - 남쪽 |cffffff80(4/4)|r",
  ["Mobs active - West |cffffff80(2/4)|r"] = "몹 활성화 - 서쪽 |cffffff80(2/4)|r",

  -- MSV: The Stone Guard
  ["Amethyst"] = "자수정",
  ["Cobalt"] = "코발트",
  ["Jade"] = "비취",
  ["Jasper"] = "벽옥",
  ["Linked with %s"] = "%s와(과) 연결됨",
  ["Neutralize Traps"] = "함정 해제",
  ["Overload Soon"] = "곧 과부하",
  ["Painters Leaderboard"] = "바닥 칠하기 랭킹",
  ["SNAP"] = "끊어내기",
  ["Snap the chains"] = "사슬 끊기",

  -- MSV: Feng
  ["Arcane Phase"] = "비전 (지팡이) 페이즈",
  ["Barrier"] = "보호막",
  ["DEBUFFS INC."] = "곧 디버프",
  ["Flame Phase"] = "불꽃 (주먹) 페이즈",
  ["Lightning Phase"] = "번개 (창) 페이즈",
  ["Shadow Phase"] = "암흑 (방패) 페이즈",
  ["Shroud"] = "반사막",

  -- MSV: Gara'jal
  ["Shadowy Attack"] = "암흑 공격",
  ["Adds Count"] = "쫄 카운트",
  ["Kill Severers"] = "영혼 절단자 처치",
  ["Shared Damage"] = "공유 피해",
  ["Stats"] = "능력치",

  -- MSV: The Spirit Kings
  ["Kite Skull"] = "해골 연계",
  ["Pinned"] = "못 박힘",

  -- Elegon
  ["Cant Soak"] = "맞받기 불가",
  ["Focus Charges"] = "에너지 구슬 집중 공격",
  ["Falling Floor"] = "바닥 붕괴",
  ["Gossip Available"] = "대화 가능",
  ["YOURE NEXT TO SOAK"] = "다음 맞받기는 당신",

  -- Will of Emperor
  ["Prepare to Root"] = "속박 준비",
  ["Building Up"] = "에너지 축적 중",
  ["Courage"] = "용기",
  ["Dodge Combo"] = "춤 페이즈",
  ["Jan-xi"] = "잔시",
  ["Qin-xi"] = "친시",
  ["Rage"] = "분노",
  ["Strength"] = "힘",
  ["Bonus Attack"] = "추가 공격",

  -- HoF: Trash
  ["Extended CDs"] = "긴 재사용 대기시간 디버프",

  -- HoF: Zor'lok
  ["Echo"] = "메아리 분신",
  ["Melee Boss"] = "근접 보스",
  ["Mind Control"] = "정신 지배",
  ["Mind Control Soon"] = "곧 정신 지배",
  ["Prepare to hide"] = "숨을 준비",
  ["Sonic Rings Soon"] = "곧 음파 링",

  -- HoF: Tayak
  ["Gone with the Wind"] = "바람에 날아감",

  -- HoF: Garalon
  ["Catch Pheromones"] = "페로몬 받기",

  -- HoF: Mel'jarak
  ["Adds Respawn Soon"] = "곧 쫄 리젠",
  ["Cant Hit Prisons"] = "감옥 공격 불가",
  ["Dodge Blade"] = "회전 칼날 피하기",
  ["Right Click Me"] = "오른쪽 클릭",

  -- HoF: Unsok
  ["Cross Globules"] = "구슬 교차시키기",
  ["Press %d"] = "%d번 키 누르기",
  ["Player Explosion"] = "플레이어 폭발",

  -- HoF: Shekzeer
  ["Buff Players"] = "플레이어에게 버프",
  ["Come Get The Buff"] = "버프 받으러 오기",
  ["Combine Resins"] = "점액 모으기",
  ["Explosion Soon"] = "곧 폭발",
  ["Get Buff On Tank"] = "탱커 근처에서 버프 받기",
  ["Fears Soon"] = "곧 공포",

  -- ToES: Protectors
  ["Your Group: Swap in"] = "당신 조: 교대 들어오기",
  ["Your Group: Swap Out"] = "당신 조: 교대 나가기",

  -- ToES: Tsulong
  ["YOURE NEXT TO TAKE |cffffff40LIGHT|r"] = "다음 |cffffff40빛|r 담당은 당신",
  ["Drop Stacks"] = "중첩 빼기",

  -- ToES: Lei Shi
  ["Special Ability"] = "특수 기술",

  -- ToES: Sha of Fear
  ["Forms a Wall"] = "빛의 벽 생성",
  ["Left Platform"] = "왼쪽 발판",
  ["Middle Platform"] = "중앙 발판",
  ["Move to %d"] = "%d번 쪽으로 이동",
  ["Right Platform"] = "오른쪽 발판",
  ["Start in %d"] = "%d번에서 시작",
  ["Random Ability (1 of 3)"] = "무작위 기술 (3개 중 1개)",

  ---------------------------
  -- Throne of Thunder T15 --
  ---------------------------
  ["Comet Soon"] = "곧 혜성",
  ["Red Add killed"] = "빨간 쫄 처치",
  ["Drop Pool"] = "바닥 장판 깔기",
  ["Get to Safe Range"] = "안전 거리로 이동",
  ["Dont Kill Orbs"] = "구슬 치지 마세요",
  ["Arrival"] = "도착",
  ["Unlocked"] = "해제됨",
  ["IMMUNED"] = "면역",
  ["Celestial"] = "천신",
  ["Slows boss abilities"] = "보스 기술 느려짐",
  ["Health / Mana Regen"] = "생명력/마나 회복",
  ["+50% HP"] = "+50% 체력",
  ["Cranes Damage"] = "두루미 피해 증가",
  ["Taunt Big Add"] = "큰 쫄 도발",
  ["AoE Dmg"] = "광역 피해",
  ["Use Defensives"] = "생존기 사용",
  ["Breaths"] = "브레스",
  ["hold debuff"] = "디버프 유지",
  ["pass now"] = "지금 넘기기",
  ["Tank Switch"] = "탱 교대",
  ["Tank Switch Soon"] = "곧 탱 교대",
  ["Safe to Stack"] = "붙어도 안전",
  ["Raid Damage"] = "공대 광역 피해",
  ["Order Reset"] = "순서 리셋",
  ["Taunt Boss"] = "보스 도발",
  ["Stack with me"] = "나와 함께 붙기",
  ["Spread"] = "산개",
  ["Big Add"] = "큰 쫄",
  ["You Assigned"] = "당신 차례",
  ["Beams Phase"] = "광선 페이즈",
  ["Dodge Spear"] = "창 피하기",
  ["Watch Winds"] = "바람 주의",
  ["Focus Adds"] = "쫄 집중 공격",
  ["Knockback"] = "넉백",
  ["COME CLOSER"] = "가까이 붙기",
  ["Interrupting Cast"] = "시전 차단 필요",
  ["Interrupt Soon"] = "곧 차단",
  ["Windstorm"] = "바람 폭풍",
  ["Throw Turtle"] = "거북 던지기",
  ["STOP CAST IN"] = "곧 시전 중지",
  ["Fixate"] = "주시",
  ["Control Orb"] = "구슬 조종",
  ["Right Click Orb"] = "구슬 오른쪽 클릭",
  ["Bell Destroyed"] = "종 파괴됨",
  ["Kite Torrent"] = "물줄기 연계",
  ["+Dmg"] = "피해 증가",
  ["STOP CASTING"] = "시전 그만",
  ["Charge Soon"] = "곧 돌진",
  ["KILL |cffffff80[AMBER FOG]|r ASSAP"] = "|cffffff80[호박 안개]|r 최대한 빨리 처치",
  ["Dodge Particles"] = "입자 피하기",
  ["MOVE BOSS FROM |cffff4040%s|r"] = "보스를 |cffff4040%s|r에서 떼기",
  ["Blue Beam On You"] = "파란 광선 대상자",
  ["Yellow Beam on you"] = "노란 광선 대상자",
  ["Red Beam On You"] = "빨간 광선 대상자",
  ["New Waters"] = "새로운 물 웅덩이",
  ["Upper"] = "위층",
  ["Lower"] = "아래층",
  ["Turtle Throw"] = "거북 던지기",
  ["Breath soon"] = "곧 브레스",
  ["Soak Buff on the |cff3fc7ebPlatform|r"] = "|cff3fc7eb발판|r에서 버프 맞기",
  ["Soak Buff on the |cffff4040Nest|r"] = "|cffff4040둥지|r에서 버프 맞기",
  ["Soak buff on the Nest"] = "둥지에서 버프 맞기",
  ["Soak buff on the Platform"] = "발판에서 버프 맞기",
  ["ICE WALL IN"] = "곧 얼음 벽",
  ["Immune Soon"] = "곧 면역",
  ["Prepare to Stack"] = "붙을 준비",
  ["Next Flock"] = "다음 병아리 무리",
  ["Casting Breath"] = "브레스 시전 중",
  ["Stun the Add"] = "쫄 기절시키기",
  ["Worms"] = "벌레",
  ["Hide Behind Comet"] = "혜성 뒤에 숨기",
  ["Stay Still"] = "움직이지 말기",
  ["Corrupted Balls"] = "부패한 구슬",
  ["Use Movements"] = "이동기 사용",
  ["New Add"] = "새 쫄",
  ["Stop Soak"] = "맞받기 중지",
  ["%d yards"] = "%d미터",
  ["-haste"] = "-가속",
  ["+ Attack and CD"] = "공격 속도 및 재사용 시간 증가",
  ["Feather"] = "깃털",
  ["MOVE ON {rt6} |cff40c7ebSQUARE|r"] = "{rt6} |cff40c7eb네모|r로 이동",
  ["MOVE ON {rt4} |cff00ff00TRIANGLE|r"] = "{rt4} |cff00ff00세모|r로 이동",
  ["Move to Square"] = "네모로 이동",
  ["Move to Triangle"] = "세모로 이동",
  ["KEEP |cffff4040%s|r AWAY!"] = "|cffff4040%s|r 멀리 떼어놓기!",
  ["Balls"] = "구슬",
  ["Balls Soon"] = "곧 구슬",
  ["Death Beam Spawn"] = "죽음 광선 생성",
  ["Death Beam"] = "죽음 광선",
  ["New Adds"] = "새 쫄 등장",
  ["Dont Move"] = "움직이지 말기",
  ["Jolt Obtained"] = "충격 획득",
  ["DONT MOVE TIL |cffff4040ADD|r IS DEAD"] = "|cffff4040쫄|r 죽을 때까지 움직이지 말기",
  ["STOP MOVING"] = "지금 즉시 멈추기",
  ["Death Ray"] = "죽음 광선",
  ["Stay Alone"] = "단독 위치",
  ["Click"] = "클릭",
  ["Head |cFF33AAFFup|r to %s"] = "%s로 |cFF33AAFF위층|r 이동",
  ["Head |cFFFFAA33down|r to %s"] = "%s로 |cFFFFAA33아래층|r 이동",
  ["M"] = "중앙", -- Middle
  ["Head up to the |cFF33FF66middle|r"] = "|cFF33FF66중앙|r으로 이동",
  ["Dinomancer"] = "공룡술사",
  ["Dinomancer Incoming"] = "공룡술사 등장",
  ["Take Spot"] = "자리 맡기",
  ["Raid Damage Soon"] = "곧 공대 광역 피해",
  ["dmg tkn"] = "받은 피해",
  ["Zapped"] = "감전됨",
  ["Right Click!"] = "오른쪽 클릭!",
  ["TANK THROW"] = "탱 던지기",
  ["Tank Throw Soon"] = "곧 탱 던지기",
  ["Soak"] = "맞받기",
  ["Take Bats"] = "박쥐 가져가기",
  ["Adds Spawning"] = "쫄 스폰 중",
  ["Door Open"] = "문 열림",
  ["Next Doors"] = "다음 문",
  ["Melt Ice"] = "얼음 녹이기",
  ["Stay Out"] = "안 들어가기",
  ["Split Dmg"] = "피해 분산",
  ["Split Damage"] = "피해 나누기",
  ["Run Forward"] = "앞으로 달리기",
  ["Hold W"] = "W 고정",
  ["Intermission 1"] = "전환 페이즈 1",
  ["Intermission 2"] = "전환 페이즈 2",
  ["Intermission"] = "전환 페이즈",
  ["Full Power"] = "에너지 가득 참",
  ["New Balls"] = "새 구슬",
  ["Throw"] = "던지기",
  ["Tank Throw"] = "탱 던지기",
  ["Face Away"] = "뒤돌기",
  ["Hit Crystal"] = "수정 공격",
  ["Next Soak"] = "다음 맞받기",
  ["Stop Cast"] = "시전 중지",
  ["Plus Damage on Boss"] = "보스에게 추가 피해",
  ["Parasite"] = "기생충",
  ["Run Out"] = "바깥으로 나가기",
  ["Run Over Frost Patch"] = "얼음 바닥 밟기",
  ["Damage Particles"] = "피해 입자",
  ["Jalak"] = "잘라크",
  ["Immune Now"] = "지금 면역",
  ["Split Dmg 25 yards"] = "25미터 내 피해 분산",
  ["Spread 5 yards"] = "5미터 산개",
  ["cant pick up"] = "줍기 불가",
  ["feathers"] = "깃털",
  ["Stop Cast Soon"] = "곧 시전 중지",
  ["Damage Buff Spew"] = "피해 증가 브레스",
  ["Prepare to Soak"] = "맞받을 준비",
  ["Move Out of Waters"] = "물 바닥에서 나가기",
  ["{rt8} Spear near!"] = "{rt8} 창 근처!",
  ["Slow the Add"] = "쫄 감속",
  ["Drag Out"] = "밖으로 끌어내기",
  ["Take Max Range"] = "최대 거리 유지",
  ["Kill Adds"] = "쫄 처치",
  ["Add Soon"] = "곧 쫄",
  ["Soaked"] = "맞받음 완료",
  ["START MOVING TO |ce6ff4040NEXT|r"] = "|ce6ff4040다음 위치|r로 이동 시작",
  ["MOVE TO NEXT"] = "다음 위치로 이동",
  ["Stun"] = "기절",
  ["Stack on me"] = "나에게 붙기",
  ["Big Bang"] = "빅뱅",
  ["Soon"] = "곧",
  ["Switch to Add"] = "쫄로 전환",
  ["Switch to |cffff4040Add|r"] = "|cffff4040쫄|r로 전환",
  ["You are next at |cFF33AAFFupper|r %s in 30s"] = "30초 후 |cFF33AAFF위층|r %s에서 당신 차례",
  ["You are next at |cFFFFAA33lower|r %s in 30s"] = "30초 후 |cFFFFAA33아래층|r %s에서 당신 차례",
  ["You are next at the |cFF33FF66middle|r"] = "다음은 |cFF33FF66중앙|r의 당신 차례",
  ["Middle"] = "중앙",
  ["You Next at %s"] = "다음은 %s에서 당신",
  ["Stack for Thunder"] = "번개 맞받기 위해 붙기",
  ["Move in"] = "안으로 붙기",
  ["Spread Out for Quicksand"] = "모래 웅덩이 피해서 산개",
  ["mastery"] = "특화",
  ["North"] = "북쪽",
  ["East"] = "동쪽",
  ["West"] = "서쪽",
  ["South"] = "남쪽",
  ["New Add Soon"] = "곧 새 쫄",
  ["Move Forward"] = "앞으로 이동",
  ["Beams Spawn"] = "광선 생성",
  ["New Water"] = "새로운 물 웅덩이",
  ["Storm"] = "폭풍",
  ["Storm Soon"] = "곧 폭풍",
  ["crit"] = "치명타",
  ["Life Drain"] = "생명력 흡수",
  ["Dodge Turtles"] = "거북 피하기",
  ["Gaze Debuffs"] = "응시 디버프",
  ["Build"] = "중첩 쌓기", -- Build stacks on Primordius
  ["Dodge Swipe"] = "휘두르기 피하기",
  ["|ce6ff4040Red Add|r revealed"] = "|ce6ff4040빨간 쫄|r 발견됨",
  ["Full"] = "최대 중첩",
  ["|cffff4040Megaera|r Rises"] = "|cffff4040메가이라|r 등장",
  ["{rt8} DODGE TO THE SIDES!"] = "{rt8} 양옆으로 피하기!",
  ["Kill the add"] = "쫄 처치",
  ["Kill Beast"] = "야수 처치",
  ["Reveal Adds"] = "쫄 드러내기",
  ["Big Ooze"] = "큰 수액괴물",
  ["Big Ooze Soon"] = "곧 큰 수액괴물",
  ["boss dmg"] = "보스 딜",
  ["Intermission End"] = "전환 페이즈 종료",
  ["Intermission End in"] = "종료까지 남음",
  ["Stack for Overcharged"] = "과충전 맞받기 위해 붙기",
  ["Dispel"] = "해제",
  ["Slow Turtles"] = "거북 감속",
  ["You're assigned to Control Orb"] = "당신은 구슬 조종 담당입니다",
  ["You're assigned to Stun the Adds"] = "당신은 쫄 기절 담당입니다",
  ["You're assigned to Slow the Adds"] = "당신은 쫄 감속 담당입니다",
  ["You're assigned to Max Range Twisted Fate"] = "당신은 최대 거리에서 뒤틀린 운명 담당입니다",
  ["You're assigned to %s Throw Turtle"] = "당신은 %s 거북 던지기 담당입니다",
  ["You're assigned to |cff9d9d9dbackup|r %s Throw Turtle"] = "당신은 |cff9d9d9d백업|r %s 거북 던지기 담당입니다",
  ["You're assigned to tank %s Boss"] = "당신은 %s 보스 탱킹 담당입니다",
  ["You're assigned to tank %s Bats"] = "당신은 %s 박쥐 탱킹 담당입니다",
  ["You're assigned to slow %s Turtles"] = "당신은 %s 거북 감속 담당입니다",
  ["Run Wth %s |cffff4040Red Beam|r"] = "%s와 함께 |cffff4040빨간 광선|r에서 이동",
  ["Run with %s |cff3fc7ebBlue Beam|r"] = "%s와 함께 |cff3fc7eb파란 광선|r에서 이동",
  ["Run with %s |cffffff00Yellow Beam|r"] = "%s와 함께 |cffffff00노란 광선|r에서 이동",
  ["You're assigned to %s |cffff4040Red|r Beam"] = "당신은 %s와 함께 |cffff4040빨간|r 광선 담당입니다",
  ["You're assigned to %s |cff3fc7ebBlue|r Beam"] = "당신은 %s와 함께 |cff3fc7eb파란|r 광선 담당입니다",
  ["You're assigned to %s |cffffff00Yellow|r Beam"] = "당신은 %s와 함께 |cffffff00노란|r 광선 담당입니다",
  ["Current"] = "현재",
  ["Next"] = "다음",
  ["Get Back under the Boss"] = "보스 발밑으로 복귀",
  ["Stack on %s"] = "%s에게 붙기",
  ["Perfect"] = "완벽",
  ["Dispelled"] = "해제됨",
  ["Dark Energy"] = "어둠의 에너지",
  ["Absorb"] = "흡수",
  ["Doors Opened"] = "문이 열렸습니다",
  ["Frontal inc."] = "곧 정면 공격",
  ["Adds inc."] = "곧 쫄 등장",
  ["Adds Soon"] = "곧 쫄",
}
