Merfin = Merfin or {}
Merfin.Localizations = Merfin.Localizations or {}

Merfin.Localizations.zhCN = {

  ["%d-%dy"] = "%d-%d码", -- 25-30y (range)
  ["GLOVES READY"] = "手套已就绪",
  ["Gloves Inc"] = "手套生效中",
  ["LOW MANA"] = "法力值过低",
  ["Mark"] = "爪子", -- Druid Mark
  ["AP"] = "攻强", -- Attack Power
  ["MP5"] = "回蓝", -- MP5
  ["Haste"] = "急速",
  ["Swap"] = "换装",
  ["%s is outdated. Update to version %s+."] = "%s 已过期，请更新到 %s+ 版本。",
  ["%s is not loaded. Install version %s or later."] = "%s 未加载，请安装 %s 或更高版本。",
  ["Issues detected:"] = "发现问题：",
  ["Take %s"] = "拿 %s",
  ["Eat %s"] = "吃 %s",
  ["%s is up"] = "%s 已激活",
  ["Assist with Summon"] = "帮忙拉人",
  ["Ardent Procced"] = "炽热防御触发",
  ["Seal"] = "圣印",
  ["Aura"] = "光环",
  ["Pet Food"] = "宠物进食增益",
  ["%s asks for |cff40ff40[%s]|r %s"] = "%s 请求 |cff40ff40[%s]|r %s",
  ["Pull Timer by %s"] = "由 %s 发起的开怪计时",
  ["Break Timer by %s"] = "由 %s 发起的休息计时",
  ["» %s « is being resurrected"] = "» %s « 正在被复活",
  ["Scroll Page"] = "切换动作条",
  ["Drain Soul Phase"] = "吸取灵魂阶段",
  ["Hold Ctrl for Release"] = "按住 Ctrl 释放",
  ["Use %s on me, please!"] = "请给我 %s！",

  -- Dummy Auras
  ["BIG BANG"] = "大爆炸",
  ["BIG BANG INC."] = "即将大爆炸",
  ["DEPORTATION ON %s"] = "驱逐 %s",
  ["%s Huge Tariffs » %s %s"] = "%s 巨额罚款 » %s %s",
  ["Dummy Bar"] = "测试计时条",
  ["Regular Cooldown Bar"] = "常规冷却条",
  ["Special #1 Cooldown Bar"] = "特殊#1冷却条",
  ["Special #2 Cooldown Bar"] = "特殊#2冷却条",
  ["Special #3 Cooldown Bar"] = "特殊#3冷却条",
  ["Special #4 Cooldown Bar"] = "特殊#4冷却条",
  ["Emphasized Cooldown Bar"] = "高亮冷却条",
  ["Ready"] = "准备", -- Cooldown
  ["Pre-warning"] = "预警",

  -- Default replicas
  -- e.g. "Crush Soon" or "Blade Tempest Soon", %s is the mechanic name
  -- You can change the placement of %s if it's more convenient in your language
  ["%s soon"] = "即将 %s ",
  ["GTFO"] = "@cffff8b17走开@r [%s]",
  ["GTFO |cffff4040[%s]|r"] = "|cffff4040走开|r [%s]",
  ["%s Removed"] = "%s 移除", -- f.e. "Shield removed" on Lei Shi

  -- Flow / Timing
  ["AOE Soon"] = "准备AOE",
  ["Adds Incoming"] = "小怪刷新",
  ["Boss Arrival"] = "BOSS刷新",
  ["Flight"] = "飞行",
  ["INC."] = "即将到来",
  ["Phase"] = "阶段",
  ["Phase 1"] = "1阶段",
  ["Phase 2"] = "2阶段",
  ["Phase 3"] = "3阶段",
  ["Phase 4"] = "4阶段",
  ["Platform"] = "平台",
  ["Platform 2"] = "2平台",
  ["Platform 3"] = "3平台",
  ["Debuffs Soon"] = "准备Debuffs",

  -- Movement
  ["Behind"] = "背后",
  ["Dodge"] = "回避",
  ["Dodge to Left"] = "向左回避",
  ["Dodge to Right"] = "向右回避",
  ["Forward"] = "向前",
  ["Frontal"] = "头前",
  ["Hide"] = "躲藏",
  ["Inside"] = "进场",
  ["Left"] = "左",
  ["Move"] = "移动",
  ["Move Out"] = "跑开",
  ["Out"] = "出",
  ["Right"] = "右",
  ["Back"] = "后",
  ["Spread Out"] = "分散",
  ["Stack"] = "分摊",
  ["Stack On Me"] = "找我分摊",
  ["Stay Away"] = "远离人群",
  ["Prepare to Dodge"] = "准备躲避",

  -- Actions
  ["Auto-Attack"] = "自动攻击",
  ["Be Aware"] = "注意",
  ["Focus Target"] = "焦点目标",
  ["Interrupt Now"] = "现在打断",
  ["Prepare to stack"] = "准备分摊",
  ["Soak the Cast"] = "分摊法术",
  ["Stop Attack"] = "停止攻击",
  ["Stop Attack Soon"] = "即将停止攻击",
  ["Swap In"] = "换入",
  ["Swap Out"] = "换出",
  ["Switch Target"] = "切换目标",
  ["Switch Targets"] = "切换目标",
  ["Take the Add"] = "接小怪",
  ["Target"] = "目标",
  ["You are next"] = "下一个是你",
  ["Put Pet on %s Passive"] = "将宠物 %s 设置被动",
  ["Burst the boss"] = "正面",

  -- Player Status (Debuffs)
  ["DoT"] = "DoT",
  ["Feared"] = "恐惧",
  ["Fixated"] = "被锁定",
  ["Silenced"] = "沉默",
  ["Stunned"] = "眩晕",
  ["Targetted"] = "目标是你",
  ["Trapped"] = "被困",

  -- Buffs / Utility
  ["Mana Regen"] = "回蓝",
  ["Move Speed"] = "移速",
  ["Protected"] = "保护",
  ["Reflect"] = "反射",

  -- Damage / Healing / Output
  ["AOE"] = "AOE",
  ["Boss Dmg"] = "Boss 伤害",
  ["Damage"] = "伤害",
  ["Damage Done"] = "伤害输出",
  ["Dmg Done"] = "伤害输出",
  ["Dmg Tkn"] = "承伤",
  ["Dmg/Heal"] = "伤害/治疗",
  ["Heal Tkn"] = "受到治疗",
  ["Heal to Full"] = "奶满",
  ["Healing Done"] = "治疗量",

  -- Entities
  ["Add"] = "小怪",
  ["Adds"] = "小怪群",
  ["Entrance"] = "入口",

  -- MSV: Trash
  ["Doors will be broken down"] = "打破大门(战斗开场)",
  ["Frontal & Knockback"] = "头前与击退",
  ["Mobs active - East |cffffff80(1/4)|r"] = "大怪激活-东 |cffffff80(1/4)|r",
  ["Mobs active - North |cffffff80(3/4)|r"] = "大怪激活-北 |cffffff80(3/4)|r",
  ["Mobs active - South |cffffff80(4/4)|r"] = "大怪激活-南|cffffff80(4/4)|r",
  ["Mobs active - West |cffffff80(2/4)|r"] = "大怪激活-西 |cffffff80(2/4)|r",

  -- MSV: The Stone Guard
  ["Amethyst"] = "紫晶",
  ["Cobalt"] = "蓝晶",
  ["Jade"] = "青玉",
  ["Jasper"] = "红玉",
  ["Linked with %s"] = "与 %s 连线",
  ["Neutralize Traps"] = "接触陷阱",
  ["Overload Soon"] = "即将过载",
  ["Painters Leaderboard"] = "搬砖排行榜",
  ["SNAP"] = "拉断",
  ["Snap the chains"] = "挣脱锁链",

  -- MSV: Feng
  ["Arcane Phase"] = "奥术(杖)阶段",
  ["Barrier"] = "屏障",
  ["DEBUFFS INC."] = "即将debuff.",
  ["Flame Phase"] = "火焰(拳)阶段",
  ["Lightning Phase"] = "闪电(矛)阶段",
  ["Shadow Phase"] = "暗影(盾)阶段",
  ["Shroud"] = "反射罩",

  -- MSV: Gara'jal
  ["Shadowy Attack"] = "暗影攻击",
  ["Adds Count"] = "小怪计数",
  ["Kill Severers"] = "击杀灵魂撕裂者(大怪)", -- https://www.wowhead.com/mop-classic/spell=116278/soul-sever
  ["Shared Damage"] = "复制伤害", -- https://www.wowhead.com/mop-classic/spell=122151/voodoo-doll
  ["Stats"] = "属性", -- https://www.wowhead.com/mop-classic/spell=117549/spiritual-innervation

  -- MSV: The Spirit Kings
  ["Kite Skull"] = "风筝骷髅",
  ["Pinned"] = "被钉住", -- https://www.wowhead.com/mop-classic/spell=118135/pinned-down

  -- Elegon
  ["Cant Soak"] = "不能分摊", -- https://www.wowhead.com/mop-classic/spell=132226/destabilized
  ["Focus Charges"] = "注意充能", -- Energy Charges
  ["Falling Floor"] = "地板崩塌",
  ["Gossip Available"] = "对话可用",
  ["YOURE NEXT TO SOAK"] = "你是下一个分摊",

  -- Will of Emperor
  ["Prepare to Root"] = "准备定身（缠绕）",
  ["Building Up"] = "能量积聚（平砍阶段）", -- Energy goes to full
  ["Courage"] = "勇气",
  ["Dodge Combo"] = "跳舞阶段",
  ["Jan-xi"] = "剑曦",
  ["Qin-xi"] = "秦希",
  ["Rage"] = "狂怒",
  ["Strength"] = "力量",
  ["Bonus Attack"] = "额外攻击",

  -- HoF: Trash
  ["Extended CDs"] = "延长技能CD", -- Last Boss Room https://www.wowhead.com/spell=125907/cry-havoc

  -- HoF: Zor'lok
  ["Echo"] = "回响分身", -- Boss Clone Name without postfix
  ["Melee Boss"] = "近战boss", -- https://www.wowhead.com/mop-classic/spell=132236/song-of-the-empress
  ["Mind Control"] = "心控", -- https://www.wowhead.com/spell=122740/convert
  ["Mind Control Soon"] = "即将心控", -- https://www.wowhead.com/spell=122740/convert
  ["Prepare to hide"] = "准备躲藏", -- https://www.wowhead.com/spell=122713/force-and-verve
  ["Sonic Rings Soon"] = "即将音波", -- https://www.wowhead.com/spell=127834/attenuation

  -- HoF: Tayak
  ["Gone with the Wind"] = "风暴释放", -- Start of Phase 2, when you're getting carried by Winds

  -- HoF: Garalon
  ["Catch Pheromones"] = "接信息素",

  -- HoF: Mel'jarak
  ["Adds Respawn Soon"] = "小怪即将重生",
  ["Cant Hit Prisons"] = "无法攻击监牢", -- https://www.wowhead.com/mop-classic/spell=122055/residue
  ["Dodge Blade"] = "躲回旋之刃", -- https://www.wowhead.com/spell=91294/whirling-blade
  ["Right Click Me"] = "右键点我", -- https://www.wowhead.com/mop-classic/spell=121885/amber-prison

  -- HoF: Unsok
  ["Cross Globules"] = "合并宝珠", -- https://www.wowhead.com/mop-classic/spell=125502/amber-beacon
  ["Press %d"] = "按 %d", -- Press 1, Press 2 etc.
  ["Player Explosion"] = "玩家炸团", -- Explosion in Monstrocity

  -- HoF: Shekzeer
  ["Buff Players"] = "增益玩家", -- https://www.wowhead.com/mop-classic/spell=124821/poison-drenched-armor
  ["Come Get The Buff"] = "来拿增益", -- https://www.wowhead.com/mop-classic/spell=124821/poison-drenched-armor
  ["Combine Resins"] = "聚集树脂", -- https://www.wowhead.com/mop-classic/spell=124097/sticky-resin
  ["Explosion Soon"] = "即将爆炸", -- Dissonance Field @ 10% health
  ["Get Buff On Tank"] = "靠近坦克获得增益", -- https://www.wowhead.com/mop-classic/spell=124827/poison-fumes
  ["Fears Soon"] = "即将恐惧",

  -- ToES: Protectors
  ["Your Group: Swap in"] = "你的队伍：换入",
  ["Your Group: Swap Out"] = "你的队伍：换出",

  -- ToES: Tsulong
  ["YOURE NEXT TO TAKE |cffffff40LIGHT|r"] = "你下一个接 |cffffff40光|r", -- https://www.wowhead.com/mop-classic/spell=123716/the-light-of-day
  ["Drop Stacks"] = "消除层数",

  -- ToES: Lei Shi
  ["Special Ability"] = "特殊技能",

  -- ToES: Sha of Fear
  ["Forms a Wall"] = "形成光墙", -- https://www.wowhead.com/mop-classic/spell=117866/champion-of-the-light
  ["Left Platform"] = "左侧平台",
  ["Middle Platform"] = "中间平台",
  ["Move to %d"] = "移动到 %d",
  ["Right Platform"] = "右侧平台",
  ["Start in %d"] = "起始于 %d", -- Position on Sha Sector Helper
  ["Random Ability (1 of 3)"] = "R随机技能 (3选1)",

  ---------------------------
  -- Throne of Thunder T15 --
  ---------------------------
  ["Comet Soon"] = "即将彗星",
  ["Red Add killed"] = "红色小怪已击杀",
  ["Drop Pool"] = "放水",
  ["Get to Safe Range"] = "移动到安全距离",
  ["Dont Kill Orbs"] = "不要打球",
  ["Arrival"] = "到达",
  ["Unlocked"] = "已解锁",
  ["IMMUNED"] = "免疫",
  ["Celestial"] = "天神",
  ["Slows boss abilities"] = "降低首领技能速度",
  ["Health / Mana Regen"] = "生命/法力恢复",
  ["+50% HP"] = "+50% 生命值",
  ["Cranes Damage"] = "朱鹤伤害",
  ["Taunt Big Add"] = "嘲讽大怪",
  ["AoE Dmg"] = "范围伤害",
  ["Use Defensives"] = "开自保技能",
  ["Breaths"] = "吐息",
  ["hold debuff"] = "保持debuff",
  ["pass now"] = "立即传递",
  ["Tank Switch"] = "换坦",
  ["Tank Switch Soon"] = "即将换坦",
  ["Safe to Stack"] = "可以集合",
  ["Raid Damage"] = "全团伤害",
  ["Order Reset"] = "顺序重置",
  ["Taunt Boss"] = "嘲讽BOSS",
  ["Stack with me"] = "跟我集合",
  ["Spread"] = "分散",
  ["Big Add"] = "大怪",
  ["You Assigned"] = "轮到你",
  ["Beams Phase"] = "光束阶段",
  ["Dodge Spear"] = "躲矛",
  ["Watch Winds"] = "注意旋风",
  ["Focus Adds"] = "集火小怪",
  ["Knockback"] = "击退",
  ["COME CLOSER"] = "靠近一点",
  ["Interrupting Cast"] = "打断施法",
  ["Interrupt Soon"] = "即将打断",
  ["Windstorm"] = "风暴",
  ["Throw Turtle"] = "扔乌龟",
  ["STOP CAST IN"] = "即将停止施法",
  ["Fixate"] = "锁定",
  ["Control Orb"] = "控制球体",
  ["Right Click Orb"] = "右键点击球体",
  ["Bell Destroyed"] = "钟已被摧毁",
  ["Kite Torrent"] = "风筝洪流",
  ["+Dmg"] = "伤害提高",
  ["STOP CASTING"] = "停手",
  ["Charge Soon"] = "即将冲锋",
  ["KILL |cffffff80[AMBER FOG]|r ASSAP"] = "尽快击杀 |cffffff80[琥珀迷雾]|r",
  ["Dodge Particles"] = "躲避碎片",
  ["MOVE BOSS FROM |cffff4040%s|r"] = "把首领拉离 |cffff4040%s|r",
  ["Blue Beam On You"] = "蓝光点你",
  ["Yellow Beam on you"] = "黄光点你",
  ["Red Beam On You"] = "红光点你",
  ["New Waters"] = "新的水池",
  ["Upper"] = "上层",
  ["Lower"] = "下层",
  ["Turtle Throw"] = "扔乌龟",
  ["Breath soon"] = "即将吐息",
  ["Soak Buff on the |cff3fc7ebPlatform|r"] = "在 |cff3fc7eb大平台|r 吃增益",
  ["Soak Buff on the |cffff4040Nest|r"] = "在 |cffff4040巢穴|r 吃增益",
  ["Soak buff on the Nest"] = "在巢穴吃增益",
  ["Soak buff on the Platform"] = "在大平台吃增益",
  ["ICE WALL IN"] = "即将冰墙",
  ["Immune Soon"] = "即将免疫",
  ["Prepare to Stack"] = "准备集合",
  ["Next Flock"] = "下一波蝙蝠",
  ["Casting Breath"] = "正在施放吐息",
  ["Stun the Add"] = "眩晕小怪",
  ["Worms"] = "蝙蝠",
  ["Hide Behind Comet"] = "躲在彗星后面",
  ["Stay Still"] = "不要移动",
  ["Corrupted Balls"] = "腐化之球",
  ["Use Movements"] = "使用位移技能",
  ["New Add"] = "新小怪",
  ["Stop Soak"] = "停止踩圈",
  ["%d yards"] = "%d码",
  ["-haste"] = "-急速",
  ["+ Attack and CD"] = "攻击和冷却加快",
  ["Feather"] = "羽毛",
  ["MOVE ON {rt6} |cff40c7ebSQUARE|r"] = "移动到 {rt6} |cff40c7eb方形|r",
  ["MOVE ON {rt4} |cff00ff00TRIANGLE|r"] = "移动到 {rt4} |cff00ff00三角|r",
  ["Move to Square"] = "去方块",
  ["Move to Triangle"] = "去三角",
  ["KEEP |cffff4040%s|r AWAY!"] = "让 |cffff4040%s|r 远离！",
  ["Balls"] = "球",
  ["Balls Soon"] = "即将出球",
  ["Death Beam Spawn"] = "死亡光束出现",
  ["Death Beam"] = "死亡光束",
  ["New Adds"] = "新一波小怪",
  ["Dont Move"] = "不要移动",
  ["Jolt Obtained"] = "获得震荡",
  ["DONT MOVE TIL |cffff4040ADD|r IS DEAD"] = "在 |cffff4040小怪|r 死前不要移动",
  ["STOP MOVING"] = "立刻停下",
  ["Death Ray"] = "死亡射线",
  ["Stay Alone"] = "单独站位",
  ["Click"] = "点击",
  ["Head |cFF33AAFFup|r to %s"] = "向 |cFF33AAFF上层|r 前往 %s",
  ["Head |cFFFFAA33down|r to %s"] = "向 |cFFFFAA33下层|r 前往 %s",
  ["M"] = "中", -- Middle
  ["Head up to the |cFF33FF66middle|r"] = "前往 |cFF33FF66中层|r",
  ["Dinomancer"] = "恐龙召唤师",
  ["Dinomancer Incoming"] = "恐龙召唤师来了",
  ["Take Spot"] = "去占位置",
  ["Raid Damage Soon"] = "即将全团伤害",
  ["dmg tkn"] = "受到伤害",
  ["Zapped"] = "被电击",
  ["Right Click!"] = "按右键！",
  ["TANK THROW"] = "坦克投掷",
  ["Tank Throw Soon"] = "即将坦克投掷",
  ["Soak"] = "踩圈",
  ["Take Bats"] = "接蝙蝠",
  ["Adds Spawning"] = "小怪刷新",
  ["Door Open"] = "大门开启",
  ["Next Doors"] = "下一扇门",
  ["Melt Ice"] = "融冰",
  ["Stay Out"] = "出去",
  ["Split Dmg"] = "分摊伤害",
  ["Split Damage"] = "分摊伤害",
  ["Run Forward"] = "向前跑",
  ["Hold W"] = "按住W",
  ["Intermission 1"] = "阶段转换 1",
  ["Intermission 2"] = "阶段转换 2",
  ["Intermission"] = "阶段转换",
  ["Full Power"] = "能量满",
  ["New Balls"] = "新的球",
  ["Throw"] = "投掷",
  ["Tank Throw"] = "坦克投掷",
  ["Face Away"] = "背对人群",
  ["Hit Crystal"] = "攻击水晶",
  ["Next Soak"] = "下一次踩圈",
  ["Stop Cast"] = "停手",
  ["Plus Damage on Boss"] = "对首领伤害提高",
  ["Parasite"] = "寄生虫",
  ["Run Out"] = "跑出去",
  ["Run Over Frost Patch"] = "踩过冰霜地面",
  ["Damage Particles"] = "伤害碎片",
  ["Jalak"] = "贾拉克",
  ["Immune Now"] = "现在免疫",
  ["Split Dmg 25 yards"] = "25码分摊伤害",
  ["Spread 5 yards"] = "5码分散",
  ["cant pick up"] = "无法拾取",
  ["feathers"] = "羽毛",
  ["Stop Cast Soon"] = "即将停手",
  ["Damage Buff Spew"] = "伤害增益喷吐",
  ["Prepare to Soak"] = "准备踩圈",
  ["Move Out of Waters"] = "离开水池",
  ["{rt8} Spear near!"] = "{rt8} 附近有长矛！",
  ["Slow the Add"] = "减速小怪",
  ["Drag Out"] = "拉到外面",
  ["Take Max Range"] = "拉到最远距离",
  ["Kill Adds"] = "击杀小怪",
  ["Add Soon"] = "即将出小怪",
  ["Soaked"] = "已踩",
  ["START MOVING TO |ce6ff4040NEXT|r"] = "开始移动到 |ce6ff4040下一个位置|r",
  ["MOVE TO NEXT"] = "移动到下一处",
  ["Stun"] = "眩晕",
  ["Stack on me"] = "找我集合",
  ["Big Bang"] = "大爆炸",
  ["Soon"] = "即将到来",
  ["Switch to Add"] = "转火小怪",
  ["Switch to |cffff4040Add|r"] = "转火 |cffff4040小怪|r",
  ["You are next at |cFF33AAFFupper|r %s in 30s"] = "30秒后轮到你去 |cFF33AAFF上层|r %s",
  ["You are next at |cFFFFAA33lower|r %s in 30s"] = "30秒后轮到你去 |cFFFFAA33下层|r %s",
  ["You are next at the |cFF33FF66middle|r"] = "下一位是你去 |cFF33FF66中层|r",
  ["Middle"] = "中层",
  ["You Next at %s"] = "下一位是你在 %s",
  ["Stack for Thunder"] = "集合吃雷",
  ["Move in"] = "进去",
  ["Spread Out for Quicksand"] = "为流沙分散",
  ["mastery"] = "精通",
  ["North"] = "北",
  ["East"] = "东",
  ["West"] = "西",
  ["South"] = "南",
  ["New Add Soon"] = "即将出新小怪",
  ["Move Forward"] = "向前移动",
  ["Beams Spawn"] = "光束出现",
  ["New Water"] = "新的水池",
  ["Storm"] = "风暴",
  ["Storm Soon"] = "即将风暴",
  ["crit"] = "暴击",
  ["Life Drain"] = "生命吸取",
  ["Dodge Turtles"] = "躲乌龟",
  ["Gaze Debuffs"] = "凝视减益",
  ["Build"] = "叠层", -- Build stacks on Primordius
  ["Dodge Swipe"] = "躲横扫",
  ["|ce6ff4040Red Add|r revealed"] = "|ce6ff4040红色小怪|r 已显形",
  ["Full"] = "满层",
  ["|cffff4040Megaera|r Rises"] = "|cffff4040墨格拉|r 现身",
  ["{rt8} DODGE TO THE SIDES!"] = "{rt8} 向两侧躲避！",
  ["Kill the add"] = "击杀小怪",
  ["Kill Beast"] = "击杀野兽",
  ["Reveal Adds"] = "显形小怪",
  ["Big Ooze"] = "大软泥怪",
  ["Big Ooze Soon"] = "大软泥怪即将出现",
  ["boss dmg"] = "对首领伤害",
  ["Intermission End"] = "阶段结束",
  ["Intermission End in"] = "阶段结束于",
  ["Stack for Overcharged"] = "为超载集合", -- https://www.wowhead.com/spell=136295/overcharged
  ["Dispel"] = "驱散",
  ["Slow Turtles"] = "减速海龟",
  ["You're assigned to Control Orb"] = "你被指派去控制宝珠",
  ["You're assigned to Stun the Adds"] = "你被指派去眩晕小怪",
  ["You're assigned to Slow the Adds"] = "你被指派去减速小怪",
  ["You're assigned to Max Range Twisted Fate"] = "你被指派去最远距离处理命运双生",
  ["You're assigned to %s Throw Turtle"] = "你被指派去 %s 投掷乌龟",
  ["You're assigned to |cff9d9d9dbackup|r %s Throw Turtle"] = "你被指派去 |cff9d9d9d支援|r %s 投掷乌龟",
  ["You're assigned to tank %s Boss"] = "你被指派去坦住 %s BOSS",
  ["You're assigned to tank %s Bats"] = "你被指派去坦住 %s 蝙蝠",
  ["You're assigned to slow %s Turtles"] = "你被指派去减速 %s 乌龟",
  ["Run Wth %s |cffff4040Red Beam|r"] = "和 %s 一起跑 |cffff4040红光束|r",
  ["Run with %s |cff3fc7ebBlue Beam|r"] = "和 %s 一起跑 |cff3fc7eb蓝光束|r",
  ["Run with %s |cffffff00Yellow Beam|r"] = "和 %s 一起跑 |cffffff00黄光束|r",
  ["You're assigned to %s |cffff4040Red|r Beam"] = "你被指派到 %s |cffff4040红色|r 光束",
  ["You're assigned to %s |cff3fc7ebBlue|r Beam"] = "你被指派到 %s |cff3fc7eb蓝色|r 光束",
  ["You're assigned to %s |cffffff00Yellow|r Beam"] = "你被指派到 %s |cffffff00黄色|r 光束",
  ["Current"] = "当前",
  ["Next"] = "下一个",
  ["Get Back under the Boss"] = "回到BOSS脚下",
  ["Stack on %s"] = "找 %s 集合",
  ["Perfect"] = "完美", -- When you immune Ionization =)
  ["Dispelled"] = "已驱散",
  ["Dark Energy"] = "黑暗能量",
  ["Absorb"] = "吸收",
  ["Doors Opened"] = "大门已开启",
  ["Frontal inc."] = "即将头前",
  ["Adds inc."] = "小怪即将出现",
  ["Adds Soon"] = "即将出小怪",

  ["+Fire Dmg"] = "+火焰伤害",
  ["+Frost Dmg"] = "+冰霜伤害",
  ["+Nature Dmg"] = "+自然伤害",
  ["Agent Spawn"] = "密探",
  ["Agents Spawned"] = "密探出现",
  ["Agents incoming"] = "密探即将出现",
  ["Atrophic"] = "萎缩",
  ["Boss Gains"] = "首领获得",
  ["Boss is Frost"] = "冰霜阶段",
  ["Boss is Nature"] = "自然阶段",
  ["Breath"] = "深呼吸",
  ["Bubbles Chasing"] = "泡泡追你",
  ["Burn Shield"] = "燃烧护盾",
  ["CC"] = "控制",
  ["Chasing you"] = "正在追你",
  ["Cleanse"] = "净化",
  ["Defensives"] = "减伤",
  ["Demon Form"] = "恶魔形态",
  ["Disoriented"] = "迷失方向",
  ["Elemental"] = "被污染的元素",
  ["Elemental Active"] = "元素激活",
  ["Elemental CD"] = "元素冷却",
  ["Emerge"] = "重新出现",
  ["Empty Bags"] = "清空背包",
  ["Equip Weapon"] = "装备武器",
  ["Expiring"] = "即将结束",
  ["Fear"] = "恐惧",
  ["Focus Egg"] = "凤凰卵",
  ["Free MC"] = "解除心控",
  ["Frenzy"] = "狂暴",
  ["Frost Phase"] = "冰霜阶段",
  ["Gaze"] = "凝视",
  ["Geyser"] = "喷泉",
  ["Grand Astromancer Capernian"] = "卡波妮娅",
  ["Gravity"] = "重力",
  ["Grounding!"] = "接地！",
  ["Human Form"] = "人形态",
  ["I just gave you the Tainted Core!"] = "我刚把污浊核心给你了！",
  ["Immune"] = "免疫",
  ["Infection"] = "感染",
  ["Interrupt"] = "打断",
  ["Jump Down"] = "跳下去",
  ["Kill Demon"] = "击杀恶魔",
  ["Kill Totem"] = "击杀图腾",
  ["Lord Sanguinar"] = "萨古纳尔",
  ["MC"] = "心控",
  ["MCed"] = "被心控",
  ["Master Engineer Telonicus"] = "塔隆尼库斯",
  ["Meteor"] = "流星",
  ["Move Away"] = "远离",
  ["Murlocs"] = "鱼人群",
  ["Naga"] = "盘牙精英",
  ["Naga Spawned"] = "纳迦出现",
  ["Nature Phase"] = "自然阶段",
  ["New Elemental"] = "新的元素",
  ["New Gaze target"] = "新的凝视目标",
  ["New Phoenix"] = "新的凤凰",
  ["New Strider"] = "新的巡逻者",
  ["Next Platform"] = "下一个位置",
  ["Next Split"] = "分裂",
  ["Orb On You"] = "宝珠在你身上",
  ["Phase 5"] = "第5阶段",
  ["Phoenix Rebirth"] = "复生",
  ["Phoenix Spawned"] = "凤凰出现",
  ["Priest Spawn"] = "祭司与索兰莉安",
  ["Priests & Solarian incoming"] = "祭司与索兰莉安即将出现",
  ["Priests Spawned"] = "祭司与索兰莉安出现",
  ["Quake"] = "震荡",
  ["Rooted"] = "被定身",
  ["Run Away"] = "快跑",
  ["Shield"] = "护盾",
  ["Shield Stack Removed"] = "护盾层数移除",
  ["Spellsteal"] = "法术偷取",
  ["Split Soon"] = "5秒后分裂",
  ["Spout Soon"] = "即将喷水",
  ["Step Out"] = "走出去",
  ["Strider"] = "盘牙巡逻者",
  ["Strider Spawned"] = "巡逻者出现",
  ["Stuns"] = "昏迷",
  ["Submerge"] = "下潜",
  ["Tank Swap"] = "换坦",
  ["Thaladred the Darkener"] = "萨拉德雷",
  ["Threat Reset"] = "仇恨重置",
  ["Too Close"] = "太近了",
  ["Tornado"] = "龙卷风",
  ["Total HP"] = "总生命值",
  ["Tranq Shot"] = "宁神射击",
  ["Use Defs"] = "开减伤",
  ["Use FD!"] = "假死！",
  ["Use Staff"] = "使用法杖",
  ["You have"] = "你有",
  ["stunned"] = "昏迷",
  ["{rt2} CORE ON ME!"] = "{rt2} 核心在我身上！",
  ["{rt2} Threw Tainted Core on "] = "{rt2} 把污浊核心丢给了 ",
  ["{rt7} GRAVE ON ME!"] = "{rt7} 墓碑在我身上！",
  ["{rt8} GAZE ON ME!"] = "{rt8} 凝视我！",
  ["{rt8} MC ON ME! CC ME!"] = "{rt8} 我被心控！控我！",
  ["{rt8} MC ON ME! FREE ME!"] = "{rt8} 我被心控！救我！",
  ["{rt8} STATIC ON ME! MOVE AWAY"] = "{rt8} 静电在我身上！快散开！",
  ["{rt8} WRATH ON ME!"] = "{rt8} 愤怒在我身上！",
}
