--Modify From NDui
--msylgj0
--thx to siweia :P

--config start--
local MicroMenuPos = {"TOP", UIParent, "TOP", -120, 1}
local Scale = 0.9
--config end--

local Media = "Interface\\Addons\\MicroMenu\\Media\\"
local bdTex = "Interface\\ChatFrame\\ChatFrameBackground"
local glowTex = Media.."glowTex"
local InfoColor = "|cff70C0F5"
local myClass = select(2, UnitClass("player"))
local color = (CUSTOM_CLASS_COLORS or RAID_CLASS_COLORS)[myClass]
local faction = UnitFactionGroup("player")

local MB = CreateFrame("frame", nil, UIParent)
MB:SetSize(210, 20)
MB:SetScale(Scale)
MB:SetPoint(unpack(MicroMenuPos))
MB:RegisterEvent("PLAYER_ENTERING_WORLD")
MB:SetScript("OnEvent", function()
	MB:UnregisterEvent("PLAYER_ENTERING_WORLD")
	--in case of first call in combat
	ToggleAllBags()
	ToggleAllBags()
        ToggleFrame(CharacterFrame)
        ToggleFrame(CharacterFrame)
        ToggleCollectionsJournal()
        ToggleCollectionsJournal()
end)

local function CreateBD(f, a, s)
	f:SetBackdrop({
		bgFile = bdTex, edgeFile = glowTex, edgeSize = s or 4,
		insets = {left = s or 4, right = s or 4, top = s or 4, bottom = s or 4},
	})
	f:SetBackdropColor(0, 0, 0, a or 0.5)
	f:SetBackdropBorderColor(0, 0, 0)
end

local function CreateMM(f, t)
	f:SetSize(50, 50)
	f:SetFrameStrata("MEDIUM")
	f:SetBackdrop({bgFile = Media..t})
	f:SetBackdropColor(color.r, color.g, color.b, 1)
end

local function CreateMB(f, parent, w, h, x, y)
	f:SetSize(w, h)
	f:SetPoint("CENTER", parent, "CENTER", x, y)
	CreateBD(f, 1)
	f:SetFrameLevel(parent:GetFrameLevel() - 1)
	f:SetAlpha(0)
end

local function key(text, action)
	if GetBindingKey(action) then
		return text.." ("..GetBindingText(GetBindingKey(action))..")", color.r, color.g, color.b
	else
		return text, color.r, color.g, color.b
	end
end

local MB1 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB1:SetPoint("CENTER", MB, "CENTER", -24, 0)
CreateMM(MB1, "micro_player")
local MB1BG = CreateFrame("button", nil, MB1, "BackDropTemplate")
CreateMB(MB1BG, MB1, 35, 20, -6, 0)
MB1BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(key(CHARACTER_BUTTON, "TOGGLECHARACTER0"))
	GameTooltip:Show()
end)
MB1BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB1BG:SetScript("OnClick", function(self)
	ToggleFrame(CharacterFrame)
end)

local MB2 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB2:SetPoint("CENTER", MB, "CENTER", 2, 0)
CreateMM(MB2, "micro_spellbook")
local MB2BG = CreateFrame("button", nil, MB2, "BackDropTemplate")
CreateMB(MB2BG, MB2, 24, 20, 0, 0)
MB2BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(key(SPELLBOOK_ABILITIES_BUTTON, "TOGGLESPELLBOOK"))
	GameTooltip:Show()
end)
MB2BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
ToggleFrame(SpellBookFrame)	-- prevent taint
MB2BG:SetScript("OnClick", function(self)
	ToggleFrame(SpellBookFrame)
end)


local MB3 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB3:SetPoint("CENTER", MB, "CENTER", 28, 0)
CreateMM(MB3, "micro_talents")
local MB3BG = CreateFrame("button", nil, MB3, "BackDropTemplate")
CreateMB(MB3BG, MB3, 24, 20, 0, 0)
MB3BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(key(TALENTS_BUTTON, "TOGGLETALENTS"))
	GameTooltip:Show()
end)
MB3BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB3BG:SetScript("OnClick", function(self)
	if not PlayerTalentFrame then LoadAddOn("Blizzard_TalentUI") end
	if UnitLevel("player") < SHOW_SPEC_LEVEL then
		UIErrorsFrame:AddMessage(InfoColor..format(FEATURE_BECOMES_AVAILABLE_AT_LEVEL, SHOW_SPEC_LEVEL))
	else
		ToggleFrame(PlayerTalentFrame)
	end
end)

local MB4 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB4:SetPoint("CENTER", MB, "CENTER", 54, 0)
CreateMM(MB4, "micro_achievements")
local MB4BG = CreateFrame("button", nil, MB4, "BackDropTemplate")
CreateMB(MB4BG, MB4, 24, 20, 0, 0)
MB4BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(key(ACHIEVEMENT_BUTTON, "TOGGLEACHIEVEMENT"))
	GameTooltip:Show()
end)
MB4BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB4BG:SetScript("OnClick", function(self)
	ToggleAchievementFrame()
end)

local MB5 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB5:SetPoint("CENTER", MB, "CENTER", 80, 0)
CreateMM(MB5, "micro_quests")
local MB5BG = CreateFrame("button", nil, MB5, "BackDropTemplate")
CreateMB(MB5BG, MB5, 24, 20, 0, 0)
MB5BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(key(QUESTLOG_BUTTON, "TOGGLEQUESTLOG"))
	GameTooltip:Show()
end)
MB5BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB5BG:SetScript("OnClick", function(self)
	ToggleFrame(QuestLogFrame)
end)

local MB6 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB6:SetPoint("CENTER", MB, "CENTER", 106, 0)
CreateMM(MB6, "micro_guild")
local MB6BG = CreateFrame("button", nil, MB6, "BackDropTemplate")
CreateMB(MB6BG, MB6, 24, 20, 0, 0)
MB6BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(key(SOCIALS, "TOGGLESOCIAL"))
	GameTooltip:Show()
end)
MB6BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB6BG:SetScript("OnClick", function(self)
	ToggleFriendsFrame()
end)

local MB15 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB15:SetPoint("CENTER", MB, "CENTER", 158, 0)
CreateMM(MB15, "micro_collections")
local MB15BG = CreateFrame("button", nil, MB15, "BackDropTemplate")
CreateMB(MB15BG, MB15, 24, 20, 0, 0)
MB15BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(key(COLLECTIONS, "TOGGLECOLLECTIONS"))
	GameTooltip:Show()
end)
MB15BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB15BG:SetScript("OnClick", function(self)
	ToggleCollectionsJournal()
end)

local MB7 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB7:SetPoint("CENTER", MB, "CENTER", 132, 0)
CreateMM(MB7, "micro_pvp")
local MB7BG = CreateFrame("button", nil, MB7, "BackDropTemplate")
CreateMB(MB7BG, MB7, 24, 20, 0, 0)
MB7BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(key(PLAYER_V_PLAYER, "TOGGLECHARACTER4"))
	GameTooltip:Show()
end)
MB7BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB7BG:SetScript("OnClick", function(self)
	ToggleFrame(PVPParentFrame)
end)

local MB8 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB8:SetPoint("CENTER", MB, "CENTER", 184, 0)
CreateMM(MB8, "micro_LFD")
local MB8BG = CreateFrame("button", nil, MB8, "BackDropTemplate")
CreateMB(MB8BG, MB8, 24, 20, 0, 0)
MB8BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(key(DUNGEONS_BUTTON, "TOGGLEGROUPFINDER"))
	GameTooltip:Show()
end)
MB8BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB8BG:SetScript("OnClick", function(self)
	PVEFrame_ToggleFrame()
end)

local MB9 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB9:SetPoint("CENTER", MB, "CENTER", 210, 0)
CreateMM(MB9, "micro_encounter")
local MB9BG = CreateFrame("button", nil, MB9, "BackDropTemplate")
CreateMB(MB9BG, MB9, 24, 20, 0, 0)
MB9BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(key(WORLDMAP_BUTTON, "TOGGLEWORLDMAP"))
	GameTooltip:Show()
end)
MB9BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB9BG:SetScript("OnClick", function(self)
	ToggleFrame(WorldMapFrame)
end)

local MB12 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB12:SetPoint("CENTER", MB, "CENTER", 236, 0)
CreateMM(MB12, "micro_gm")
local MB12BG = CreateFrame("button", nil, MB12, "BackDropTemplate")
CreateMB(MB12BG, MB12, 24, 20, 0, 0)
MB12BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(HELP_BUTTON, color.r, color.g, color.b)
	GameTooltip:Show()
end)
MB12BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB12BG:SetScript("OnClick", function(self)
	ToggleFrame(HelpFrame)
end)

local MB13 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB13:SetPoint("CENTER", MB, "CENTER", 262, 0)
CreateMM(MB13, "micro_settings")
local MB13BG = CreateFrame("button", nil, MB13, "BackDropTemplate")
CreateMB(MB13BG, MB13, 24, 20, 0, 0)
MB13BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(MAIN_MENU, color.r, color.g, color.b)
	GameTooltip:Show()
end)
MB13BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB13BG:SetScript("OnClick", function(self)
	ToggleFrame(GameMenuFrame)
end)

local MB14 = CreateFrame("frame", nil, MB, "BackDropTemplate")
MB14:SetPoint("CENTER", MB, "CENTER", 299, 0)
CreateMM(MB14, "micro_bags")
local MB14BG = CreateFrame("button", nil, MB14, "BackDropTemplate")
CreateMB(MB14BG, MB14, 35, 20, -6, 0)
MB14BG:SetScript("OnEnter", function(self)
	self:SetAlpha(0.7)
	GameTooltip:SetOwner(self, 'ANCHOR_TOP')
	GameTooltip:AddLine(key(BAGSLOT, "OPENALLBAGS"))
	GameTooltip:Show()
end)
MB14BG:SetScript("OnLeave", function(self)
	GameTooltip:Hide()
	self:SetAlpha(0)
end)
MB14BG:SetScript("OnClick", function(self)
	ToggleAllBags()
end)
