local AddonName, a = ...
a.Localize = setmetatable({}, {__index = function(_, key) return key end})
local L = a.Localize

-- Example:
L["English text goes here."] = "Translated text goes here."

if GetLocale() == "ptBR" then -- Brazilian Portuguese
--L["Always show information on XP bar"] = ""
--L["Close this window to update the information."] = ""
--L["If enabled, numbers will be separated using a comma for easier reading."] = ""
--L["If unchecked, the information will only be visible when you move the cursor over the XP bar."] = ""
--L["Number Formatting"] = ""
--L["Show more information on XP bar"] = ""
--L["Show pet information on XP bar"] = ""
--L["use /xpt to access the configuration window."] = ""
elseif GetLocale() == "frFR" then -- French
L["Always show information on XP bar"] = "Toujours afficher les informations sur la barre d'expérience"
L["Close this window to update the information."] = "Fermez cette fenêtre pour mettre à jour les informations."
L["If enabled, numbers will be separated using a comma for easier reading."] = "Si cette option est activée, les numéros seront séparés par une virgule pour faciliter la lecture."
L["If unchecked, the information will only be visible when you move the cursor over the XP bar."] = "Si cette case n'est pas cochée, les informations ne seront visibles que si vous déplacez le curseur sur la barre d'expérience."
L["Number Formatting"] = "Formatage des nombres"
L["Show more information on XP bar"] = "Afficher plus d'informations sur la barre d'expérience"
L["Show pet information on XP bar"] = "Afficher des informations sur les animaux de compagnie sur la barre d'expérience"
L["use /xpt to access the configuration window."] = "utilisez /xpt pour accéder à la fenêtre de configuration."
elseif GetLocale() == "deDE" then -- German
L["Always show information on XP bar"] = "Informationen immer in der Erfahrungsleiste anzeigen"
L["Close this window to update the information."] = "Schließen Sie dieses Fenster, um die Informationen zu aktualisieren."
L["If enabled, numbers will be separated using a comma for easier reading."] = "Wenn diese Option aktiviert ist, werden Zahlen zur besseren Lesbarkeit durch ein Komma getrennt."
L["If unchecked, the information will only be visible when you move the cursor over the XP bar."] = "Wenn das Kontrollkästchen deaktiviert ist, werden die Informationen nur angezeigt, wenn Sie den Mauszeiger über die Erfahrungsleiste bewegen."
L["Number Formatting"] = "Zahlenformatierung"
L["Show more information on XP bar"] = "Zeigen Sie weitere Details in der Erlebnisleiste an"
L["Show pet information on XP bar"] = "Tierinformationen in der Erfahrungsleiste anzeigen"
L["use /xpt to access the configuration window."] = "verwenden sie /xpt um auf das Konfigurationsfenster zuzugreifen."
elseif GetLocale() == "itIT" then -- Italian
L["Always show information on XP bar"] = "Mostra sempre informazioni sulla barra dell'esperienza"
L["Close this window to update the information."] = "Chiudi questa finestra per aggiornare le informazioni."
L["If enabled, numbers will be separated using a comma for easier reading."] = "Se abilitato, i numeri saranno separati usando una virgola per facilitare la lettura."
L["If unchecked, the information will only be visible when you move the cursor over the XP bar."] = "Se deselezionato, le informazioni saranno visibili solo quando si sposta il cursore sulla barra dell'esperienza."
L["Number Formatting"] = "Formattazione numerica"
L["Show more information on XP bar"] = "Mostra maggiori informazioni sulla barra dell'esperienza"
L["Show pet information on XP bar"] = "Mostra le informazioni sugli animali domestici sulla barra dell'esperienza"
L["use /xpt to access the configuration window."] = "usa / xpt per accedere alla finestra di configurazione."
elseif GetLocale() == "koKR" then -- Korean
--L["Always show information on XP bar"] = ""
--L["Close this window to update the information."] = ""
--L["If enabled, numbers will be separated using a comma for easier reading."] = ""
--L["If unchecked, the information will only be visible when you move the cursor over the XP bar."] = ""
--L["Number Formatting"] = ""
--L["Show more information on XP bar"] = ""
--L["Show pet information on XP bar"] = ""
--L["use /xpt to access the configuration window."] = ""
elseif GetLocale() == "esMX" then -- Latin American Spanish
--L["Always show information on XP bar"] = ""
--L["Close this window to update the information."] = ""
--L["If enabled, numbers will be separated using a comma for easier reading."] = ""
--L["If unchecked, the information will only be visible when you move the cursor over the XP bar."] = ""
--L["Number Formatting"] = ""
--L["Show more information on XP bar"] = ""
--L["Show pet information on XP bar"] = ""
--L["use /xpt to access the configuration window."] = ""
elseif GetLocale() == "ruRU" then -- Russian
--L["Always show information on XP bar"] = ""
--L["Close this window to update the information."] = ""
--L["If enabled, numbers will be separated using a comma for easier reading."] = ""
--L["If unchecked, the information will only be visible when you move the cursor over the XP bar."] = ""
--L["Number Formatting"] = ""
--L["Show more information on XP bar"] = ""
--L["Show pet information on XP bar"] = ""
--L["use /xpt to access the configuration window."] = ""
elseif GetLocale() == "zhCN" then -- Simplified Chinese
--L["Always show information on XP bar"] = ""
--L["Close this window to update the information."] = ""
--L["If enabled, numbers will be separated using a comma for easier reading."] = ""
--L["If unchecked, the information will only be visible when you move the cursor over the XP bar."] = ""
--L["Number Formatting"] = ""
--L["Show more information on XP bar"] = ""
--L["Show pet information on XP bar"] = ""
--L["use /xpt to access the configuration window."] = ""
elseif GetLocale() == "esES" then -- Spanish
--L["Always show information on XP bar"] = ""
--L["Close this window to update the information."] = ""
--L["If enabled, numbers will be separated using a comma for easier reading."] = ""
--L["If unchecked, the information will only be visible when you move the cursor over the XP bar."] = ""
--L["Number Formatting"] = ""
--L["Show more information on XP bar"] = ""
--L["Show pet information on XP bar"] = ""
--L["use /xpt to access the configuration window."] = ""
elseif GetLocale() == "zhTW" then -- Traditional Chinese
--L["Always show information on XP bar"] = ""
--L["Close this window to update the information."] = ""
--L["If enabled, numbers will be separated using a comma for easier reading."] = ""
--L["If unchecked, the information will only be visible when you move the cursor over the XP bar."] = ""
--L["Number Formatting"] = ""
--L["Show more information on XP bar"] = ""
--L["Show pet information on XP bar"] = ""
--L["use /xpt to access the configuration window."] = ""
end