local ADDON = ...
local L = LibStub('AceLocale-3.0'):NewLocale(ADDON, 'enUS', true)
if not L then
    return
end
-- @locale:language=enUS@
L = L or {}
L["Active talent"] = true
L["Add socket"] = true
L["Bind with EquipmentSet"] = true
L["Character Gear"] = true
L["Character List"] = true
L["Clear Spec Equipment"] = true
L["Close character frame when inspect"] = true
L["Current realm characters"] = true
L["Data source:"] = true
L["Empty socket"] = true
L["Gear List"] = true
L["Help"] = true
L["HELP_SUMMARY"] = true
L["Hidden"] = true
L["iLvl:"] = true
L["Inspect Gear"] = true
L["Inspect mouseover"] = true
L["Inspect target"] = true
L["Item level color style"] = true
L["Last update:"] = true
L["Light"] = true
L["Low level characters"] = true
L["Major"] = true
L["Minor"] = true
L["No Enchant"] = true
L["Other realm characters"] = true
L["Quality by blizzard"] = true
L["See other account character?"] = true
L["Set alias name"] = true
L["Set Spec Equipment"] = true
L["Show character gear list"] = true
L["Show enchant"] = true
L["Show enchant for ranged weapon only for hunter"] = true
L["Show enchant/gem lost"] = true
L["Show gem"] = true
L["Show gems in front"] = true
L["Show inspect compare"] = true
L["Show inspect gear list"] = true
L["Show low level characters"] = true
L["Show option button in character gear list"] = true
L["Show option button in inspect gear list"] = true
L["Show talent background"] = true
L["Switch my characters"] = true
L["Switch talent"] = true
L["The key is bound to |cffffd100%s|r, are you sure you want to overwrite it?"] = true
L["View mouseover hotkey"] = true
L["View target hotkey"] = true
L["White"] = true
--@end-locale@]=]
--[[@debug@
-- @import:language=enUS@
L['Last update:'] = true
L['Data source:'] = true
L['Inspect target'] = true
L['Inspect mouseover'] = true
L['iLvl:'] = true
L['Show character gear list'] = true
L['Show inspect compare'] = true
L['Show inspect gear list'] = true
L['Show talent background'] = true
L.HELP_SUMMARY = true
L.Help = true
L['Show option button in character gear list'] = true
L['Show option button in inspect gear list'] = true
L['View mouseover hotkey'] = true
L['View target hotkey'] = true
L['The key is bound to |cffffd100%s|r, are you sure you want to overwrite it?'] = true
L['No Enchant'] = true
L['Empty socket'] = true
L['Show enchant'] = true
L['Show enchant/gem lost'] = true
L['Show gem'] = true
L['Add socket'] = true
L.Major = true
L.Minor = true
L['Show gems in front'] = true
L['Bind with EquipmentSet'] = true
L['Low level characters'] = true
L['Set Spec Equipment'] = true
L['Active talent'] = true
L['Switch my characters'] = true
L['Switch talent'] = true
L['Clear Spec Equipment'] = true
L['Close character frame when inspect'] = true
L['Character Gear'] = true
L['Gear List'] = true
L['Inspect Gear'] = true
L['Character List'] = true
L['Current realm characters'] = true
L['Other realm characters'] = true
L['See other account character?'] = true
L['Show low level characters'] = true
L['Item level color style'] = true
L.Light = true
L['Quality by blizzard'] = true
L.White = true
L.Hidden = true
L['Show enchant for ranged weapon only for hunter'] = true
L['Set alias name'] = true
-- @locale-fill@
-- @end-import@
--@end-debug@]]
