MINARCH_EXPANSION = 'Mainline'

-- uiMapIDs for continents [uiMapID] = internalContID
MinArchContIDMap = {
	[12] = 1, -- Kalimdor
	[13] = 2, -- EK
	[101] = 3, -- Outland
	[113] = 4, -- Northrend
	[948] = 5, -- Maelstrom
	[424] = 6, -- Pandaria
	[572] = 7, -- Draenor
	[619] = 8, -- Broken Isles
	[876] = 9, -- Kul Tiras
	[875] = 10, -- Zandalar
};

ARCHAEOLOGY_RACE_OTHER               = 0
ARCHAEOLOGY_RACE_DRUSTVARI           = 1
ARCHAEOLOGY_RACE_ZANDALARI           = 2
ARCHAEOLOGY_RACE_DEMONIC             = 3
ARCHAEOLOGY_RACE_HIGHMOUNTAIN_TAUREN = 4
ARCHAEOLOGY_RACE_HIGHBORNE           = 5
ARCHAEOLOGY_RACE_OGRE                = 6
ARCHAEOLOGY_RACE_DRAENOR             = 7
ARCHAEOLOGY_RACE_ARAKKOA             = 8
ARCHAEOLOGY_RACE_MOGU                = 9
ARCHAEOLOGY_RACE_PANDAREN            = 10
ARCHAEOLOGY_RACE_MANTID              = 11
ARCHAEOLOGY_RACE_VRYKUL              = 12
ARCHAEOLOGY_RACE_TROLL               = 13
ARCHAEOLOGY_RACE_TOLVIR              = 14
ARCHAEOLOGY_RACE_ORC                 = 15
ARCHAEOLOGY_RACE_NERUBIAN            = 16
ARCHAEOLOGY_RACE_NIGHTELF            = 17
ARCHAEOLOGY_RACE_FOSSIL              = 18
ARCHAEOLOGY_RACE_DRAENEI             = 19
ARCHAEOLOGY_RACE_DWARF               = 20

ARCHAEOLOGY_NUM_RACES                = 20
ARCHAEOLOGY_NUM_CONTINENTS           = 10
ARCHAEOLOGY_MAX_RANK				 = 950

MINARCH_MSG_STATUS = nil
MINARCH_MSG_DEBUG = 1

SURVEY_SPELL_ID = 80451

MINARCH_QSTATE_NIL = 0;
MINARCH_QSTATE_LEGION_AVAILABLE    = 1;
MINARCH_QSTATE_PRISTINE_INCOMPLETE = 2;
MINARCH_QSTATE_PRISTINE_ONQUEST    = 3;
MINARCH_QSTATE_PRISTINE_COMPLETE   = 4;

MINARCH_PROGRESS_UNKNOWN        = 0;
MINARCH_PROGRESS_KNOWN          = 1;
MINARCH_PROGRESS_CURRENT        = 2;
MINARCH_ACHIPROGRESS_NONE       = 3;
MINARCH_ACHIPROGRESS_INCOMPLETE = 4;
MINARCH_ACHIPROGRESS_COMPLETE   = 5;
