local LSM = LibStub("LibSharedMedia-3.0")

-- -----
-- BACKGROUND
-- -----

-- -----
-- BORDER
-- -----

-- -----
-- FONT
-- -----

-- -----
-- Rurutia
-- -----
LSM:Register("sound", "!FF-Aggro", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Aggro.mp3]])
LSM:Register("sound", "!FF-Change_Hotbar", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Change_Hotbar.mp3]])
LSM:Register("sound", "!FF-Confirm", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Confirm.mp3]])
LSM:Register("sound", "!FF-Enter_Chat", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Enter_Chat.mp3]])
LSM:Register("sound", "!FF-Enter_Instance", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Enter_Instance.mp3]])
LSM:Register("sound", "!FF-Error", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Error.mp3]])
LSM:Register("sound", "!FF-Feature_Unlocked", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Feature_Unlocked.mp3]])
LSM:Register("sound", "!FF-Full_Party", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Full_Party.mp3]])
LSM:Register("sound", "!FF-Incoming_Tell_1", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Incoming_Tell_1.mp3]])
LSM:Register("sound", "!FF-Incoming_Tell_2", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Incoming_Tell_2.mp3]])
LSM:Register("sound", "!FF-Incoming_Tell_3", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Incoming_Tell_3.mp3]])
LSM:Register("sound", "!FF-Level_Up", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Level_Up.mp3]])
LSM:Register("sound", "!FF-Limit_Break_Activated", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Limit_Break_Activated.mp3]])
LSM:Register("sound", "!FF-Limit_Break_Charged", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Limit_Break_Charged.mp3]])
LSM:Register("sound", "!FF-Limit_Break_Unlocked", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Limit_Break_Unlocked.mp3]])
LSM:Register("sound", "!FF-Linkshell_Transmission", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Linkshell_Transmission.mp3]])
LSM:Register("sound", "!FF-Notification", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Notification.mp3]])
LSM:Register("sound", "!FF-Open_Window", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Open_Window.mp3]])
LSM:Register("sound", "!FF-Register_Duty", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Register_Duty.mp3]])
LSM:Register("sound", "!FF-Remove_Item", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Remove_Item.mp3]])
LSM:Register("sound", "!FF-Switch_Target", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Switch_Target.mp3]])
LSM:Register("sound", "!FF-Untarget", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!FF-Untarget.mp3]])
LSM:Register("sound", "!IOS-即兴曲调", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!IOS-即兴曲调.ogg]])
LSM:Register("sound", "!IOS-哈喽", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!IOS-哈喽.ogg]])
LSM:Register("sound", "!IOS-完成", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!IOS-完成.ogg]])
LSM:Register("sound", "!IOS-火车鸣笛", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!IOS-火车鸣笛.ogg]])
LSM:Register("sound", "!IOS-竹子", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!IOS-竹子.ogg]])
LSM:Register("sound", "!IOS-脉冲", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!IOS-脉冲.ogg]])
LSM:Register("sound", "!IOS-鸟鸣声", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!IOS-鸟鸣声.ogg]])
LSM:Register("sound", "!MIUI-凌波微步", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!MIUI-凌波微步.ogg]])
LSM:Register("sound", "!MIUI-咕咚", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!MIUI-咕咚.ogg]])
LSM:Register("sound", "!MIUI-奇妙鼓点", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!MIUI-奇妙鼓点.ogg]])
LSM:Register("sound", "!MIUI-水滴", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!MIUI-水滴.ogg]])
LSM:Register("sound", "!MIUI-泡泡幻灭", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!MIUI-泡泡幻灭.ogg]])
LSM:Register("sound", "!MIUI-消失", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!MIUI-消失.ogg]])
LSM:Register("sound", "!MIUI-清爽", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!MIUI-清爽.ogg]])
LSM:Register("sound", "!MIUI-风铃", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!MIUI-风铃.ogg]])
LSM:Register("sound", "!SE-Ding1", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Ding1.ogg]])
LSM:Register("sound", "!SE-Ding2", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Ding2.ogg]])
LSM:Register("sound", "!SE-Ding3", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Ding3.ogg]])
LSM:Register("sound", "!SE-Ding4", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Ding4.ogg]])
LSM:Register("sound", "!SE-Ding5", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Ding5.ogg]])
LSM:Register("sound", "!SE-Ding6", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Ding6.ogg]])
LSM:Register("sound", "!SE-Ding7", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Ding7.ogg]])
LSM:Register("sound", "!SE-Ding8", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Ding8.ogg]])
LSM:Register("sound", "!SE-Ding9", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Ding9.ogg]])
LSM:Register("sound", "!SE-Pling1", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Pling1.ogg]])
LSM:Register("sound", "!SE-Pling2", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Pling2.ogg]])
LSM:Register("sound", "!SE-Pling3", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Pling3.ogg]])
LSM:Register("sound", "!SE-Pling4", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Pling4.ogg]])
LSM:Register("sound", "!SE-Pling5", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Pling5.ogg]])
LSM:Register("sound", "!SE-Pling6", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Pling6.ogg]])
LSM:Register("sound", "!SE-Whisper", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!SE-Whisper.ogg]])
LSM:Register("sound", "!Wind-OnePlusLight", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!Wind-OnePlusLight.ogg]])
LSM:Register("sound", "!Wind-OnePlusSurprise", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\!Wind-OnePlusSurprise.ogg]])
LSM:Register("sound", "【露露1】1", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】1.ogg]])
LSM:Register("sound", "【露露2】2", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】2.ogg]])
LSM:Register("sound", "【露露3】3", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】3.ogg]])
LSM:Register("sound", "【露露3】3连减伤", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】3连减伤.ogg]])
LSM:Register("sound", "【露露4】4", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】4.ogg]])
LSM:Register("sound", "【露露5】5", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】5.ogg]])
LSM:Register("sound", "【露露5】5码分散", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】5码分散.ogg]])
LSM:Register("sound", "【露露6】6连减伤", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】6连减伤.ogg]])
LSM:Register("sound", "【露露B】Bingo", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】Bingo.ogg]])
LSM:Register("sound", "【露露B】BIU", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】BIU.ogg]])
LSM:Register("sound", "【露露B】BOSS强化", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】BOSS强化.ogg]])
LSM:Register("sound", "【露露I】Info", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】Info.ogg]])
LSM:Register("sound", "【露露S】SE01", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】SE01.ogg]])
LSM:Register("sound", "【露露S】SE02", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】SE02.ogg]])
LSM:Register("sound", "【露露S】SE03", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】SE03.ogg]])
LSM:Register("sound", "【露露S】SE04", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】SE04.ogg]])
LSM:Register("sound", "【露露S】SE05", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】SE05.ogg]])
LSM:Register("sound", "【露露S】SE06", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】SE06.ogg]])
LSM:Register("sound", "【露露S】SE07", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】SE07.ogg]])
LSM:Register("sound", "【露露S】Sonar", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】Sonar.ogg]])
LSM:Register("sound", "【露露W】Warning", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】Warning.ogg]])
LSM:Register("sound", "【露露S】三阶段准备", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】三阶段准备.ogg]])
LSM:Register("sound", "【露露E】二阶段准备", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】二阶段准备.ogg]])
LSM:Register("sound", "【露露N】你被易伤", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】你被易伤.ogg]])
LSM:Register("sound", "【露露N】你被点名", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】你被点名.ogg]])
LSM:Register("sound", "【露露S】使用道具", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】使用道具.ogg]])
LSM:Register("sound", "【露露T】停止攻击", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】停止攻击.ogg]])
LSM:Register("sound", "【露露B】冰墓点名", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】冰墓点名.ogg]])
LSM:Register("sound", "【露露B】冰霜阶段", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】冰霜阶段.ogg]])
LSM:Register("sound", "【露露C】冲击波点你", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】冲击波点你.ogg]])
LSM:Register("sound", "【露露C】冲锋点你", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】冲锋点你.ogg]])
LSM:Register("sound", "【露露Z】准备AOE", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】准备AOE.ogg]])
LSM:Register("sound", "【露露Z】准备传球", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】准备传球.ogg]])
LSM:Register("sound", "【露露Z】准备侧翻", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】准备侧翻.ogg]])
LSM:Register("sound", "【露露Z】准备分散", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】准备分散.ogg]])
LSM:Register("sound", "【露露Z】准备吐息", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】准备吐息.ogg]])
LSM:Register("sound", "【露露Z】准备投掷", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】准备投掷.ogg]])
LSM:Register("sound", "【露露Z】准备挡线", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】准备挡线.ogg]])
LSM:Register("sound", "【露露Z】准备集合", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】准备集合.ogg]])
LSM:Register("sound", "【露露C】出人群驱散", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】出人群驱散.ogg]])
LSM:Register("sound", "【露露D】叮咚", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】叮咚.ogg]])
LSM:Register("sound", "【露露Y】右侧翻", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】右侧翻.ogg]])
LSM:Register("sound", "【露露C】吃大餐咯~", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】吃大餐咯~.ogg]])
LSM:Register("sound", "【露露T】坦克减伤", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】坦克减伤.ogg]])
LSM:Register("sound", "【露露A】安全安全", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】安全安全.ogg]])
LSM:Register("sound", "【露露D】定身", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】定身.ogg]])
LSM:Register("sound", "【露露J】寄生虫点名", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】寄生虫点名.ogg]])
LSM:Register("sound", "【露露X】小心头前", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】小心头前.ogg]])
LSM:Register("sound", "【露露X】小心脚下", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】小心脚下.ogg]])
LSM:Register("sound", "【露露X】小心践踏", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】小心践踏.ogg]])
LSM:Register("sound", "【露露X】小怪刷新", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】小怪刷新.ogg]])
LSM:Register("sound", "【露露C】层数过高", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】层数过高.ogg]])
LSM:Register("sound", "【露露Z】左侧翻", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】左侧翻.ogg]])
LSM:Register("sound", "【露露K】快出内场", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快出内场.ogg]])
LSM:Register("sound", "【露露K】快打寄生虫", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快打寄生虫.ogg]])
LSM:Register("sound", "【露露K】快打工兵", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快打工兵.ogg]])
LSM:Register("sound", "【露露K】快打断", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快打断.ogg]])
LSM:Register("sound", "【露露K】快打源质箭", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快打源质箭.ogg]])
LSM:Register("sound", "【露露K】快打肌腱", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快打肌腱.ogg]])
LSM:Register("sound", "【露露K】快找掩体", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快找掩体.ogg]])
LSM:Register("sound", "【露露K】快找风眼", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快找风眼.ogg]])
LSM:Register("sound", "【露露K】快跑哟", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快跑哟.ogg]])
LSM:Register("sound", "【露露K】快躲开", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快躲开.ogg]])
LSM:Register("sound", "【露露K】快转火", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快转火.ogg]])
LSM:Register("sound", "【露露K】快集合", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】快集合.ogg]])
LSM:Register("sound", "【露露J】救那个倒霉蛋！", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】救那个倒霉蛋！.ogg]])
LSM:Register("sound", "【露露H】昏迷", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】昏迷.ogg]])
LSM:Register("sound", "【露露Y】易伤结束", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】易伤结束.ogg]])
LSM:Register("sound", "【露露Y】易伤阶段", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】易伤阶段.ogg]])
LSM:Register("sound", "【露露A】暗淡点你", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】暗淡点你.ogg]])
LSM:Register("sound", "【露露Z】注意分散", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】注意分散.ogg]])
LSM:Register("sound", "【露露Z】注意吐息", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】注意吐息.ogg]])
LSM:Register("sound", "【露露Z】注意治疗", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】注意治疗.ogg]])
LSM:Register("sound", "【露露Z】注意点名", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】注意点名.ogg]])
LSM:Register("sound", "【露露Y】源质箭准备", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】源质箭准备.ogg]])
LSM:Register("sound", "【露露M】目标是你", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】目标是你.ogg]])
LSM:Register("sound", "【露露D】第1阶段", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】第1阶段.ogg]])
LSM:Register("sound", "【露露D】第2阶段", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】第2阶段.ogg]])
LSM:Register("sound", "【露露N】能量过低", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】能量过低.ogg]])
LSM:Register("sound", "【露露N】能量过高", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】能量过高.ogg]])
LSM:Register("sound", "【露露J】脚下集合", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】脚下集合.ogg]])
LSM:Register("sound", "【露露J】解散宝宝", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】解散宝宝.ogg]])
LSM:Register("sound", "【露露T】跳跳跳", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】跳跳跳.ogg]])
LSM:Register("sound", "【露露Y】远离BOSS", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】远离BOSS.ogg]])
LSM:Register("sound", "【露露Y】远离人群", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】远离人群.ogg]])
LSM:Register("sound", "【露露S】闪电阶段", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】闪电阶段.ogg]])
LSM:Register("sound", "【露露J】阶段转换", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】阶段转换.ogg]])
LSM:Register("sound", "【露露J】集合分摊", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】集合分摊.ogg]])
LSM:Register("sound", "【露露K】靠近坦克", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】靠近坦克.ogg]])
LSM:Register("sound", "【露露F】风筝BOSS", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】风筝BOSS.ogg]])
LSM:Register("sound", "【露露G】高达点名", [[Interface\Addons\SharedMedia_Rurutia\Rurutia\【露露】高达点名.ogg]])

-- -----
-- Rurutia_Common
-- -----

-- -----
-- STATUSBAR
-- -----
LSM:Register("statusbar", "!Rurutia01", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia01.tga]])
LSM:Register("statusbar", "!Rurutia02", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia02.tga]])
LSM:Register("statusbar", "!Rurutia03", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia03.tga]])
LSM:Register("statusbar", "!Rurutia04", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia04.tga]])
LSM:Register("statusbar", "!Rurutia05", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia05.tga]])
LSM:Register("statusbar", "!Rurutia06", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia06.tga]])
LSM:Register("statusbar", "!Rurutia07", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia07.tga]])
LSM:Register("statusbar", "!Rurutia08", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia08.tga]])
LSM:Register("statusbar", "!Rurutia09", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia09.tga]])
LSM:Register("statusbar", "!Rurutia10", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia10.tga]])
LSM:Register("statusbar", "!Rurutia11", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia11.tga]])
LSM:Register("statusbar", "!Rurutia12", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia12.tga]])
LSM:Register("statusbar", "!Rurutia13", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia13.tga]])
LSM:Register("statusbar", "!Rurutia14", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia14.tga]])
LSM:Register("statusbar", "!Rurutia15", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia15.tga]])
LSM:Register("statusbar", "!Rurutia16", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia16.tga]])
LSM:Register("statusbar", "!Rurutia17", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia17.tga]])
LSM:Register("statusbar", "!Rurutia18", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia18.tga]])
LSM:Register("statusbar", "!Rurutia19", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia19.tga]])
LSM:Register("statusbar", "!Rurutia20", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia20.tga]])
LSM:Register("statusbar", "!Rurutia21", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia21.tga]])
LSM:Register("statusbar", "!Rurutia22", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia22.tga]])
LSM:Register("statusbar", "!Rurutia23", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia23.tga]])
LSM:Register("statusbar", "!Rurutia24", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia24.tga]])
LSM:Register("statusbar", "!Rurutia25", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia25.tga]])
LSM:Register("statusbar", "!Rurutia26", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia26.tga]])
LSM:Register("statusbar", "!Rurutia27", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia27.tga]])
LSM:Register("statusbar", "!Rurutia28", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia28.tga]])
LSM:Register("statusbar", "!Rurutia29", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia29.tga]])
LSM:Register("statusbar", "!Rurutia_Half01", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia_Half01.tga]])
LSM:Register("statusbar", "!Rurutia_Half02", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia_Half02.tga]])
LSM:Register("statusbar", "!Rurutia_Half03", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia_Half03.tga]])
LSM:Register("statusbar", "!Rurutia_Half04", [[Interface\Addons\SharedMedia_Rurutia\statusbar\!Rurutia_Half04.tga]])
