
local L = LibStub('AceLocale-3.0'):NewLocale('tdAuction', 'deDE')
if not L then return end

L["Always"] = "Immer"
L["Auction price"] = "Auktionspreis"
L["Auto open price list"] = "Preisliste automatisch öffnen"
L["Bid price"] = "Gebot"
L["Choose other price"] = "Anderen Preis wählen"
L["Clear database"] = "Datenbank leeren"
L["Count"] = "Anzahl"
L["Database"] = "Datenbank"
L["Default auction duration"] = "Standardwert für Auktionslänge"
L["Default stack size"] = "Standardtwert für Stapelgröße"
L["Disenchant price"] = "Entzauberungspreis"
--[[Translation missing --]]
--[[ L["Duration no deposit"] = ""--]] 
L["Enable ALT to sell"] = "Aktiviere ALT zum verkaufen"
L["Enable ALT-CTRL click to buyout"] = "Aktiviere ALT-STRG zum kaufen"
L["Full"] = "Voll"
L["Full scan"] = "Vollständiger Scan"
L["Full scaning, elapsed time: %s"] = "Vollständiger Scan, verstrichene Zeit: %s"
L["Ignore"] = "Ignorieren"
L["in about %s"] = "in etwa %s"
L["Merchant price"] = "Händlerpreis"
L["Nerver"] = "Niemals"
L["New"] = "Neu"
L["Next available time:"] = "Nächste verfügbare Zeit:"
L["No price"] = "Kein Preis"
L["Now"] = "Jetzt"
L["Pressed SHIFT"] = "Wenn SHIFT gedrückt"
L["Price"] = "Preis"
L["Processing data, elapsed time: %s"] = "Verarbeite Daten, verstrichene Zeit: %s"
L["Scan all"] = "Alles scannen"
L["Scan one page"] = "Eine Seite scannen"
L["Scan price mode"] = "Preisscan Modus"
L["Show disenchant info"] = "Zeige Entzauberungsinfo"
L["Single price"] = "Einzelpreis"
L["Start auction:"] = "Auktion starten:"
L["Start price discount"] = "Startpreis Rabatt"
L["Start scan"] = "Scan starten"
L["Time"] = "Zeit"
L["Tooltip"] = true
L["TOOLTIP_PREFIX_AUCTION"] = "Auktion"
L["TOOLTIP_PREFIX_DISENCHANT"] = "Entzaubern"
L["TOOLTIP_PREFIX_VENDO"] = "Händler"
L["Total price"] = "Gesamtpreis"
L["Unit price"] = "Stückpreis"
L["Unknown"] = "Unbekannt"
L["Update"] = "Aktualisieren"
L["Use history price"] = "Verwende historischen Preis"
L["Use merchant price x%d"] = "Verwende Händlerpreis x%d"
L["When no price, use merchant price multiply by"] = "Falls kein Preis verfügbar, verwende Händlerpreis multipliziert mit"
L["When pressed SHIFT, to dislay ..."] = "Wenn SHIFT gedrückt, zeige..."
L["You are sure to clear the database"] = "Bist du sicher, dass du die Datenbank leeren willst?"

