local GSE = GSE
local Statics = GSE.Static

Statics.Patrons = {
    "!Ceccil",
    "'William Meringolo",
    "..",
    "1990Causer",
    "1Silly Gooose78",
    "3333333333",
    "900obzen ",
    "A Four",
    "A G",
    "AJ Guckian",
    "AL",
    "ALKHAMIS",
    "ARTEX",
    "ATS",
    "Aabukim",
    "Aamir Shakir",
    "Aaron",
    "Aaron Clark",
    "Aaron Halpin",
    "Aaron Rhodes",
    "Aaron Smith",
    "Aaron Steley",
    "Acromion",
    "Adaestra ",
    "Adam",
    "Adam Anderson",
    "Adam Doherty",
    "Adam Fisher",
    "Adam Robinson",
    "Adam Smith",
    "Adam Tall",
    "Adrian Cornelius",
    "Adrian Maier",
    "Adriana Novakova",
    "Adriano Macinkovic",
    "Adventures Of Raven",
    "Aerrek",
    "Aiden Gramson",
    "Akk",
    "Akos",
    "Alan Davis",
    "Alastorm",
    "Alejandro Sanclemente",
    "Aleksej",
    "Alex",
    "Alex",
    "Alex Branch",
    "Alex Branch",
    "Alex Gudgeon",
    "Alex McLaren",
    "Alex Omusoru",
    "Alexander Verrecchia",
    "Alexis Benton",
    "Alexis85",
    "Alfonso",
    "Alfred Green",
    "Allan Korsgaard",
    "Allan Smith Nielsen",
    "Allan Sørup Korsgaard",
    "Allbeef",
    "Allen Ponce",
    "Alvaro Sanchez",
    "Aman Braich",
    "Amanda Smith",
    "Andre Carbonell",
    "Andrea Carturan",
    "Andrea Rossi",
    "Andrew",
    "Andrew Baldwin",
    "Andrew Fox",
    "Andrew Hodgson",
    "Andrew Lester",
    "Andrew Medina",
    "Andrew VanArman",
    "Andrew lundquist",
    "Andris Kulmans",
    "Andy Ashes",
    "Andy Dalmat",
    "Andy Erickson",
    "Andy Kybett",
    "Angel Marchini",
    "Angrypug",
    "AnjosRodrigo",
    "Anna Göransson",
    "Anonyme",
    "Anthony",
    "Anthony King",
    "Anthony Welch",
    "Anthony0396",
    "Antithesis OvO",
    "Antonio Zahra",
    "Antti Rautio",
    "Anubikk ",
    "Arild Moen",
    "Arne Krüger",
    "Arno Body",
    "Arnold E newton",
    "Arynoyn",
    "Ashley",
    "Ashley Ludwig",
    "Ashneel Kumar",
    "Ashvin Chutkay",
    "Ashwalker ",
    "Austen Way",
    "Austin Crain",
    "Auto",
    "Axel Schwania",
    "Axellis ",
    "Aydın",
    "B Menees",
    "B Whitcombe",
    "B43lzebub",
    "BAO D LE",
    "BC",
    "BFMVmetalA7X .",
    "BRIAN V DELLER",
    "Baely ",
    "Bahaga",
    "Baka Pixel",
    "Bandito69",
    "Barbosa",
    "Baz Train",
    "Bean",
    "Bear",
    "Bearded_Gamer ",
    "Beardedadbod",
    "Becan",
    "Bella RH",
    "Ben Hocking",
    "Ben McBryde",
    "Ben Stage",
    "Bengt Grahl",
    "Benjamin Gallay",
    "Benjamin T.",
    "Benjamin litty",
    "Bennie Moses",
    "Bennyfof",
    "Betsi Boombasket",
    "Bghy Rbfch",
    "BigPoppaRich",
    "Big_Al",
    "Bigwuflow ",
    "Bill Bowker",
    "Bill Heathrow",
    "Bill coonelly",
    "Billy",
    "Binary Nick",
    "Binnie Cook",
    "Bitto",
    "Biyanshi",
    "Bizzle",
    "Bleukar of Quel'dorei",
    "Blizz",
    "Bloodgrv GHG3D",
    "Blub an",
    "Bluee Yang",
    "Bob",
    "Bob",
    "Bob Pieters",
    "Bobbi Queen",
    "Bobbll´s Kanal",
    "Bobby Edrich",
    "BobbyTwoHands ",
    "Bodo Wiese",
    "Body Bagz",
    "Bolt",
    "Bonch",
    "Boris Schüler",
    "Bowdacious ",
    "Brad ",
    "Bragorc",
    "Brandon Angrisano",
    "Brandon Bks",
    "Brandon Conklin",
    "Brandon Crose",
    "Brandon Ellis",
    "Brandon Henry",
    "Brandon Henry",
    "Brandon Hill",
    "Bree",
    "Bree",
    "Brendan Ellis",
    "Brett Beaumont",
    "Brett Warfle",
    "Brian",
    "Brian Dickerson",
    "Brian Lewin",
    "Brian Lynch",
    "Brian Miller",
    "Brian Rud Sørensen",
    "Brickshots",
    "Bruce Wardle",
    "Bryan Burns",
    "Bryan Seitz",
    "Bryce Carr",
    "Bubonix",
    "Burt Reynolds",
    "Bxnane",
    "C",
    "CAN OZAN",
    "CC TSAO",
    "Cabiria-Il-Notte ",
    "Calvin Jones",
    "Calvin Jones",
    "Camaraderie ",
    "CapSisko ",
    "Carl Williams",
    "Carlos Alberto Arizpe Mendoza",
    "Carpe Somnia",
    "Carter Cross",
    "Cass",
    "Cassio Almeida",
    "Cdub3n",
    "Cele",
    "Cernios",
    "Chack Chack",
    "Chance",
    "Charles",
    "Charles R Tabor",
    "Chase Hoppock",
    "Chele",
    "Chew",
    "Chiccaa",
    "China MagicalRealism",
    "Choco Munday",
    "Chris",
    "Chris",
    "Chris Barsalou",
    "Chris Bunting",
    "Chris Cordwell",
    "Chris Esparza",
    "Chris G",
    "Chris Hynes",
    "Chris Jackson",
    "Chris Juengel",
    "Chris L",
    "Chris Livingston",
    "Chris Mills",
    "Chris Reynolds",
    "Chris S",
    "Chris Williams",
    "Chris Wunner",
    "Christian Mostert",
    "Christine Berger",
    "Christopher Fennell",
    "Christopher Lee",
    "Christopher Reed",
    "Christopher Young",
    "Christos ",
    "Chumao",
    "Cindy Stuckey",
    "Clayton Johnson",
    "Cliff",
    "Clinton Hennig",
    "Codda Matl",
    "CoffeeTime",
    "Colby Rooker",
    "ColdFish",
    "Coldghost",
    "Colm",
    "Consors",
    "Constantin Martini",
    "Constantin Stoian",
    "Copy",
    "Corey Marchant",
    "Corey Tresnak",
    "Cosmos46",
    "Cought",
    "Country Creations",
    "CrankBootyTV",
    "Crispy",
    "Cruelier",
    "Crygon",
    "Csaba Cimpan",
    "Cuandur",
    "Curtis buckland jr",
    "Cåuchemar",
    "D B",
    "D C",
    "DENNIS CHRISTENSEN",
    "DERP",
    "DJ",
    "DJ_FingaGunz",
    "DMFerree",
    "Dagul Magul",
    "Daknar",
    "Dallas Mcnab",
    "Damien Askey",
    "Damion Thomas",
    "Damon Walker",
    "Dan",
    "Dan Inda",
    "Dan Schmidt",
    "Daniel Clements",
    "Daniel Friberg",
    "Daniel Gabriele",
    "Daniel Girgsdies",
    "Daniel Kristiansson",
    "Daniel Kristofersson",
    "Daniel Lange",
    "Daniel Lythgoe",
    "Daniel Martin",
    "Daniel Mendez",
    "Daniel Perez",
    "Daniel Sümmchen",
    "Daniel Thomas",
    "Dark Box",
    "Darkane",
    "Darren Parkin",
    "Darroll Howard",
    "Dave Gordon",
    "Dave Jones",
    "Dave Sonne",
    "Dave Staggs",
    "David A Bell",
    "David Casey",
    "David Isburgh",
    "David Johansson",
    "David Pennington",
    "David Rice",
    "David Rose",
    "David Simoes",
    "David Thrower",
    "David Toms",
    "David Wagner",
    "David Wilson",
    "David Young",
    "Davis Campos",
    "Dean Fonos",
    "Deborah Gough",
    "Deezyl Fizzlepop",
    "DeiwiZzZ J",
    "Dejuan Taylor",
    "Demondotz",
    "Denis Samoilov",
    "Dennis Batty",
    "Deranged Hermit",
    "Derek Lauzon",
    "Derik B Casper",
    "Derrick Puckett",
    "Devin Blair",
    "Devon Stayt",
    "Dex",
    "DezGaming",
    "Diedora",
    "Diesel",
    "Dieter Cazon",
    "Dietmar Staudacher",
    "DieuCrow ",
    "Dimitris Lentzos",
    "Dirk Dill",
    "Dirk Kowalski",
    "Dirty Apparition",
    "Dominik Krabacher",
    "Donald Bertelsen",
    "Donald Easter",
    "Donnie Spencer",
    "DoodlyDoodle",
    "Doug Miers",
    "Douglas Petronis",
    "Douglas Schlemper",
    "Dradran",
    "Drahgunfyre",
    "Drake Aedus",
    "Dre Dodd",
    "Dredd",
    "Drew Jackson",
    "Drioz",
    "Drix",
    "Drunk Gaming",
    "Dude Guy",
    "Dummy Test",
    "Durron1337",
    "Dustin Davenport",
    "Dustin Gadd",
    "Dustin W",
    "Dylan Warner",
    "E Peters",
    "EasyFrost",
    "Ecthal (Dalaran)",
    "Ed E",
    "Edgar Dazevedo",
    "Edmond",
    "Eduard Claassen",
    "Eduardo Lima",
    "Edwan",
    "Edwan Silva",
    "Edward Yanke",
    "Ejner",
    "Elange4 ",
    "ElderGod Games",
    "ElementNine",
    "Elfyau",
    "Elgador",
    "Eli Sapanayev",
    "Ellië Warcraft",
    "Emannuel ",
    "Emanuel Barbi",
    "Emo Mihov",
    "Enmity",
    "Envoy",
    "Epix Winner",
    "Eric D B",
    "Eric Desmarais",
    "Eric Donini",
    "Eric Hammersley",
    "Eric Kerzman",
    "Eric Matherne",
    "Eric Rainey",
    "Eric Roberts",
    "Eric Sanders",
    "Eric Stoeckel Jr",
    "Eric Vasquez",
    "Eric Vincent",
    "Eric donini",
    "Erich Herbert",
    "Erik Heiland",
    "Erin Reymann",
    "Ernst Lukas",
    "Euben Hadd",
    "Even",
    "Even",
    "Everett St.Clair",
    "Excutive Outcome game",
    "Eznoda",
    "Eznoda",
    "FERDIN GONZALEZ",
    "FPSMarcus",
    "FUT_Sovereign ",
    "Fabian Maier",
    "FaderBog",
    "Fadeshape",
    "Fadi Alfadda",
    "Fahad Khamis",
    "Faisal Siddiqui",
    "Fallenangel 5869",
    "Fallens Death",
    "Fangorian_1337",
    "Fariz Adnan",
    "Fatality",
    "Fed",
    "Felipe Colombino",
    "Fenrir",
    "Ferat A",
    "Feros Uchiki",
    "First Last",
    "Fischi",
    "Florin Enache",
    "Flávio Jerónimo",
    "Francisco Fernandez",
    "Frank DeLeon",
    "Frank Opitz",
    "Frank Wheeler",
    "Frank franz",
    "Frankie Lee",
    "FreakyDeaky",
    "Fredrik Feros Haugli",
    "Freeyae ",
    "Frighten_bees",
    "Fumbles518 ",
    "Futz0r",
    "FyuZ. ",
    "Gabriel Ramos",
    "Gaimon Chris",
    "GamingMama56",
    "Gary",
    "Gary Markland",
    "Gary Mills",
    "Gary W Hiddle",
    "Gaël Daire",
    "Gddmitspiros",
    "GenTsoCkn ",
    "Gendi",
    "Geoff Weinhold",
    "Geoffrey Tang",
    "George B",
    "George McCubbins",
    "Gerald McCandless",
    "Gerardo Oduber",
    "Gianluca Berian",
    "Gianpiero Gaio",
    "Gilbert Mejia",
    "Gilbert Mejia",
    "Gilian Bentulan",
    "Glenn van Kooijk",
    "Glock",
    "Goregoth",
    "Graf288",
    "Grandpa",
    "Grayson Roberts",
    "Greg Schmitz",
    "Gregory ",
    "Gregory M",
    "Grifter",
    "Grim",
    "Grumpy British old Gamer",
    "Gunnar Norgren",
    "Gustav Gans",
    "Gutitout",
    "Gzod",
    "Gấu Panda",
    "HAO LEI",
    "HOLLIS FORD",
    "Haksung kim",
    "Hamilton Foro",
    "Hampton Albert",
    "Hannah Mae",
    "Hansli Peterli",
    "Hayden Dee",
    "Hayden Willis",
    "Helder Fernandes",
    "Henrik Nielsen",
    "Henrique Ribeiro",
    "Herbert Besenfelder",
    "Herman Graute",
    "Hervé Coatanhay",
    "Holger",
    "Holger Schwania",
    "Holli Mcmillen",
    "Hollis Ford",
    "Holy",
    "HomeMobileEmail",
    "Hong Shang",
    "Horologist",
    "Horst Bauer",
    "Hugh Judd",
    "Hunka",
    "Hykren ",
    "INTIAMAUTA",
    "Idkjust4f",
    "Igel",
    "Illandren ",
    "Indigo Prophet",
    "Indomitus B",
    "Inga Palatova",
    "Ingemar Axelsson",
    "Injunction",
    "Iphone Concept",
    "Isaiah Lombardy",
    "Ivan Chiu",
    "Ivan Moucha",
    "J B",
    "J B",
    "J G",
    "JIA GUO",
    "JIMA JONES",
    "JON",
    "JWBGames",
    "Jacek Paslawski",
    "Jacek Pasławski",
    "Jack",
    "Jack Etienne",
    "Jack Selektion",
    "Jacob Richey",
    "Jacqu Eline",
    "Jajads",
    "Jake ",
    "Jake Alan",
    "Jakke Suominen",
    "Jakob Andersen",
    "James",
    "James Beck",
    "James Blamey",
    "James Brown",
    "James Duncan",
    "James Faircloth",
    "James Fortier",
    "James King",
    "James Mason",
    "James Turnbull",
    "James Webster",
    "Jamie Currier",
    "Jamie Gordon",
    "Jamie Mulero",
    "Jani Kay",
    "Jarl tore mellem",
    "JarrTET",
    "Jason ",
    "Jason B.",
    "Jason Cartledge",
    "Jason Driver",
    "Jason Johnson",
    "Jason Kartes",
    "Jasper Hengefeld",
    "Javier Navarro",
    "Jaxx",
    "Jay  Gomez",
    "Jay Jay",
    "Jay Ranson",
    "Jayson Isaacs",
    "Jean-Philippe Baril",
    "Jed Lawton",
    "Jeff Berman",
    "Jeff Butler",
    "Jeff Hinga",
    "Jeff Hughes",
    "Jeff Powell",
    "Jefferson Pascoal",
    "Jeffrey Belcher",
    "Jeffrey Daniels",
    "Jeffrey White",
    "Jennifer Angelidis",
    "Jenny ",
    "Jens Schulze",
    "Jens Wehking",
    "Jeppe Becker",
    "Jeremi Walker",
    "Jeremy",
    "Jeremy ",
    "Jeremy Duncan",
    "Jeremy Grayson",
    "Jeremy Harvey",
    "Jeremy Hinkle",
    "Jeremy Jones",
    "Jeremy Jones",
    "Jeremy MccAll",
    "Jeremy Neumann",
    "Jeremy Ockander",
    "Jeroen Bakker",
    "Jerrod Linderman",
    "Jerry Sutton",
    "Jerry T",
    "Jesper Holmlund Jørgensen",
    "Jesse",
    "Jesse Davis",
    "Jessica",
    "Jf Boubou",
    "Jim",
    "Jim B",
    "Jim Pinson",
    "Jim Weaver",
    "Jimmy Tuvebrant",
    "Jimrummy",
    "Jinazz",
    "Jion Kim",
    "Jodi Meese",
    "Jody Gemzik",
    "Joe Bowen",
    "Joe Bromeland",
    "Joe Davis",
    "Joe Dinsmore",
    "Joe Jackson",
    "Joe Liu",
    "Joe Newitt",
    "Joe Shmoe",
    "Joe.D ",
    "Joel D Bailey",
    "Joetrio",
    "Johan Andersson",
    "Johan Lindqvist",
    "Johan wennerström",
    "Johannes Frei",
    "John",
    "John",
    "John",
    "John Adams",
    "John Balk",
    "John Beland",
    "John Caylor",
    "John Clem",
    "John D Aulbu",
    "John Hoskin",
    "John Martin",
    "John Rose",
    "John Shelton",
    "John Weeast",
    "John smith",
    "Johnnie Rigsby",
    "Johnny Fotschky",
    "Joker",
    "Jon Blam",
    "Jon Leuck",
    "Jon Noland",
    "Jon Waalewyn",
    "Jonathan",
    "Jonathan Abucejo",
    "Jonathan Devore Scales",
    "Jonathan Krizek",
    "Jonathan Wilson",
    "Jonathan leal",
    "Jonathon Finlay",
    "Jordan Feller",
    "Jordan Owen-O'Neill",
    "Joseph Atkins",
    "Joseph Barber",
    "Joseph Lowery",
    "Josh Green",
    "Josh Silvia",
    "Josh wilkerson",
    "Joshua Allen",
    "Joshua Croffet",
    "Joshua J. Edgell",
    "Joshua Sawyer",
    "Joshua Stevens",
    "Joshua Thurman",
    "Joshua nelson",
    "José Carlos Pérez Carreño",
    "João Freitas",
    "João Paulo Souza",
    "Jpow",
    "Juan Jose Anton alcantara",
    "Juberias",
    "Jude Mazur",
    "Juka",
    "Julien Knauff",
    "JumpyWizzard",
    "Junior Rodriguez",
    "Justin",
    "Justin Boldra",
    "Justin Robertson",
    "Justin Shaffner",
    "Justin Smith",
    "Justin Vaughn",
    "Justin3121",
    "K",
    "K",
    "K J",
    "KIM DONG MIN",
    "KJ",
    "KURT MOSS",
    "Kahoots",
    "Kai Geheb",
    "Kakka",
    "Kal basra",
    "Kaleb Shaw",
    "Kamil Kosior",
    "Kanadian",
    "Kapp",
    "Karl Clinton Wells",
    "Karl gregory",
    "KarmaBurst",
    "Karoldue ",
    "Karsten Hansen",
    "Kayahan Kaya",
    "Keith Fults",
    "Keith Kelly",
    "Keldrog",
    "Kelton Nickerson",
    "Kemal Tolun",
    "Ken McCune",
    "Ken Poleshuck",
    "Kenny Pritchard",
    "Kent Blair",
    "Kenta Gustavsson",
    "Kevin Bathe",
    "Kevin Fellion",
    "Kevin Hare",
    "Kevin Ibrahim",
    "Kevin Jansen",
    "Kevin Kuijer",
    "Kevin Murphy",
    "Kevin Polson",
    "Kevin Radler",
    "Kevin Robert",
    "Kevin Splady",
    "Khaled W AlSulaiti",
    "Kheldon Sherwood",
    "Khoa Truong",
    "Khyzzy",
    "Kickn Chickn",
    "Kiel Arenas",
    "King",
    "Kishmar Smith",
    "Klanransalee ",
    "Klaus Dobrzynski",
    "Klaus Murra",
    "Koha",
    "Konrad Kociński",
    "Kool-ade",
    "Kourosh Vosough",
    "Kozzen",
    "Kris",
    "Kris MV",
    "Kristopher Battles",
    "Kristopher Bowling",
    "Krom",
    "Krypto#1307",
    "Kwendion 13",
    "Kyle Edlin",
    "Kyle Francis",
    "Kyle Peck",
    "Kyle Stamps",
    "LONESTAR",
    "Labi",
    "Lara Marcattili",
    "Larry Hook",
    "Larry Nau",
    "Lars Wingemark",
    "Laszlo Hunor",
    "Laura A Clegg",
    "Laura Sieloff",
    "Laurent Fessard",
    "Laurie Holmes",
    "Laurie Timothy",
    "Laurine League",
    "Leeloo",
    "Leena Marigold",
    "Leprona",
    "Lesley Manson",
    "Levi Whaley",
    "Liam McCarthy",
    "Liam O'Donnell",
    "Liam Olpin",
    "Liam Swan",
    "Liart",
    "Linora",
    "LivinOnTheCorner",
    "Liz The Journal Magpie",
    "Logan",
    "Logan F",
    "Lori Nincehelser",
    "Lori Nincehelser",
    "Lorna Appleby",
    "Lorvahaven Hunter",
    "Lorvahavenhunter ",
    "LrdNikon ",
    "Luca Migliorini",
    "Lucifers W",
    "Luckrider",
    "Luis Flores",
    "Luke Beals",
    "Luke Newland",
    "Luke Westra",
    "Lyricai",
    "MC",
    "MVP",
    "MWARFOU JOCKER",
    "Mackenzie Rushing",
    "Macroholic",
    "Madgar29 ",
    "Maffon",
    "Magnerian",
    "Magnus Karlsson",
    "Mals",
    "MankiGames ",
    "Manuel Nordmeier",
    "Manuel Sternath",
    "Marc E Scott",
    "Marc allen",
    "Marcel Spieard",
    "Marco Horst",
    "Marco Martens",
    "Marcos Andre",
    "Marcus Andesson",
    "Marcus Helgstrand",
    "Mardy Stevens",
    "Marek Dvořák",
    "Mariusz Sawlewicz",
    "Mark",
    "Mark ",
    "Mark Bradley",
    "Mark David McCoy 34",
    "Mark Dion",
    "Mark Eberle",
    "Mark Gomersbach",
    "Mark Robinson",
    "Mark van de Beek",
    "Markgthr",
    "Markus",
    "Markus Hartje",
    "Maroun ghanem",
    "Marshmellow",
    "Martijn",
    "Martijn Groenewegen",
    "Martin ",
    "Martin Needham",
    "Martin Needham",
    "Martin Robertsson",
    "Martin Vines",
    "Martina C.",
    "Master Lee",
    "Mathias Bohman",
    "Mathias Fuchs",
    "Mathusala",
    "Matt",
    "Matt Sneary",
    "Matt Surratt",
    "Matthew Gural",
    "Matthew Leech",
    "Matthew Peabody",
    "Matthew Sager",
    "Matthew Trukositz",
    "Matthias Mosberger",
    "Matty7500",
    "Maurice Josten",
    "Maverick Jones",
    "Mavros",
    "Max",
    "Max Meijer",
    "Maybe1",
    "McLeod Turner",
    "MechaZao",
    "Mechelle McGowan Cheng",
    "Megan Sims (Blenderkitten)",
    "Melchy",
    "Melissa N Anderson",
    "Melissa condon",
    "Meph",
    "Mephchens",
    "Mephiroth",
    "Mercurio",
    "Merly Butler",
    "Miakis Lytellion",
    "Micael Johnsson",
    "Michael",
    "Michael ",
    "Michael Bailey",
    "Michael Bankston",
    "Michael Becker",
    "Michael Bray",
    "Michael Brodie",
    "Michael Castronovo",
    "Michael Danser",
    "Michael Fenton",
    "Michael Frnka",
    "Michael H",
    "Michael Irving",
    "Michael Lewis",
    "Michael Mcdaniels",
    "Michael R Kauffmann",
    "Michael Schulz",
    "Michael Swancott",
    "Michael W",
    "Michael Youngblood",
    "Michal Stalanowski",
    "Michel FEHR",
    "Michel Fehr",
    "Michelle Ström",
    "Mick",
    "Miethos",
    "Mikael Sundström",
    "Mike",
    "Mike Lavore",
    "Mike Pegg",
    "Mikel Carrascosa Alonso",
    "Mikkel Juul Jørgensen",
    "Mirek",
    "Miss Zombeezy",
    "Misty Jinn",
    "Mitch",
    "Mitchell Emberson",
    "Moe Nice",
    "Mohd Bohamad",
    "MolarMacros",
    "Monkey of Paris",
    "Moremore Monmon",
    "Morgan Asher",
    "Morgana Hilra",
    "MrDarque",
    "MrLind",
    "Murat",
    "Murray Technician",
    "Mustafa Kamil",
    "MyJock ye",
    "Mystik",
    "Naomi McMillan",
    "Narz",
    "Nate Whisnant",
    "Nathan Gillespie",
    "Nathan Jetson",
    "Nathan Lear",
    "Nathan Warfield",
    "Nawaf Aljudaibi",
    "Naye",
    "Ndecent ",
    "Nebiros",
    "Neil Blain",
    "Neil C",
    "Neoxars",
    "Nestor",
    "Neya",
    "Ni Kaka",
    "Nichola Richardson",
    "Nicholas Brown",
    "Nick Cornelius",
    "Nick Martin",
    "Nicola Spence",
    "Nigel Fellows",
    "NightOwl",
    "NightWeasel ",
    "Ninin",
    "Noah",
    "Noah Burge",
    "Noneya Biz",
    "Nonope",
    "Nora Kirschling",
    "Norbert Riemer",
    "Norving Gutierrez",
    "NotNektar",
    "NotSure SureNot",
    "OLDT1MER ",
    "Obi",
    "Offline",
    "Ohgurr Gaming",
    "Oliver Barth",
    "Oliver Berger",
    "Olivér Pécsi",
    "OnePunch",
    "Orclikepork",
    "Orion8 Junk",
    "Orlando Miguel Lahoya",
    "Ourax",
    "Ouya France",
    "Overly Aggressive/ PhatZero Videos",
    "Ozzi",
    "P",
    "Paffkata DGE",
    "PansaJones",
    "Passy No",
    "Patrick",
    "Patrick B",
    "Patrick Bokelmann",
    "Patrick Lüke",
    "Patrick Lüke",
    "Patrick O'Hagan",
    "Patrick Van eldik",
    "Paul",
    "Paul Coffey",
    "Paul Gilhespy",
    "Paul Guertin",
    "Paul Harrell",
    "Paul Harris",
    "Paul Kingman",
    "Paul Tillery",
    "Paul Westervelt",
    "Paul White",
    "Peanutbeards",
    "Pedro Machado Creste",
    "Penny2",
    "Per Jensen",
    "Pete Corbett",
    "Peter",
    "Peter Hansen",
    "Peter Haugen",
    "Peter Masters",
    "Peter Schlüter",
    "Peter Toft",
    "Peter von der Ahe",
    "Petr Poustecký",
    "Petter Zweidorff",
    "Phat Le",
    "Phil ",
    "Phil Vo",
    "Philip Bird",
    "Philipp Reitter",
    "Phillip Banky",
    "Phillip Smithhisler",
    "Physekiel",
    "Pierfrancesco Marone",
    "Pih_TV",
    "Pippa Martel",
    "Plastic Heart",
    "Pohtaytoh",
    "Ponics",
    "Possum Jenkins",
    "PotSh0t",
    "ProWater",
    "Prof Dabs",
    "Protest Obscurity",
    "Proton",
    "Pte Partz",
    "Pumpers",
    "Punica",
    "Pwntatochip",
    "Pyred",
    "Quint",
    "R Lee Cawthon",
    "RACHEL liperote",
    "RSD",
    "RabidClaws ",
    "Radioactive Bullfrog",
    "Rafael Tosi",
    "Rakuza yoknomu",
    "Randall Crank",
    "Randy Barton",
    "Randy Belknap",
    "Randy G",
    "Randy Kavanaugh",
    "Randy Rushing",
    "Raubtiereins",
    "RaviWolf",
    "Ravn Maniac",
    "Raw",
    "Ray Adams",
    "Ray Feliciano",
    "Ray H",
    "Raymond Aguirre",
    "Raymond Monk",
    "Razerwing",
    "Rdawg06",
    "Rebecca Gosdin",
    "Reginald Zwartjes",
    "Remus Berretta",
    "Remzi",
    "Renato Freitas",
    "Rene Traue",
    "Repug Gaming",
    "Rhaina",
    "Ricardo Alvarez",
    "Rich Reighard",
    "Richard Hopkins",
    "Richard Kocielko",
    "Richard Leister",
    "Richard Sears",
    "Richard Truett",
    "Richard W",
    "Rickey C",
    "Ricky Woods",
    "Riki Knight",
    "Roadspill ",
    "Rob ",
    "Rob Melvin",
    "Rob Parker",
    "Rob Salani",
    "Robert Andersson",
    "Robert Costello",
    "Robert Ellsworth",
    "Robert Grabosch",
    "Robert Harris",
    "Robert J MacLeod",
    "Robert Lewis",
    "Robert MacLeod",
    "Robert Mcknight",
    "Robert Millar",
    "Robert Morvay",
    "Robert Pipan",
    "Robert Ruck",
    "Robert Wears",
    "Robert Webb",
    "Robert Wilson",
    "Robertas Suminskas",
    "Roberto Roeschmann",
    "Roberto Zanini",
    "Robin Laubinger",
    "Robin Udéhn",
    "Roborius",
    "Rod mackellar",
    "Rodrigo",
    "Rodrigo Bugs",
    "Rodrigo Maria Soares",
    "Rodrigo Mendoza",
    "Rody z",
    "Roger Heiniluoma",
    "Rolandas Normanas",
    "RoleClass ",
    "Ron Cameron",
    "Ron McNamara",
    "Ronald ",
    "Ronald De Martines",
    "Ronald Pritchett",
    "Ronnie Otterborg",
    "Ronny Sæle",
    "Rose Gulley",
    "Roxanne Arber",
    "Roxanne Arber",
    "Roy Hastings",
    "Rusina abdullah",
    "Russell Baker",
    "Russell Lee Laymance",
    "Ryan ",
    "Ryan Chen Pan",
    "Ryan Hickey",
    "Ryan Hoover",
    "Ryan McDonald",
    "Ryan Roberts",
    "Ryo",
    "RyzenPunk",
    "Râzor",
    "S Driggers",
    "S S",
    "Sah Quel Plaisir",
    "Salty",
    "Sam Byrnes",
    "Sami Nurmi",
    "Samma",
    "Samuel L Spencer",
    "Samuel Lacerda",
    "Samuel Lacerda",
    "Sandra Primm",
    "Sandy (AKA SassyGamer)",
    "Santiago Draco",
    "Saoud Ali",
    "Sara Bort",
    "Sarrion",
    "Scarlett Knight",
    "ScaryLarryGames",
    "ScaryLarryGames",
    "Schiwouna Schi",
    "Scott",
    "Scott Davis",
    "Scott Edwards-Dohn",
    "Scott Flippo",
    "Scott Gresham",
    "Scott Hounsell",
    "Scott Houska",
    "Scott Hurst",
    "Scott Penney",
    "Scott Rose",
    "Scott Tuman",
    "Scotty",
    "Sean O'Hara",
    "Sean Siegrist",
    "Sean Smith",
    "Sean Walsh",
    "Sean-Heidi Serraguard",
    "Sebastian Kieback",
    "Sebastian Linner",
    "Sebastien Milcent",
    "Semi",
    "Sepp24",
    "Serafina Moon",
    "Sercan Kum",
    "Sergey Droba",
    "Seth A. Savitsky",
    "Sev Severium",
    "Sh4wdy",
    "ShadyLucifer ",
    "Shaenoide",
    "Shane Kuchler",
    "Shannon Baines",
    "Shannon Bowers",
    "Shannon Peikert",
    "Shaun Baxter",
    "Shaun Flagel",
    "Shaun Olsen",
    "Shaun Parson",
    "Shawn Snyder",
    "Shawn Snyder",
    "Shawn Weishuhn",
    "Shayne Landers",
    "Shea Shay",
    "Shelltoekicks",
    "Shelmss",
    "Shirowi ",
    "Shockwave973",
    "Short",
    "Shtev",
    "Sid Robichaud",
    "Sillk",
    "SilverFox",
    "Simon Dabkowski",
    "Simon Karlskov",
    "Simon Wilcock",
    "Sina Lahsaee",
    "Singletail",
    "Sk",
    "Skiptrac3 ",
    "Skirmis LT",
    "Skwerrel",
    "Skyblaze75",
    "Slatorius",
    "SmoKings",
    "Snake痞",
    "Snakky",
    "Sol LeTaire",
    "Sol Masta",
    "Soldier VP",
    "Solltex ",
    "Sparrowhawk Sr",
    "Spartariuz",
    "Spencer Blomquist",
    "Stan Wang",
    "Stefan Hauck",
    "Stefan Kremer",
    "Stefano Boglietti",
    "Stefano Filardo",
    "Stephen Carmichael",
    "Stephen Seagrave",
    "Stephen Smith",
    "Stephen Wilson",
    "Stephen Wright",
    "Stephers",
    "Sternwind",
    "Steve Clink",
    "Steve Dodson",
    "Steve Hensch",
    "Steve Koch",
    "Steve McCarthy",
    "Steve Robben",
    "Steven Allison",
    "Steven Hansen",
    "Steven Rex",
    "Steven Shaw",
    "Steven Short",
    "Steven Sorkin",
    "Steven T Brewer",
    "Steven Tadlock",
    "Steven funnell",
    "Stew Frei",
    "Stonecolder71",
    "Stormy",
    "Stuart Hendrie",
    "Suman ",
    "Sumbear",
    "Sung Do",
    "Susan Mushill",
    "Susan Mushill",
    "Sven Sieber",
    "Sydney",
    "Sydney Richards",
    "Sylvok Wolfrun",
    "Szilárd Lukácsi",
    "Sérgio Miguel",
    "T C",
    "T D",
    "T M",
    "TAUNO RÄÄSTAS",
    "Tabby Post",
    "Tad Oleson",
    "Tad Oleson",
    "TakkedaHD",
    "Tamara C Duncan ",
    "Tamer Baes",
    "Tamesha Brown",
    "Tanja Dilger",
    "Tanner Walker",
    "Tasos Bounos",
    "Tawaporah",
    "Terry Musser",
    "Tersia Higgins",
    "ThESiXtHLeGioN",
    "The Jason",
    "The world through my eyes",
    "TheArabianLord",
    "TheKephas ",
    "Thomas ",
    "Thomas Hawes",
    "Thomas Nicholson",
    "Thomas Rambaut",
    "Thomas Young",
    "Thore Kvalheim",
    "Tiburan EU",
    "Tiegars",
    "Tim Firth",
    "Tim Mentink",
    "Tim Salmoni",
    "Tim Weiden",
    "Timothy Campbell",
    "Timothy allen patterson",
    "Tituswolfe",
    "Tobias Korn",
    "Todd Haines",
    "Toknyn",
    "Tolea ",
    "Tom",
    "Tom Oslovar",
    "Tom Snipes",
    "Tom Straugh",
    "Tommy ",
    "Tommy Edvardsen",
    "Tommy Southam",
    "Tommy White",
    "Tong Yu",
    "Tony Goodwin",
    "Tony Simpson",
    "Tony Smith",
    "Topcat357",
    "Tor Ove",
    "Torbjörn Jönsson",
    "Toril Harink ",
    "Tortuga",
    "Toto Leo",
    "Tove Too",
    "Toxic",
    "Tr3ss3n",
    "Tracy Howard",
    "Travis ",
    "Travis Delaney",
    "Travis Watson",
    "Trevor Gordon",
    "Trevor Harper",
    "Trevor Yeager",
    "Tris",
    "Trixie",
    "Troy Rooker",
    "Troy n Rooker",
    "Truzedo ",
    "Tsaiko",
    "Tsavdaridis Anastasios",
    "Tweadle",
    "TwistedSMF ",
    "TwiztidBloom",
    "Tyler Griffiths",
    "UhohOreo ",
    "Uistean",
    "Umenneske94",
    "Uncle Grumpy",
    "VR-Gamerz fr",
    "Valamar",
    "Valcyn",
    "Vanessa Jambois",
    "Veldon",
    "Venni Liimatainen",
    "Vetskyyy ",
    "Victor Florez",
    "Victor Hodges",
    "Victor Hua",
    "Vince G",
    "Vince Orlando",
    "Vincent Lee",
    "Vindra",
    "Vitalii Tsvietkov",
    "Vloshko ",
    "Voidfather",
    "Vuudi",
    "W Wilson",
    "Wagner Oliveira Lopes",
    "Walter Beiter",
    "Warren Jumper",
    "Waselbein",
    "Wazwaz",
    "Weird Alien",
    "Werg",
    "Werner van den Heever",
    "Wilhelm Thomassen",
    "Will Baistow",
    "William ",
    "William Isaacs",
    "William J Hiatt",
    "William Kelley",
    "William Lee",
    "William Mertler",
    "William P Grady",
    "William Perrotto",
    "William Sharp",
    "William Smith",
    "Willy",
    "Windfey",
    "Wizard Hayden",
    "Wizzie",
    "Wojciech Orpel",
    "Wonder Senpaii",
    "Woo Kim",
    "Woody",
    "XXX XXX",
    "Xantor",
    "XdR3M",
    "Xingudi",
    "XoDonZi",
    "Xochitl",
    "Xynix ",
    "Yan Cote",
    "Yh Wang",
    "Yi Han",
    "Yohanan",
    "Yousif Abdaulla",
    "Zachary Cullis",
    "Zachary Smith",
    "Zain Sohail",
    "Zainab Yakhoub",
    "Zane Savage",
    "ZappyRod",
    "Zdenek Caha",
    "Zhenyu Yao",
    "ZingZi",
    "Zioxiis",
    "Zoonets",
    "Zu#4997",
    "[ROG] Vision",
    "_Lillith_",
    "aaron ",
    "adam humphreys",
    "adrian ibris",
    "ahmed mekkawy",
    "alan coutts",
    "ale diki",
    "ali mohammadi",
    "allen",
    "alprazolam",
    "alvin parker",
    "amshagar ",
    "andy le",
    "andy sprague",
    "antonym29@gmail.com",
    "apokalypsiz arc",
    "axelius",
    "babalou",
    "bearno2021",
    "beat theory",
    "benjamin delhaye",
    "bk",
    "black panther",
    "blastingweevil",
    "buffnblue",
    "bunchishi tawara",
    "carolineself@gmail.com",
    "cghilla2711",
    "chad corbett",
    "chancealot16",
    "chef chef",
    "chenhao bai",
    "chichi",
    "chris bawden",
    "chris gallogly",
    "chris hellmuth",
    "chris mayhew",
    "christopher eluna",
    "cigarman",
    "claudia dimaggio",
    "cleafairy",
    "cloutyTV ",
    "coot ",
    "crogin",
    "crystaltech",
    "curtis buffum",
    "dadbod",
    "danny joacim",
    "david hawke",
    "deathbody89",
    "denis",
    "der mausi",
    "desdakiwi",
    "devlik",
    "dixon garyck",
    "dmz011",
    "dom",
    "drunkenboy ",
    "dwarf1986",
    "elad shlezinger",
    "emerson monday",
    "eren ",
    "eric ricker",
    "erodil quadros",
    "evans starzinger",
    "evasion",
    "ffcjonny",
    "fred gladstone",
    "fredde ",
    "friedbones",
    "fx god",
    "garrett ainsworth",
    "gerald bb",
    "giorgino",
    "grav",
    "hannah maxino",
    "heyor ",
    "huts",
    "iEatCatTreats",
    "ilker yavuz",
    "impaxx ",
    "ismail manış",
    "itmeTeemo",
    "james etenburn",
    "james hyatt",
    "james stuart broderick",
    "jamie bradley",
    "jarah marafie",
    "javi pedraza",
    "jay garcia",
    "jaymediaone",
    "jayson hunter",
    "jean-marie rossi",
    "jianqiang sun",
    "jimbob",
    "joe faultless",
    "joe lechner",
    "joel cadett",
    "johnehokanson",
    "jonathan wester",
    "jordon mabry",
    "jsc ",
    "juke ",
    "karen walker",
    "keith archer",
    "kelly jarrell",
    "kenneth brent raines (The BQQ (insert Vader u failed me for last time clip clip)(aka AuburnDad4Life)",
    "kenny pritchard",
    "kerim candan",
    "kristian montevecchi",
    "levend62",
    "lisalo7",
    "lloyd spencer",
    "lmamais lmamais",
    "luc janssens",
    "luke",
    "malkeet sumal",
    "manuel Leistner",
    "marc bonnett",
    "matt Williams",
    "mechweb",
    "mediasmart",
    "migro",
    "mika ai",
    "mike sano",
    "mike saul",
    "mourad abrahim",
    "mr mods",
    "mrraag",
    "msumal",
    "naago",
    "nameChef",
    "nathan barlow",
    "neofodder",
    "nerf",
    "neung",
    "nistule",
    "norman beshears",
    "numainville claudine",
    "orville godby",
    "pally",
    "pantinhatv",
    "pascalmaramis",
    "patategalactic",
    "patrice heinemann",
    "paytun",
    "peter goessling",
    "ph0enixuk",
    "phayth",
    "phillip corlett",
    "phinyo yo",
    "pudkud",
    "quoc nguyen",
    "rachid benchaou",
    "ralf heckel",
    "regis Halbout",
    "rightonetwo",
    "ron mcsweeney",
    "rwpow",
    "ryan kloepper",
    "ryon84",
    "ryzael75",
    "scott normandale",
    "sheriwn kk",
    "silvershark71",
    "slashwrist",
    "solstice",
    "stagd ",
    "starbeam",
    "sten",
    "sten",
    "stiph curry",
    "terry johnston",
    "thebadcatbot.com",
    "thorshammer",
    "tkitez (take it easy)",
    "todd greaves",
    "tony",
    "troy tallent",
    "ttplank",
    "tuoko tk",
    "twmwalters",
    "tyreek73 Mcn",
    "uwe pabst",
    "wangmang",
    "wargood ",
    "wouZAR ",
    "wynne clark",
    "xManiac",
    "xan2622",
    "xin xin",
    "xiutian zhu",
    "yourlivid yourlivid",
    "yuyuD",
    "zambelc",
    "zhang zhang",
    "zibiken",
    "Íl Danno",
    "Александр Коротков",
    "Александр Сазонов",
    "Андрей Суколенко",
    "Антон Сидоров",
    "Данила Турбин",
    "Олег Вкусняшкин",
    "Роман Ершов",
    "Сергей Казекин",
    "مشعل العنزي",
    "南 天气",
    "博 曹",
    "尕骨頭",
    "巴人 某",
    "怂怂 叶",
    "昭育 曾",
    "昱升 刘",
    "李",
    "熙 凌",
    "瞎子 我是个",
    "纪昭 王",
    "翔仁 涂",
    "锦程 赵",
    "马小慧",
    "高 i",
    "경환 이",
    "문 아이언",
    "민형 김",
    "사람 로블하는",
    "성길 김",
    "스턱 김",
    "임 용준"
}