LBIS.EnchantSources =
{
    [8024] = { Name = "Flametongue Weapon", DesignId = "99999", Source = LBIS.L["Shaman Spell"], SourceLocation = "", TextureId = "" },
    [51730] = { Name = "Earthliving Weapon", DesignId = "99999", Source = LBIS.L["Shaman Spell"], SourceLocation = "", TextureId = "" },
    [53343] = { Name = "Rune of Razorice", DesignId = "99999", Source = LBIS.L["Death Knight Spell"], SourceLocation = "", TextureId = "" },
    [53344] = { Name = "Rune of the Fallen Crusader", DesignId = "99999", Source = LBIS.L["Death Knight Spell"], SourceLocation = "", TextureId = "" },
    [53365] = { Name = "Unholy Strength", DesignId = "99999", Source = LBIS.L["Death Knight Spell"], SourceLocation = "", TextureId = "" },
    [54999] = { Name = "Hyperspeed Accelerators", DesignId = "99999", Source = LBIS.L["Engineering Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [55642] = { Name = "Lightweave Embroidery", DesignId = "99999", Source = LBIS.L["Tailoring Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [74230] = { Name = "Enchant Cloak - Critical Strike", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [82175] = { Name = "Synapse Springs", DesignId = "99999", Source = LBIS.L["Engineering Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [96264] = { Name = "Enchant Bracer - Agility", DesignId = "68787", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "68787" },
    [104338] = { Name = "Enchant Bracer - Mastery", DesignId = "84560", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84560" },
    [104385] = { Name = "Enchant Bracer - Major Dodge", DesignId = "84558", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84558" },
    [104389] = { Name = "Enchant Bracer - Super Intellect", DesignId = "84559", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84559" },
    [104390] = { Name = "Enchant Bracer - Exceptional Strength", DesignId = "84561", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84561" },
    [104391] = { Name = "Enchant Bracer - Greater Agility", DesignId = "84557", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84557" },
    [104395] = { Name = "Enchant Chest - Glorious Stats", DesignId = "84562", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84562" },
    [104397] = { Name = "Enchant Chest - Superior Stamina", DesignId = "84565", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84565" },
    [104398] = { Name = "Enchant Cloak - Accuracy", DesignId = "84568", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84568" },
    [104401] = { Name = "Enchant Cloak - Greater Protection", DesignId = "84566", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84566" },
    [104403] = { Name = "Enchant Cloak - Superior Intellect", DesignId = "84569", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84569" },
    [104404] = { Name = "Enchant Cloak - Superior Critical Strike", DesignId = "84567", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84567" },
    [104407] = { Name = "Enchant Boots - Greater Haste", DesignId = "84554", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84554" },
    [104408] = { Name = "Enchant Boots - Greater Precision", DesignId = "84555", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84555" },
    [104409] = { Name = "Enchant Boots - Blurred Speed", DesignId = "84553", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84553" },
    [104414] = { Name = "Enchant Boots - Pandaren's Step", DesignId = "84556", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84556" },
    [104416] = { Name = "Enchant Gloves - Greater Haste", DesignId = "84571", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84571" },
    [104417] = { Name = "Enchant Gloves - Superior Expertise", DesignId = "84570", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84570" },
    [104419] = { Name = "Enchant Gloves - Super Strength", DesignId = "84573", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84573" },
    [104420] = { Name = "Enchant Gloves - Superior Mastery", DesignId = "84572", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84572" },
    [104425] = { Name = "Enchant Weapon - Windsong", DesignId = "84582", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84582" },
    [104427] = { Name = "Enchant Weapon - Jade Spirit", DesignId = "84583", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84583" },
    [104434] = { Name = "Enchant Weapon - Dancing Steel", DesignId = "84584", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84584" },
    [104440] = { Name = "Enchant Weapon - Colossus", DesignId = "84579", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84579" },
    [104442] = { Name = "Enchant Weapon - River's Song", DesignId = "84580", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84580" },
    [104445] = { Name = "Enchant Off-Hand - Major Intellect", DesignId = "84574", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "84574" },
    [108789] = { Name = "Phase Fingers", DesignId = "99999", Source = LBIS.L["Engineering Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [109085] = { Name = "Lord Blastington's Scope of Doom", DesignId = "99999", Source = unknown, SourceLocation = unknown, TextureId = "" },
    [109086] = { Name = "Lord Blastington's Scope of Doom", DesignId = "77529", Source = LBIS.L["Engineering Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "77529" },
    [113046] = { Name = "Secret Tiger Claw Inscription", DesignId = "87584", Source = LBIS.L["Inscription Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "87584" },
    [121192] = { Name = "Greater Tiger Fang Inscription", DesignId = "83006", Source = LBIS.L["Inscription Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "83006" },
    [121193] = { Name = "Greater Tiger Claw Inscription", DesignId = "83007", Source = LBIS.L["Inscription Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "83007" },
    [121194] = { Name = "Greater Ox Horn Inscription", DesignId = "87560", Source = LBIS.L["Inscription Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "87560" },
    [121195] = { Name = "Greater Crane Wing Inscription", DesignId = "87559", Source = LBIS.L["Inscription Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "87559" },
    [122386] = { Name = "Ironscale Leg Armor", DesignId = "83763", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "83763" },
    [122387] = { Name = "Shadowleather Leg Armor", DesignId = "83764", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "83764" },
    [122388] = { Name = "Angerhide Leg Armor", DesignId = "83765", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "83765" },
    [122392] = { Name = "Greater Cerulean Spellthread", DesignId = "82445", Source = LBIS.L["Tailoring Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "82445" },
    [122393] = { Name = "Greater Pearlescent Spellthread", DesignId = "82444", Source = LBIS.L["Tailoring Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "82444" },
    [124091] = { Name = "Sha Armor Kit", DesignId = "85559", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "85559" },
    [124551] = { Name = "Fur Lining - Agility", DesignId = "99999", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [124552] = { Name = "Fur Lining - Intellect", DesignId = "99999", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [124553] = { Name = "Fur Lining - Stamina", DesignId = "99999", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [124559] = { Name = "Primal Leg Reinforcements", DesignId = "99999", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [124561] = { Name = "Draconic Leg Reinforcements", DesignId = "99999", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [124563] = { Name = "Heavy Leg Reinforcements", DesignId = "99999", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [125481] = { Name = "Lightweave Embroidery", DesignId = "99999", Source = LBIS.L["Tailoring Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [125483] = { Name = "Swordguard Embroidery", DesignId = "99999", Source = LBIS.L["Tailoring Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [125496] = { Name = "Master's Spellthread", DesignId = "99999", Source = LBIS.L["Tailoring Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [126731] = { Name = "Synapse Springs", DesignId = "99999", Source = LBIS.L["Engineering Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [127013] = { Name = "Crane Wing Inscription", DesignId = "87578", Source = LBIS.L["Inscription Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "87578" },
    [130749] = { Name = "Enchant Bracer - Exceptional Strength (Scaling)", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [130758] = { Name = "Enchant Shield - Greater Parry", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [141167] = { Name = "Greater Crane Wing Inscription", DesignId = "87559", Source = LBIS.L["Inscription Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "87559" },
    [141168] = { Name = "Enchant Cloak - Superior Intellect", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [141170] = { Name = "Enchant Bracer - Super Intellect", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [141173] = { Name = "Enchant Gloves - Greater Haste", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [141174] = { Name = "Greater Cerulean Spellthread", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [141175] = { Name = "Enchant Boots - Pandaren's Step", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [141176] = { Name = "Enchant Off-Hand - Major Intellect", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [141177] = { Name = "Enchant Weapon - Jade Spirit", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [141330] = { Name = "Synapse Springs", DesignId = "99999", Source = LBIS.L["Engineering Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [141862] = { Name = "Enchant Gloves - Superior Mastery", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [141868] = { Name = "Enchant Bracer - Mastery", DesignId = "99999", Source = LBIS.L["Enchanting Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
    [142173] = { Name = "Lightweave Embroidery", DesignId = "99999", Source = LBIS.L["Tailoring Trainer"], SourceLocation = LBIS.L["Faction Capital"], TextureId = "" },
}
