LBIS.EnchantSources =
{
    [25072] = { Name = "Enchant Gloves - Threat", DesignId = "33153", ScrollId = "38885", Source = LBIS.L["Almaador"], SourceLocation = LBIS.L["The Sha'tar (Exalted)"], TextureId = "" },
    [25080] = { Name = "Enchant Gloves - Superior Agility", DesignId = "33152", ScrollId = "38890", Source = LBIS.L["Alurmi"], SourceLocation = LBIS.L["Keepers of Time (Exalted)"], TextureId = "" },
    [27906] = { Name = "Enchant Bracer - Major Defense", DesignId = "22530", ScrollId = "38899", Source = LBIS.L["Ethereum Nullifier"], SourceLocation = LBIS.L["Netherstorm"], TextureId = "" },
    [27914] = { Name = "Enchant Bracer - Fortitude", DesignId = "22533", ScrollId = "38902", Source = LBIS.L["Coilfang Oracle"], SourceLocation = LBIS.L["The Steamvault"], TextureId = "" },
    [27958] = { Name = "Enchant Chest - Exceptional Mana", DesignId = "0", ScrollId = "38912", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [27968] = { Name = "Enchant Weapon - Major Intellect", DesignId = "22551", ScrollId = "38918", Source = LBIS.L["Sunfury Researcher"], SourceLocation = LBIS.L["Netherstorm"], TextureId = "" },
    [27984] = { Name = "Enchant Weapon - Mongoose", DesignId = "22559", ScrollId = "38925", Source = LBIS.L["Moroes"], SourceLocation = LBIS.L["Karazhan"], TextureId = "" },
    [33990] = { Name = "Enchant Chest - Major Spirit", DesignId = "0", ScrollId = "38928", Source = LBIS.L["Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [33994] = { Name = "Enchant Gloves - Precise Strikes", DesignId = "28271", ScrollId = "38932", Source = LBIS.L["Fedryen Swiftspear"], SourceLocation = LBIS.L["Cenarion Expedition (Revered)"], TextureId = "" },
    [34007] = { Name = "Enchant Boots - Cat's Swiftness", DesignId = "28279", ScrollId = "38943", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [34009] = { Name = "Enchant Shield - Major Stamina", DesignId = "28282", ScrollId = "38945", Source = LBIS.L["Madame Ruby"], SourceLocation = LBIS.L["Shattrath City"], TextureId = "" },
    [35417] = { Name = "Greater Inscription of Vengeance", DesignId = "0", ScrollId = "0", Source = LBIS.L["Scribe Saalyn"], SourceLocation = LBIS.L["The Aldor (Exalted)"], TextureId = "28888" },
    [35452] = { Name = "Arcanum of Ferocity", DesignId = "0", ScrollId = "0", Source = LBIS.L["Fedryen Swiftspear"], SourceLocation = LBIS.L["Cenarion Expedition (Revered)"], TextureId = "29192" },
    [44484] = { Name = "Enchant Gloves - Expertise", DesignId = "0", ScrollId = "38951", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44488] = { Name = "Enchant Gloves - Precision", DesignId = "0", ScrollId = "38953", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44489] = { Name = "Enchant Shield - Defense", DesignId = "0", ScrollId = "38954", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44508] = { Name = "Enchant Boots - Greater Spirit", DesignId = "0", ScrollId = "38961", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44509] = { Name = "Enchant Chest - Greater Mana Restoration", DesignId = "0", ScrollId = "38962", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44528] = { Name = "Enchant Boots - Greater Fortitude", DesignId = "0", ScrollId = "38966", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44529] = { Name = "Enchant Gloves - Major Agility", DesignId = "0", ScrollId = "38967", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44555] = { Name = "Enchant Bracers - Exceptional Intellect", DesignId = "0", ScrollId = "38968", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44575] = { Name = "Enchant Bracers - Greater Assault", DesignId = "0", ScrollId = "44815", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [44584] = { Name = "Enchant Boots - Greater Vitality", DesignId = "0", ScrollId = "38974", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44588] = { Name = "Enchant Chest - Exceptional Resilience", DesignId = "0", ScrollId = "38975", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [44589] = { Name = "Enchant Boots - Superior Agility", DesignId = "0", ScrollId = "38976", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44591] = { Name = "Enchant Cloak - Titanweave", DesignId = "37347", ScrollId = "38978", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [44592] = { Name = "Enchant Gloves - Exceptional Spellpower", DesignId = "0", ScrollId = "38979", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44598] = { Name = "Enchant Bracers - Expertise", DesignId = "0", ScrollId = "38984", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44623] = { Name = "Enchant Chest - Super Stats", DesignId = "0", ScrollId = "38989", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44625] = { Name = "Enchant Gloves - Armsman", DesignId = "44485", ScrollId = "38990", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [44633] = { Name = "Enchant Weapon - Exceptional Agility", DesignId = "0", ScrollId = "38995", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44636] = { Name = "Enchant Ring - Greater Spellpower", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44645] = { Name = "Enchant Ring - Assault", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44770] = { Name = "Glove Reinforcements", DesignId = "34207", ScrollId = "0", Source = LBIS.L["Master Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [47672] = { Name = "Enchant Cloak - Mighty Armor", DesignId = "44471", ScrollId = "39001", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [47766] = { Name = "Enchant Chest - Greater Defense", DesignId = "37336", ScrollId = "39002", Source = LBIS.L["Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [47898] = { Name = "Enchant Cloak - Greater Speed", DesignId = "39003", ScrollId = "39003", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [47900] = { Name = "Enchant Chest - Super Health", DesignId = "0", ScrollId = "39005", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [47901] = { Name = "Enchant Boots - Tuskarr's Vitality", DesignId = "44491", ScrollId = "39006", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [50963] = { Name = "Heavy Borean Armor Kit", DesignId = "38376", ScrollId = "0", Source = LBIS.L["Grand Master Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [50964] = { Name = "Jormungar Leg Armor", DesignId = "38371", ScrollId = "0", Source = LBIS.L["Grand Master Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [50965] = { Name = "Frosthide Leg Armor", DesignId = "38373", ScrollId = "0", Source = LBIS.L["Grand Master Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [50966] = { Name = "Nerubian Leg Armor", DesignId = "38372", ScrollId = "0", Source = LBIS.L["Grand Master Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [50967] = { Name = "Icescale Leg Armor", DesignId = "38374", ScrollId = "0", Source = LBIS.L["Grand Master Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [53323] = { Name = "Rune of Swordshattering", DesignId = "0", ScrollId = "0", Source = LBIS.L["Amal'thazad"], SourceLocation = "", TextureId = "" },
    [53343] = { Name = "Rune of Razorice", DesignId = "0", ScrollId = "0", Source = LBIS.L["Amal'thazad"], SourceLocation = "", TextureId = "" },
    [53344] = { Name = "Rune of the Fallen Crusader", DesignId = "0", ScrollId = "0", Source = LBIS.L["Amal'thazad"], SourceLocation = "", TextureId = "" },
    [54446] = { Name = "Rune of Swordbreaking", DesignId = "0", ScrollId = "0", Source = LBIS.L["Amal'thazad"], SourceLocation = "", TextureId = "" },
    [54736] = { Name = "Personal Electromagnetic Pulse Generator", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "" },
    [54793] = { Name = "Frag Belt", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "" },
    [54861] = { Name = "Nitro Boosts", DesignId = "41118", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "41118" },
    [54998] = { Name = "Hand-Mounted Pyro Rocket", DesignId = "41091", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "41091" },
    [54999] = { Name = "Hyperspeed Accelerators", DesignId = "41093", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "41093" },
    [55002] = { Name = "Flexweave Underlay", DesignId = "41111", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "" },
    [55016] = { Name = "Nitro Boosts", DesignId = "41118", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "" },
    [55628] = { Name = "Socket Bracer", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Blacksmithing Trainer"], SourceLocation = "", TextureId = "" },
    [55641] = { Name = "Socket Gloves", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Blacksmithing Trainer"], SourceLocation = "", TextureId = "" },
    [55642] = { Name = "Lightweave Embroidery", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Tailoring Trainer"], SourceLocation = "", TextureId = "" },
    [55656] = { Name = "Eternal Belt Buckle", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Blacksmithing Trainer"], SourceLocation = "", TextureId = "41611" },
    [55769] = { Name = "Darkglow Embroidery", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Tailoring Trainer"], SourceLocation = "", TextureId = "" },
    [55777] = { Name = "Swordguard Embroidery", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Tailoring Trainer"], SourceLocation = "", TextureId = "" },
    [55839] = { Name = "Titanium Weapon Chain", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Blacksmithing Trainer"], SourceLocation = "", TextureId = "41976" },
    [56008] = { Name = "Shining Spellthread", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Tailoring Trainer"], SourceLocation = "", TextureId = "41601" },
    [56009] = { Name = "Brilliant Spellthread", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Tailoring Trainer"], SourceLocation = "", TextureId = "41602" },
    [56010] = { Name = "Azure Spellthread", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Tailoring Trainer"], SourceLocation = "", TextureId = "41603" },
    [56011] = { Name = "Sapphire Spellthread", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Tailoring Trainer"], SourceLocation = "", TextureId = "41604" },
    [56039] = { Name = "Sanctified Spellthread", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Tailoring Trainer"], SourceLocation = "", TextureId = "" },
    [56470] = { Name = "Sun Scope", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "41146" },
    [56478] = { Name = "Heartseeker Scope", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "41167" },
    [57683] = { Name = "Fur Lining - Attack Power", DesignId = "43097", ScrollId = "0", Source = LBIS.L["Grand Master Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [57690] = { Name = "Fur Lining - Stamina", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [57691] = { Name = "Fur Lining - Spell Power", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [59619] = { Name = "Enchant Weapon - Accuracy", DesignId = "44496", ScrollId = "44497", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [59621] = { Name = "Enchant Weapon - Berserking", DesignId = "44492", ScrollId = "44493", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [59625] = { Name = "Enchant Weapon - Black Magic", DesignId = "44495", ScrollId = "43987", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [59636] = { Name = "Enchant Ring - Stamina", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [59784] = { Name = "Arcanum of Dominance", DesignId = "0", ScrollId = "0", Source = LBIS.L["Quartermasters"], SourceLocation = LBIS.L["Alliance Vanguard/Horde Expedition (Revered)"], TextureId = "44075" },
    [59927] = { Name = "Lesser Inscription of the Storm", DesignId = "0", ScrollId = "0", Source = LBIS.L["Lillehoff"], SourceLocation = LBIS.L["The Sons of Hodir (Honored)"], TextureId = "44129" },
    [59929] = { Name = "Lesser Inscription of the Axe", DesignId = "0", ScrollId = "0", Source = LBIS.L["Lillehoff"], SourceLocation = LBIS.L["The Sons of Hodir (Honored)"], TextureId = "44131" },
    [59934] = { Name = "Greater Inscription of the Axe", DesignId = "0", ScrollId = "0", Source = LBIS.L["Lillehoff"], SourceLocation = LBIS.L["The Sons of Hodir (Exalted)"], TextureId = "50335" },
    [59936] = { Name = "Greater Inscription of the Crag", DesignId = "0", ScrollId = "0", Source = LBIS.L["Lillehoff"], SourceLocation = LBIS.L["The Sons of Hodir (Exalted)"], TextureId = "50336" },
    [59937] = { Name = "Greater Inscription of the Storm", DesignId = "0", ScrollId = "0", Source = LBIS.L["Lillehoff"], SourceLocation = LBIS.L["The Sons of Hodir (Exalted)"], TextureId = "50338" },
    [59941] = { Name = "Greater Inscription of the Pinnacle", DesignId = "0", ScrollId = "0", Source = LBIS.L["Lillehoff"], SourceLocation = LBIS.L["The Sons of Hodir (Exalted)"], TextureId = "50337" },
    [59954] = { Name = "Arcanum of Torment", DesignId = "0", ScrollId = "0", Source = LBIS.L["Duchess Mynx"], SourceLocation = LBIS.L["Knights of the Ebon Blade (Revered)"], TextureId = "44149" },
    [59955] = { Name = "Arcanum of the Stalwart Protector", DesignId = "0", ScrollId = "0", Source = LBIS.L["Veteran Crusader Aliocha Segard"], SourceLocation = LBIS.L["Argent Crusade (Revered)"], TextureId = "50369" },
    [59960] = { Name = "Arcanum of Blissful Mending", DesignId = "0", ScrollId = "0", Source = LBIS.L["Cielstrasza"], SourceLocation = LBIS.L["The Wyrmrest Accord (Revered)"], TextureId = "50370" },
    [59970] = { Name = "Arcanum of Burning Mysteries", DesignId = "0", ScrollId = "0", Source = LBIS.L["Archmage Alvareaux"], SourceLocation = LBIS.L["Kirin Tor (Revered)"], TextureId = "50368" },
    [60583] = { Name = "Jormungar Leg Reinforcements", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [60609] = { Name = "Enchant Cloak - Speed", DesignId = "0", ScrollId = "44456", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [60616] = { Name = "Enchant Bracers - Striking", DesignId = "0", ScrollId = "38971", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [60623] = { Name = "Enchant Boots - Icewalker", DesignId = "0", ScrollId = "38986", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [60653] = { Name = "Enchant Shield - Greater Intellect", DesignId = "0", ScrollId = "44455", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [60663] = { Name = "Enchant Cloak - Major Agility", DesignId = "0", ScrollId = "44457", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [60668] = { Name = "Enchant Gloves - Crusher", DesignId = "0", ScrollId = "44458", Source = LBIS.L["Grand Master Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [60691] = { Name = "Enchant 2H Weapon - Massacre", DesignId = "44483", ScrollId = "44463", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [60692] = { Name = "Enchant Chest - Powerful Stats", DesignId = "44489", ScrollId = "44465", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [60707] = { Name = "Enchant Weapon - Superior Potency", DesignId = "44486", ScrollId = "44466", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [60714] = { Name = "Enchant Weapon - Mighty Spellpower", DesignId = "44487", ScrollId = "44467", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [60763] = { Name = "Enchant Boots - Greater Assault", DesignId = "44490", ScrollId = "44469", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [60767] = { Name = "Enchant Bracers - Superior Spellpower", DesignId = "44498", ScrollId = "44470", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [61117] = { Name = "Master's Inscription of the Axe", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Inscription Trainer"], SourceLocation = "", TextureId = "" },
    [61118] = { Name = "Master's Inscription of the Crag", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Inscription Trainer"], SourceLocation = "", TextureId = "" },
    [61119] = { Name = "Master's Inscription of the Pinnacle", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Inscription Trainer"], SourceLocation = "", TextureId = "" },
    [61120] = { Name = "Master's Inscription of the Storm", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Inscription Trainer"], SourceLocation = "", TextureId = "" },
    [61271] = { Name = "Arcanum of the Savage Gladiator", DesignId = "0", ScrollId = "0", Source = LBIS.L["Quartermasters"], SourceLocation = LBIS.L["Alliance Vanguard/Horde Expedition (Revered)"], TextureId = "44875" },
    [61471] = { Name = "Diamond-cut Refractor Scope", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "44739" },
    [62158] = { Name = "Rune of the Stoneskin Gargoyle", DesignId = "0", ScrollId = "0", Source = LBIS.L["Amal'thazad"], SourceLocation = "", TextureId = "" },
    [62202] = { Name = "Titanium Plating", DesignId = "44936", ScrollId = "0", Source = LBIS.L["Grand Master Blacksmithing Trainer"], SourceLocation = "", TextureId = "" },
    [62256] = { Name = "Enchant Bracers - Major Stamina", DesignId = "44944", ScrollId = "44947", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [62384] = { Name = "Greater Inscription of the Gladiator", DesignId = "0", ScrollId = "0", Source = LBIS.L["Accessories Quartermaster"], SourceLocation = LBIS.L["10000 Honor (PvP)"], TextureId = "44957" },
    [62448] = { Name = "Earthen Leg Armor", DesignId = "44963", ScrollId = "0", Source = LBIS.L["Grand Master Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [62948] = { Name = "Enchant Staff - Greater Spellpower", DesignId = "45056", ScrollId = "45056", Source = LBIS.L["Vanessa Sellers"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [63765] = { Name = "Springy Arachnoweave", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "" },
    [63770] = { Name = "Reticulated Armor Webbing", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "" },
    [64579] = { Name = "Enchant Weapon - Blood Draining", DesignId = "46348", ScrollId = "46098", Source = LBIS.L["Trash Drop"], SourceLocation = LBIS.L["Ulduar"], TextureId = "" },
    [67839] = { Name = "Mind Amplification Dish", DesignId = "0", ScrollId = "0", Source = LBIS.L["Grand Master Engineering Trainer"], SourceLocation = "", TextureId = "" },
    [70164] = { Name = "Rune of the Nerubian Carapace", DesignId = "0", ScrollId = "0", Source = LBIS.L["Amal'thazad"], SourceLocation = "", TextureId = "" },
}
