LBIS.GemSources =
{
    [32410] = { Name = "Thundering Skyfire Diamond", DesignId = "32411", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [34220] = { Name = "Chaotic Skyfire Diamond", DesignId = "34689", Source = LBIS.L["Coilskar Siren"], SourceLocation = LBIS.L["Shadowmoon Valley"] },
    [36767] = { Name = "Solid Dragon's Eye", DesignId = "42311", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [39996] = { Name = "Bold Scarlet Ruby", DesignId = "41576", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [39997] = { Name = "Delicate Scarlet Ruby", DesignId = "41577", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [39998] = { Name = "Runed Scarlet Ruby", DesignId = "41718", Source = LBIS.L["Archmage Alvareaux"], SourceLocation = LBIS.L["Kirin Tor (Exalted)"] },
    [39999] = { Name = "Bright Scarlet Ruby", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [40002] = { Name = "Fractured Scarlet Ruby", DesignId = "41817", Source = LBIS.L["World Drop"], SourceLocation = LBIS.L["Nascent Val'kyr"] },
    [40003] = { Name = "Precise Scarlet Ruby", DesignId = "41790", Source = LBIS.L["Herald Volazj"], SourceLocation = LBIS.L["Ahn'kahet: The Old Kingdom (Heroic)"] },
    [40008] = { Name = "Solid Sky Sapphire", DesignId = "42138", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40012] = { Name = "Brilliant Autumn's Glow", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [40013] = { Name = "Smooth Autumn's Glow", DesignId = "41720", Source = LBIS.L["Lillehoff"], SourceLocation = LBIS.L["The Sons of Hodir (Exalted)"] },
    [40014] = { Name = "Rigid Autumn's Glow", DesignId = "41580", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40015] = { Name = "Thick Autumn's Glow", DesignId = "41791", Source = LBIS.L["Cyanigosa"], SourceLocation = LBIS.L["The Violet Hold (Heroic)"] },
    [40017] = { Name = "Quick Autumn's Glow", DesignId = "41579", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40022] = { Name = "Sovereign Twilight Opal", DesignId = "41784", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [40023] = { Name = "Shifting Twilight Opal", DesignId = "41747", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40025] = { Name = "Glowing Twilight Opal", DesignId = "41725", Source = LBIS.L["Duchess Mynx"], SourceLocation = LBIS.L["Knights of the Ebon Blade (Exalted)"] },
    [40026] = { Name = "Purified Twilight Opal", DesignId = "41783", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [40027] = { Name = "Royal Twilight Opal", DesignId = "41701", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40029] = { Name = "Balanced Twilight Opal", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [40031] = { Name = "Regal Twilight Opal", DesignId = "41703", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40033] = { Name = "Puissant Twilight Opal", DesignId = "41702", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40034] = { Name = "Guardian's Twilight Opal", DesignId = "41726", Source = LBIS.L["Veteran Crusader Aliocha Segard"], SourceLocation = LBIS.L["Argent Crusade (Revered)"] },
    [40037] = { Name = "Inscribed Monarch Topaz", DesignId = "41789", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [40038] = { Name = "Etched Monarch Topaz", DesignId = "41777", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [40041] = { Name = "Fierce Monarch Topaz", DesignId = "41793", Source = LBIS.L["Ingvar the Plunderer"], SourceLocation = LBIS.L["Utgarde Keep (Heroic)"] },
    [40043] = { Name = "Deadly Monarch Topaz", DesignId = "41794", Source = LBIS.L["Keristrasza"], SourceLocation = LBIS.L["The Nexus (Heroic)"] },
    [40044] = { Name = "Glinting Monarch Topaz", DesignId = "41582", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40046] = { Name = "Deft Monarch Topaz", DesignId = "41792", Source = LBIS.L["Sjonnir The Ironshaper"], SourceLocation = LBIS.L["Halls of Stone (Heroic)"] },
    [40047] = { Name = "Luminous Monarch Topaz", DesignId = "41689", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40048] = { Name = "Potent Monarch Topaz", DesignId = "41686", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40049] = { Name = "Veiled Monarch Topaz", DesignId = "41688", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40051] = { Name = "Reckless Monarch Topaz", DesignId = "41690", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40053] = { Name = "Pristine Monarch Topaz", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [40055] = { Name = "Stark Monarch Topaz", DesignId = "41687", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40058] = { Name = "Accurate Monarch Topaz", DesignId = "41818", Source = LBIS.L["World Drop"], SourceLocation = LBIS.L["Mammoths - Storm Peaks"] },
    [40088] = { Name = "Vivid Forest Emerald", DesignId = "41698", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40089] = { Name = "Enduring Forest Emerald", DesignId = "41697", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40090] = { Name = "Steady Forest Emerald", DesignId = "41738", Source = LBIS.L["Wintergrasp Quartermaster"], SourceLocation = LBIS.L["Wintergrasp"] },
    [40091] = { Name = "Forceful Forest Emerald", DesignId = "41693", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40092] = { Name = "Seer's Forest Emerald", DesignId = "41699", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40094] = { Name = "Dazzling Forest Emerald", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [40102] = { Name = "Turbid Forest Emerald", DesignId = "41737", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [40104] = { Name = "Intricate Forest Emerald", DesignId = "41694", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [40112] = { Name = "Delicate Cardinal Ruby", DesignId = "46918", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40113] = { Name = "Runed Cardinal Ruby", DesignId = "46916", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40114] = { Name = "Bright Cardinal Ruby", DesignId = "46919", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40119] = { Name = "Solid Majestic Zircon", DesignId = "46924", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40123] = { Name = "Brilliant King's Amber", DesignId = "46930", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40125] = { Name = "Rigid King's Amber", DesignId = "46928", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40126] = { Name = "Thick King's Amber", DesignId = "46931", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40128] = { Name = "Quick King's Amber", DesignId = "46933", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40129] = { Name = "Sovereign Dreadstone", DesignId = "46935", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40133] = { Name = "Purified Dreadstone", DesignId = "46937", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40138] = { Name = "Regal Dreadstone", DesignId = "46940", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40141] = { Name = "Guardian's Dreadstone", DesignId = "46942", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40148] = { Name = "Glinting Ametrine", DesignId = "47008", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40150] = { Name = "Deft Ametrine", DesignId = "47020", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40153] = { Name = "Veiled Ametrine", DesignId = "46951", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40155] = { Name = "Reckless Ametrine", DesignId = "47007", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40157] = { Name = "Pristine Ametrine", DesignId = "46956", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40159] = { Name = "Stark Ametrine", DesignId = "47023", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40162] = { Name = "Accurate Ametrine", DesignId = "47010", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40166] = { Name = "Vivid Eye of Zul", DesignId = "46899", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [40167] = { Name = "Enduring Eye of Zul", DesignId = "46897", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
    [41285] = { Name = "Chaotic Skyflare Diamond", DesignId = "41704", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [41333] = { Name = "Ember Skyflare Diamond", DesignId = "41706", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [41339] = { Name = "Swift Skyflare Diamond", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = LBIS.L["Dalaran"] },
    [41376] = { Name = "Revitalizing Skyflare Diamond", DesignId = "41707", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [41377] = { Name = "Effulgent Skyflare Diamond", DesignId = "41705", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [41380] = { Name = "Austere Earthsiege Diamond", DesignId = "41797", Source = LBIS.L["King Ymiron"], SourceLocation = LBIS.L["Utgarde Pinnacle (Heroic)"] },
    [41396] = { Name = "Eternal Earthsiege Diamond", DesignId = "41799", Source = LBIS.L["Loken"], SourceLocation = LBIS.L["Halls of Lightning (Heroic)"] },
    [41397] = { Name = "Powerful Earthsiege Diamond", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [41398] = { Name = "Relentless Earthsiege Diamond", DesignId = "41710", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [41400] = { Name = "Thundering Skyflare Diamond", DesignId = "41787", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [41401] = { Name = "Insightful Earthsiege Diamond", DesignId = "41708", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [41432] = { Name = "Perfect Bold Bloodstone", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [41436] = { Name = "Perfect Fractured Bloodstone", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [41441] = { Name = "Perfect Solid Chalcedony", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [41453] = { Name = "Perfect Guardian's Shadow Crystal", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [41458] = { Name = "Perfect Regal Shadow Crystal", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [41461] = { Name = "Perfect Sovereign Shadow Crystal", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [41464] = { Name = "Perfect Enduring Dark Jade", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [41481] = { Name = "Perfect Vivid Dark Jade", DesignId = "41567", Source = LBIS.L["Geen"], SourceLocation = LBIS.L["The Oracles (Friendly)"] },
    [42142] = { Name = "Bold Dragon's Eye", DesignId = "42298", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [42143] = { Name = "Delicate Dragon's Eye", DesignId = "42301", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [42144] = { Name = "Runed Dragon's Eye", DesignId = "42309", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [42148] = { Name = "Brilliant Dragon's Eye", DesignId = "42300", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [42150] = { Name = "Quick Dragon's Eye", DesignId = "42307", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [42156] = { Name = "Rigid Dragon's Eye", DesignId = "42308", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [42157] = { Name = "Thick Dragon's Eye", DesignId = "42315", Source = LBIS.L["Tiffany Cartier"], SourceLocation = LBIS.L["Dalaran"] },
    [42702] = { Name = "Enchanted Tear", DesignId = "0", Source = LBIS.L["Master Jewelcrafting Trainer"], SourceLocation = "" },
    [45880] = { Name = "Solid Stormjewel", DesignId = "0", Source = LBIS.L["Daily Fishing Quest"], SourceLocation = "" },
    [45882] = { Name = "Brilliant Stormjewel", DesignId = "0", Source = LBIS.L["Daily Fishing Quest"], SourceLocation = "" },
    [45883] = { Name = "Runed Stormjewel", DesignId = "0", Source = LBIS.L["Daily Fishing Quest"], SourceLocation = "" },
    [49110] = { Name = "Nightmare Tear", DesignId = "49112", Source = LBIS.L["Timothy Jones"], SourceLocation = LBIS.L["Dalaran"] },
}
