local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'DeathKnight-Unholy','DeathKnight-Blood','Druid-Feral','Rogue-Assassination','Mage-Fire','Rogue-Combat','Unknown-Unknown','Paladin-Retribution','Shaman-Elemental','Shaman-Restoration','Hunter-Marksmanship','Warlock-Affliction','Druid-Warden','Priest-Holy','Paladin-Holy','Warlock-Demonology','Warrior-Fury','Priest-Shadow','DeathKnight-Runeblade','Priest-Discipline','Paladin-Protection','Hunter-Survival','DeathKnight-Frost',}; local provider = {region='CN',realm='安娜丝塔丽',name='5133',type='subscribers',zone=1037,date='2025-08-06',data={Ak='Akadd:BAEBDQQEGX8cAAMBAAoMCyMuAACvAgqdxgAAAwBhAJ7GAAADAFQAn8YAAAMARwGgxgAAAwBfAKHGAAADAGAAosYAAAMAYgCkxgAAAwA4AKXGAAADAGMApsYAAAMAYgGnxgAAAQBAAAEACgwLIy4AAK8CCp3GAAADAGEAnsYAAAMAVACfxgAAAwBHAaDGAAADAF8AocYAAAMAYACixgAAAwBiAKTGAAACADgApcYAAAMAYwCmxgAAAwBiAafGAAABAEAAAgABDAsLAAAAAAABpMYAAAEAHAABDQQEGQoKIgADAJolAA==.',Da='Dakk:BAEADQQEGQQKBAABDQQEGQoKIgADAJolAA==.',Go='Goosee:BAEADQQDGQoKVgABDQQEGQoKIgADAJolAA==.',Lo='Loewe:BAEADQQEGQoKDQABDQQEGQoKHAAEAFMjAA==.',Ma='Marni:BAEBDQQEGX8UAAIFAAsMCyNgAAClAgudxgAAAgBUAJ7GAAACAGEAn8YAAAIAWAGgxgAAAgBUAKHGAAACAGAAosYAAAIAWwCjxgAAAQBXAKTGAAACAFoApcYAAAIAVACmxgAAAgBjAafGAAABAF4ABQALDAsjYAAApQILncYAAAIAVACexgAAAgBhAJ/GAAACAFgBoMYAAAIAVAChxgAAAgBgAKLGAAACAFsAo8YAAAEAVwCkxgAAAgBaAKXGAAACAFQApsYAAAIAYwGnxgAAAQBeAAENBAQZCgocAAQAUyMA.',Mo='Moynat:BAEBDQQEGX8aAAIGAAwMQyUBAADkAwydxgAAAwBhAJ7GAAACAGMAn8YAAAMAYwGgxgAAAgBhAKHGAAACAGEAosYAAAMAYwCjxgAAAgBfAKTGAAACAGMApcYAAAIAYwCmxgAAAgBjAafGAAACAGIAqMYAAAEASAAGAAwMQyUBAADkAwydxgAAAwBhAJ7GAAACAGMAn8YAAAMAYwGgxgAAAgBhAKHGAAACAGEAosYAAAMAYwCjxgAAAgBfAKTGAAACAGMApcYAAAIAYwCmxgAAAgBjAafGAAACAGIAqMYAAAEASAABDQQEGQoKHAAEAFMjAA==.',Mu='Mugbee:BAEADQQDGQoKDAABDQQEGQoKCwAHAAAAAA==.',Pa='Patty:BAEBDQQEGX8gAAIIAAsMdSUmAABxAwudxgAAAwBhAJ7GAAADAF4An8YAAAMAPAGgxgAAAwBjAKHGAAADAGAAosYAAAMAWgCjxgAAAwBiAKTGAAADAGAApcYAAAMAXgCmxgAAAwBIAafGAAACAFoACAALDHUlJgAAcQMLncYAAAMAYQCexgAAAwBeAJ/GAAADADwBoMYAAAMAYwChxgAAAwBgAKLGAAADAFoAo8YAAAMAYgCkxgAAAwBgAKXGAAADAF4ApsYAAAMASAGnxgAAAgBaAAENBAQZCgoeAAUALCUA.',Ra='Raiku:BAEADQQDGQoKWQABDQQEGQoKHgAFACwlAA==.',Sh='Shamylicious:BAEADQQDGQoKFAABDQQEGQoKCwAHAAAAAA==.',Xi='Xiaopp:BAEBDQQEGX8eAAIFAAsMLCUPAABYAwudxgAAAwBdAJ7GAAACAF8An8YAAAMALQGgxgAAAwBfAKHGAAADAGMAosYAAAMAYQCjxgAAAgBbAKTGAAADAFoApcYAAAMAYACmxgAAAwAmAafGAAACAGAABQALDCwlDwAAWAMLncYAAAMAXQCexgAAAgBfAJ/GAAADAC0BoMYAAAMAXwChxgAAAwBjAKLGAAADAGEAo8YAAAIAWwCkxgAAAwBaAKXGAAADAGAApsYAAAMAJgGnxgAAAgBgAAAA.',['一雲']='一雲幼果一:BAEBDQQEGX8ZAAMJAAkM8SQiAADNAgmdxgAAAwBbAJ7GAAACAGEAn8YAAAMAIwGgxgAAAwBhAKHGAAADAFkAosYAAAMAXQCkxgAAAwBeAKXGAAACAGEApsYAAAMAXAEJAAkM8SQiAADNAgmdxgAAAwBbAJ7GAAACAGEAn8YAAAMAIwGgxgAAAwBhAKHGAAADAFkAosYAAAMAXQCkxgAAAwBeAKXGAAACAGEApsYAAAIAXAEKAAEMAACfAgAAAAGmxgAAAQAOAQAA.',['一零']='一零玖叁零一:BAEADQQDGQoKLwABDQQEGQoKCwAHAAAAAA==.',['万万']='万万想到没:BAEBDQQEGX8WAAILAAwMwSACAAB7AwydxgAAAgBXAJ7GAAACAFIAn8YAAAIANgGgxgAAAgBdAKHGAAACAFcAosYAAAIAXgCjxgAAAQBJAKTGAAACAF4ApcYAAAIAWwCmxgAAAgAiAafGAAACAFwAqMYAAAEAMAALAAwMwSACAAB7AwydxgAAAgBXAJ7GAAACAFIAn8YAAAIANgGgxgAAAgBdAKHGAAACAFcAosYAAAIAXgCjxgAAAQBJAKTGAAACAF4ApcYAAAIAWwCmxgAAAgAiAafGAAACAFwAqMYAAAEAMAABDQQEGQoKHwAMAG4hAA==.',['丨零']='丨零玖叁零丨:BAEADQQDGQoKDAABDQQEGQoKCwAHAAAAAA==.',['丰满']='丰满的葡萄:BAEADQQDGQoKIwABDQQEGQoKIgADAJolAA==.',['丶南']='丶南波万:BAEADQQEGQkKEgABDQQEGQoKHwAMAG4hAA==.丶南波万丶:BAEBDQQEGX8eAAMDAAwMSiELAAByAwydxgAAAwBhAJ7GAAACAFwAn8YAAAMAYgGgxgAAAwBfAKHGAAADAFwAosYAAAMAXACjxgAAAgBfAKTGAAADAGEApcYAAAMAYQCmxgAAAgBUAafGAAACAF4AqMYAAAEABQADAAwM8h8LAAByAwydxgAAAwBhAJ7GAAACAFwAn8YAAAMAYgGgxgAAAwBfAKHGAAADAFwAosYAAAMAXACjxgAAAQBAAKTGAAADAGEApcYAAAMAYQCmxgAAAgBUAafGAAACAF4AqMYAAAEABQANAAEMSCUMAABuAAGjxgAAAQBfAAENBAQZCgofAAwAbiEA.',['丷零']='丷零玖叁零丷:BAEADQQDGQoKJAABDQQEGQoKCwAHAAAAAA==.',['伤心']='伤心的新娘:BAEADQQEGQoKCgABDQQEGQoKIAAOANwVAA==.',['你喝']='你喝醉了沒:BAEADQQDGQoKPAABDQQEGQoKIwACAHMcAA==.你喝醉了没:BAEADQQEGQoKDAABDQQEGQoKIwACAHMcAA==.你喝醉了没丶:BAEBDQQEGX8jAAIIAAwMkiYCAAAEBAydxgAAAwBjAJ7GAAADAF0An8YAAAMAYwGgxgAAAwBiAKHGAAADAGMAosYAAAMAYwCjxgAAAwBiAKTGAAADAGMApcYAAAMAYwCmxgAAAwBjAafGAAADAGIAqMYAAAIAYwAIAAwMkiYCAAAEBAydxgAAAwBjAJ7GAAADAF0An8YAAAMAYwGgxgAAAwBiAKHGAAADAGMAosYAAAMAYwCjxgAAAwBiAKTGAAADAGMApcYAAAMAYwCmxgAAAwBjAafGAAADAGIAqMYAAAIAYwABDQQEGQoKIwACAHMcAA==.你喝醉了没丷:BAEADQQDGQoKGAABDQQEGQoKIwACAHMcAA==.你喝醉了没灬:BAEADQQDGQoKXwABDQQEGQoKIwACAHMcAA==.',['你心']='你心动了没丶:BAEADQQDGQoKJAABDQQEGQoKIwACAHMcAA==.',['僜熙']='僜熙:BAEBDQQEGX8gAAIKAAwM0BYvAACEAgydxgAAAwA6AJ7GAAADACIAn8YAAAMANgGgxgAAAwADAKHGAAADAFkAosYAAAMAXwCjxgAAAgAaAKTGAAADAGEApcYAAAMATgCmxgAAAwBKAafGAAACADkAqMYAAAEAKAAKAAwM0BYvAACEAgydxgAAAwA6AJ7GAAADACIAn8YAAAMANgGgxgAAAwADAKHGAAADAFkAosYAAAMAXwCjxgAAAgAaAKTGAAADAGEApcYAAAMATgCmxgAAAwBKAafGAAACADkAqMYAAAEAKAABDQQEGQoKIwAPAPoOAA==.',['关门']='关门打刘庚:BAEADQQEGQQKBAABDQQEGQoKIgADAJolAA==.',['刀刀']='刀刀好脆啊:BAEADQQEGQoKEgABDQQEGQoKIQAQAEQfAA==.刀刀好菜呀:BAEBDQQEGX8UAAIQAAsMVhWAAABCAgudxgAAAwBYAJ7GAAABACcAn8YAAAMAQAGgxgAAAgAuAKHGAAACAE0AosYAAAMAUQCjxgAAAQAqAKTGAAACAA8ApcYAAAEALgCmxgAAAQAbAafGAAABABcAEAALDFYVgAAAQgILncYAAAMAWACexgAAAQAnAJ/GAAADAEABoMYAAAIALgChxgAAAgBNAKLGAAADAFEAo8YAAAEAKgCkxgAAAgAPAKXGAAABAC4ApsYAAAEAGwGnxgAAAQAXAAENBAQZCgohABAARB8A.刀刀爱吃辣:BAEBDQQEGX8hAAIQAAsMRB8vAADJAgudxgAAAwBaAJ7GAAADAFEAn8YAAAMAJAGgxgAAAwBJAKHGAAADAFwAosYAAAMAUgCjxgAAAwA+AKTGAAADADwApcYAAAMAXwCmxgAAAwAXAafGAAADAEQAEAALDEQfLwAAyQILncYAAAMAWgCexgAAAwBRAJ/GAAADACQBoMYAAAMASQChxgAAAwBcAKLGAAADAFIAo8YAAAMAPgCkxgAAAwA8AKXGAAADAF8ApsYAAAMAFwGnxgAAAwBEAAAA.',['刘浩']='刘浩存:BAEBDQQEGX8bAAIRAAsM7iIvAAD1AgudxgAAAgBdAJ7GAAADAFcAn8YAAAMASAGgxgAAAwBbAKHGAAADAFwAosYAAAMAYQCjxgAAAgBbAKTGAAACAFcApcYAAAIASgCmxgAAAgBAAafGAAACAFgAEQALDO4iLwAA9QILncYAAAIAXQCexgAAAwBXAJ/GAAADAEgBoMYAAAMAWwChxgAAAwBcAKLGAAADAGEAo8YAAAIAWwCkxgAAAgBXAKXGAAACAEoApsYAAAIAQAGnxgAAAgBYAAENBAQZCgoeAAUALCUA.',['别惹']='别惹二德:BAEADQQDGQoKbAABDQQEGQoKCwAHAAAAAA==.别惹伍兹:BAEADQQEGQoKCwAAAA==.别惹六娃:BAEADQQDGQoKWwABDQQEGQoKCwAHAAAAAA==.别惹四猫:BAEADQQDGQoKXwABDQQEGQoKCwAHAAAAAA==.别惹小德:BAEADQQDGQoKYAABDQQEGQoKCwAHAAAAAA==.别惹老三:BAEADQQDGQoKXwABDQQEGQoKCwAHAAAAAA==.',['劳大']='劳大肘击:BAEADQQDGQoKCwABDQQDGQoKDAAHAAAAAA==.',['南波']='南波:BAEBDQQEGX8fAAMMAAsMbiE5AADsAgudxgAAAwBGAJ7GAAADAFgAn8YAAAMAHwGgxgAAAwBXAKHGAAADAFsAosYAAAMAXwCjxgAAAgBOAKTGAAADAE0ApcYAAAMAXwCmxgAAAwBTAafGAAACAE8ADAALDCsgOQAA7AILncYAAAIAQQCexgAAAgBYAJ/GAAACAAoBoMYAAAIAVgChxgAAAgBRAKLGAAACAFsAo8YAAAIATgCkxgAAAgBMAKXGAAACAFoApsYAAAIAEwGnxgAAAgBPABAACQw3HmoAAGACCZ3GAAABAEYAnsYAAAEAFwCfxgAAAQAfAaDGAAABAFcAocYAAAEAWwCixgAAAQBfAKTGAAABAE0ApcYAAAEAXwCmxgAAAQBTAQAA.南波小万:BAEBDQQEGX8ZAAIKAAwMhyEBAABxAwydxgAAAgBhAJ7GAAACAFgAn8YAAAIAGwGgxgAAAgAcAKHGAAACAGEAosYAAAIAWgCjxgAAAgBcAKTGAAACAGMApcYAAAIAUgCmxgAAAgBOAafGAAACAGMAqMYAAAMAXwAKAAwMhyEBAABxAwydxgAAAgBhAJ7GAAACAFgAn8YAAAIAGwGgxgAAAgAcAKHGAAACAGEAosYAAAIAWgCjxgAAAgBcAKTGAAACAGMApcYAAAIAUgCmxgAAAgBOAafGAAACAGMAqMYAAAMAXwABDQQEGQoKHwAMAG4hAA==.',['卡芙']='卡芙卡:BAEADQQDGQoKYAABDQQEGQoKDAAHAAAAAA==.',['图拉']='图拉楊:BAEADQQDGQoKWAABDQQEGQoKDAAHAAAAAA==.',['圣光']='圣光阿丁:BAEBDQQEGX8fAAIPAAsMcCEYAAD8AgudxgAAAwBMAJ7GAAADAGMAn8YAAAMAYwGgxgAAAwAnAKHGAAADAF8AosYAAAMAYQCjxgAAAgBWAKTGAAADAF0ApcYAAAMAYQCmxgAAAwBaAafGAAACAFwADwALDHAhGAAA/AILncYAAAMATACexgAAAwBjAJ/GAAADAGMBoMYAAAMAJwChxgAAAwBfAKLGAAADAGEAo8YAAAIAVgCkxgAAAwBdAKXGAAADAGEApsYAAAMAWgGnxgAAAgBcAAENBAQZCgoiAAMAmiUA.圣光阿丙:BAEBDQQEGX8XAAIPAAsM8BmWAAA8AgudxgAAAwBfAJ7GAAACAEkAn8YAAAMAYwGgxgAAAgBAAKHGAAACAD0AosYAAAMAVgCjxgAAAQAfAKTGAAACACwApcYAAAIASQCmxgAAAgBUAafGAAABAAMADwALDPAZlgAAPAILncYAAAMAXwCexgAAAgBJAJ/GAAADAGMBoMYAAAIAQAChxgAAAgA9AKLGAAADAFYAo8YAAAEAHwCkxgAAAgAsAKXGAAACAEkApsYAAAIAVAGnxgAAAQADAAENBAQZCgoiAAMAmiUA.圣光阿二:BAEADQQDGQoKOgABDQQEGQoKIgADAJolAA==.圣光阿大:BAEBDQQEGX8hAAISAAsMyCIUAAAuAwudxgAAAwBdAJ7GAAADAFcAn8YAAAMAPQGgxgAAAwBcAKHGAAADAFUAosYAAAMAXACjxgAAAwBQAKTGAAADAFwApcYAAAMAVwCmxgAAAwBcAafGAAADAFQAEgALDMgiFAAALgMLncYAAAMAXQCexgAAAwBXAJ/GAAADAD0BoMYAAAMAXAChxgAAAwBVAKLGAAADAFwAo8YAAAMAUACkxgAAAwBcAKXGAAADAFcApsYAAAMAXAGnxgAAAwBUAAENBAQZCgoiAAMAmiUA.',['壁冬']='壁冬:BAEBDQQEGX8cAAIEAAsMUyMBAABbAwudxgAAAwBfAJ7GAAACAGMAn8YAAAMAYgGgxgAAAwBWAKHGAAADAF0AosYAAAMAXACjxgAAAQA8AKTGAAADAF4ApcYAAAMAYwCmxgAAAwBjAafGAAABAFIABAALDFMjAQAAWwMLncYAAAMAXwCexgAAAgBjAJ/GAAADAGIBoMYAAAMAVgChxgAAAwBdAKLGAAADAFwAo8YAAAEAPACkxgAAAwBeAKXGAAADAGMApsYAAAMAYwGnxgAAAQBSAAAA.',['天幽']='天幽暗灵:BAEADQQEGQkKCQABDQQEGQoKDAAHAAAAAA==.',['妮小']='妮小多:BAEBDQQEGX8gAAIFAAsMvCULAABqAwudxgAAAwBiAJ7GAAADAGEAn8YAAAMAWAGgxgAAAwBhAKHGAAADAF8AosYAAAMAYgCjxgAAAwBbAKTGAAADAF8ApcYAAAMAYgCmxgAAAwBiAafGAAACAFoABQALDLwlCwAAagMLncYAAAMAYgCexgAAAwBhAJ/GAAADAFgBoMYAAAMAYQChxgAAAwBfAKLGAAADAGIAo8YAAAMAWwCkxgAAAwBfAKXGAAADAGIApsYAAAMAYgGnxgAAAgBaAAENBAQZCgogAA4A3BUA.',['妳喝']='妳喝醉了没:BAEADQQEGQoKCwABDQQEGQoKIwACAHMcAA==.妳喝醉了没丶:BAEBDQQEGX8jAAMCAAwMcxwhAAAnAgydxgAAAwBWAJ7GAAADAFUAn8YAAAMANAGgxgAAAwBTAKHGAAADACQAosYAAAMAXQCjxgAAAwBQAKTGAAADAGAApcYAAAMAMACmxgAAAwBWAafGAAADAE0AqMYAAAIAKwACAAsMeBkhAAAnAgudxgAAAwBWAJ7GAAADAFUAn8YAAAMANAGgxgAAAwBTAKHGAAADACQAosYAAAMAXQCjxgAAAwBQAKXGAAABAAoApsYAAAMAVgGnxgAAAwBNAKjGAAACACsAEwACDEocNwAAlQACpMYAAAMAYAClxgAAAgAwAAAA.妳喝醉了没丷:BAEADQQDGQoKYAABDQQEGQoKIwACAHMcAA==.',['安度']='安度因洛薩:BAEADQQEGQoKDAAAAA==.',['小南']='小南波万:BAEBDQQEGX8WAAIPAAsMkB48AACzAgudxgAAAgBZAJ7GAAACAFkAn8YAAAIAFwGgxgAAAgAmAKHGAAACAFUAosYAAAIAXgCjxgAAAgA9AKTGAAACAEgApcYAAAIAYACmxgAAAgAsAafGAAACAD0ADwALDJAePAAAswILncYAAAIAWQCexgAAAgBZAJ/GAAACABcBoMYAAAIAJgChxgAAAgBVAKLGAAACAF4Ao8YAAAIAPQCkxgAAAgBIAKXGAAACAGAApsYAAAIALAGnxgAAAgA9AAENBAQZCgofAAwAbiEA.',['小默']='小默:BAEBDQQEGX8fAAMNAAsMeSMHAABxAAudxgAAAwBbAJ7GAAADAGEAn8YAAAMASwGgxgAAAwBCAKHGAAADAFwAosYAAAMAYQCjxgAAAwBhAKTGAAADAFkApcYAAAMAXgCmxgAAAwBaAafGAAABADIAAwAKDBUjMgAAyQIKncYAAAMAWwCexgAAAwBhAJ/GAAADAEsBoMYAAAMAQgChxgAAAwBcAKLGAAADAGEApMYAAAMAWQClxgAAAwBeAKbGAAADAFoBp8YAAAEAMgANAAEMNyYHAABxAAGjxgAAAwBhAAENBAQZCgogAA4A3BUA.',['尘星']='尘星:BAEADQQDGQoKOAABDQQEGQoKHQAFALwjAA==.',['就多']='就多听:BAEADQQEGQoKCwAAAA==.就多练:BAEADQQDGQoKUgABDQQEGQoKCwAHAAAAAA==.',['屁小']='屁小屁:BAEBDQQEGX8eAAIIAAsMQyUpAABmAwudxgAAAwBjAJ7GAAACAFoAn8YAAAMAWgGgxgAAAwBbAKHGAAADAGMAosYAAAMAXwCjxgAAAgBfAKTGAAADAFwApcYAAAMAYgCmxgAAAwBJAafGAAACAGAACAALDEMlKQAAZgMLncYAAAMAYwCexgAAAgBaAJ/GAAADAFoBoMYAAAMAWwChxgAAAwBjAKLGAAADAF8Ao8YAAAIAXwCkxgAAAwBcAKXGAAADAGIApsYAAAMASQGnxgAAAgBgAAENBAQZCgoeAAUALCUA.屁小浪:BAEBDQQEGX8YAAIRAAsMGx86AADlAgudxgAAAgBUAJ7GAAACAFEAn8YAAAIAWwGgxgAAAgBbAKHGAAACAFgAosYAAAIARgCjxgAAAQBiAKTGAAADACEApcYAAAMAWACmxgAAAwA6AafGAAACAEkAEQALDBsfOgAA5QILncYAAAIAVACexgAAAgBRAJ/GAAACAFsBoMYAAAIAWwChxgAAAgBYAKLGAAACAEYAo8YAAAEAYgCkxgAAAwAhAKXGAAADAFgApsYAAAMAOgGnxgAAAgBJAAENBAQZCgoeAAUALCUA.',['干涉']='干涉奶骑:BAEADQQEGQoKCgABDQQEGQoKIgADAJolAA==.',['无法']='无法言说:BAEADQQDGQoKDAAAAA==.',['昕庭']='昕庭:BAEBDQQEGX8gAAMOAAsM3BVIAAD7AAudxgAAAgBSAJ7GAAADAEwAn8YAAAMAVgGgxgAAAwA5AKHGAAADACsAosYAAAMAFwCjxgAAAwAkAKTGAAADADAApcYAAAMATwCmxgAAAwBEAafGAAADAFIAFAAHDLEPkAEAUgEHnsYAAAEAHwCfxgAAAgBWAaDGAAADADkAocYAAAMAKwCixgAAAwAXAKPGAAADACQApMYAAAMAMAAOAAYMDx9IAAD7AAadxgAAAgBSAJ7GAAACAEwAn8YAAAEASAGlxgAAAwBPAKbGAAADAEQBp8YAAAMAUgAAAA==.',['曹彦']='曹彦祖:BAEADQQEGQoKEwABDQQEGQoKHQAIAB8jAA==.',['橙兮']='橙兮:BAEBDQQEGX8jAAIPAAwM+g4xAQCxAQydxgAAAwAbAJ7GAAADAA4An8YAAAMAPwGgxgAAAwA6AKHGAAADACAAosYAAAMAHACjxgAAAwAoAKTGAAADAEwApcYAAAMAFgCmxgAAAwBWAafGAAADADMAqMYAAAIALAAPAAwM+g4xAQCxAQydxgAAAwAbAJ7GAAADAA4An8YAAAMAPwGgxgAAAwA6AKHGAAADACAAosYAAAMAHACjxgAAAwAoAKTGAAADAEwApcYAAAMAFgCmxgAAAwBWAafGAAADADMAqMYAAAIALAAAAA==.',['欧罗']='欧罗巴小土豆:BAEBDQQEGX8UAAIFAAkMsBZxAQD0AQmdxgAAAwBEAJ7GAAABACgAn8YAAAMAQgGgxgAAAwA/AKHGAAADAEIAosYAAAMASQCkxgAAAgA5AKXGAAABACQApsYAAAEABwEFAAkMsBZxAQD0AQmdxgAAAwBEAJ7GAAABACgAn8YAAAMAQgGgxgAAAwA/AKHGAAADAEIAosYAAAMASQCkxgAAAgA5AKXGAAABACQApsYAAAEABwEAAA==.欧罗巴小美人:BAEADQQEGQkKEQABDQQEGQkKFAAFALAWAA==.欧罗巴神手:BAEADQQEGQYKCwABDQQEGQkKFAAFALAWAA==.欧罗巴铁卫士:BAEADQQEGQYKDwABDQQEGQkKFAAFALAWAA==.',['淺小']='淺小茉:BAEBDQQEGX8ZAAMSAAsMTiIZAAAeAwudxgAAAwBgAJ7GAAACAFYAn8YAAAMAYAGgxgAAAwBRAKHGAAACAF4AosYAAAMAWQCjxgAAAQBMAKTGAAACAFQApcYAAAMAXQCmxgAAAgAYAafGAAABACsAEgAKDE4iGQAAHgMKncYAAAMAYACexgAAAgBWAJ/GAAADAGABoMYAAAMAUQChxgAAAgBeAKLGAAADAFkAo8YAAAEATACkxgAAAgBUAKXGAAADAF0ApsYAAAIAGAEUAAEMAAAOAwAAAAGnxgAAAQA5AAAA.',['澄兮']='澄兮:BAEBDQQEGX8jAAIPAAwM0x0iAADrAgydxgAAAwBSAJ7GAAADADYAn8YAAAMAGAGgxgAAAwA6AKHGAAADAFkAosYAAAMAXwCjxgAAAwBRAKTGAAADAE0ApcYAAAMAMwCmxgAAAwBMAafGAAADAEIAqMYAAAIAXwAPAAwM0x0iAADrAgydxgAAAwBSAJ7GAAADADYAn8YAAAMAGAGgxgAAAwA6AKHGAAADAFkAosYAAAMAXwCjxgAAAwBRAKTGAAADAE0ApcYAAAMAMwCmxgAAAwBMAafGAAADAEIAqMYAAAIAXwABDQQEGQoKIwAPAPoOAA==.',['澄曦']='澄曦:BAEBDQQEGX8fAAIUAAsM+h4tAADPAgudxgAAAwBUAJ7GAAADAEgAn8YAAAMANAGgxgAAAwA1AKHGAAADAGIAosYAAAMAUgCjxgAAAgBbAKTGAAADADgApcYAAAMAXgCmxgAAAwBfAafGAAACAEkAFAALDPoeLQAAzwILncYAAAMAVACexgAAAwBIAJ/GAAADADQBoMYAAAMANQChxgAAAwBiAKLGAAADAFIAo8YAAAIAWwCkxgAAAwA4AKXGAAADAF4ApsYAAAMAXwGnxgAAAgBJAAENBAQZCgojAA8A+g4A.',['澄熙']='澄熙:BAEBDQQEGX8iAAIPAAwMRhwsAADRAgydxgAAAwBWAJ7GAAADAFoAn8YAAAMADwGgxgAAAwA8AKHGAAADADkAosYAAAMATwCjxgAAAwBFAKTGAAADAFwApcYAAAMATACmxgAAAwBdAafGAAADAF8AqMYAAAEAJgAPAAwMRhwsAADRAgydxgAAAwBWAJ7GAAADAFoAn8YAAAMADwGgxgAAAwA8AKHGAAADADkAosYAAAMATwCjxgAAAwBFAKTGAAADAFwApcYAAAMATACmxgAAAwBdAafGAAADAF8AqMYAAAEAJgABDQQEGQoKIwAPAPoOAA==.',['猫七']='猫七丷:BAEADQQDGQoKYAABDQQEGQoKIwACAHMcAA==.',['珍娜']='珍娜普罗德摩:BAEADQQEGQkKEgABDQQEGQoKDAAHAAAAAA==.',['白发']='白发双马尾:BAEBDQQEGX8iAAIMAAwM5B8WAABoAwydxgAAAwBhAJ7GAAADAEkAn8YAAAMAXAGgxgAAAwBdAKHGAAADAFoAosYAAAMAWwCjxgAAAwBPAKTGAAADAF4ApcYAAAMAXACmxgAAAwBDAafGAAADAFUAqMYAAAEAFQAMAAwM5B8WAABoAwydxgAAAwBhAJ7GAAADAEkAn8YAAAMAXAGgxgAAAwBdAKHGAAADAFoAosYAAAMAWwCjxgAAAwBPAKTGAAADAF4ApcYAAAMAXACmxgAAAwBDAafGAAADAFUAqMYAAAEAFQAAAA==.',['皮小']='皮小小:BAEBDQQEGX8mAAISAAsMSSMcAAAKAwudxgAABABcAJ7GAAADAF0An8YAAAQASQGgxgAABABaAKHGAAAEAFoAosYAAAQAXwCjxgAAAwBIAKTGAAAEAFoApcYAAAQAYQCmxgAAAwBTAafGAAABADYAEgALDEkjHAAACgMLncYAAAQAXACexgAAAwBdAJ/GAAAEAEkBoMYAAAQAWgChxgAABABaAKLGAAAEAF8Ao8YAAAMASACkxgAABABaAKXGAAAEAGEApsYAAAMAUwGnxgAAAQA2AAENBAQZCgoeAAUALCUA.皮小痞:BAEADQQDGQoKPAABDQQEGQoKHgAFACwlAA==.',['知莫']='知莫问:BAEADQQEGQoKCwABDQQEGQoKIwAPAPoOAA==.',['老娘']='老娘来了:BAEBDQQEGX8hAAIFAAwMUyANAABdAwydxgAAAwBgAJ7GAAADAFgAn8YAAAMAKgGgxgAAAwBYAKHGAAADAGIAosYAAAMAYgCjxgAAAgBVAKTGAAADAGMApcYAAAMAWQCmxgAAAwBgAafGAAADAD0AqMYAAAEAAQAFAAwMUyANAABdAwydxgAAAwBgAJ7GAAADAFgAn8YAAAMAKgGgxgAAAwBYAKHGAAADAGIAosYAAAMAYgCjxgAAAgBVAKTGAAADAGMApcYAAAMAWQCmxgAAAwBgAafGAAADAD0AqMYAAAEAAQABDQQEGQoKIgADAJolAA==.',['老子']='老子巨帅:BAEADQQEGQcKCgABDQQEGQoKIgADAJolAA==.',['老曹']='老曹:BAEBDQQEGX8XAAIDAAsMvx8lAADpAgudxgAAAgBAAJ7GAAACAGEAn8YAAAMAHwGgxgAAAwBhAKHGAAACAFQAosYAAAMAYQCjxgAAAQAoAKTGAAACAEoApcYAAAIAXACmxgAAAgBUAafGAAABAFAAAwALDL8fJQAA6QILncYAAAIAQACexgAAAgBhAJ/GAAADAB8BoMYAAAMAYQChxgAAAgBUAKLGAAADAGEAo8YAAAEAKACkxgAAAgBKAKXGAAACAFwApsYAAAIAVAGnxgAAAQBQAAENBAQZCgodAAgAHyMA.',['老默']='老默吃鱼:BAEBDQQEGX8eAAMIAAsMRyQ4AAA/AwudxgAAAwBgAJ7GAAACAFoAn8YAAAMAVgGgxgAAAwBhAKHGAAADAF4AosYAAAMAYACjxgAAAgBRAKTGAAADAFYApcYAAAMAYwCmxgAAAwBjAafGAAACAFAACAALDEckOAAAPwMLncYAAAMAYACexgAAAgBaAJ/GAAADAFYBoMYAAAMAYQChxgAAAwBeAKLGAAADAGAAo8YAAAIAUQCkxgAAAgBWAKXGAAADAGMApsYAAAMAYwGnxgAAAgBQABUAAQwrA+wBAA8AAaTGAAABAAgAAQ0EBBkKCiAADgDcFQA=.',['自在']='自在仙:BAEBDQQEGX8hAAMJAAsMwCEVAAD8AgudxgAAAwBfAJ7GAAADAF8An8YAAAMAXAGgxgAAAwBbAKHGAAADAFMAosYAAAMAYQCjxgAAAwBGAKTGAAADAEoApcYAAAMAUgCmxgAAAwBQAafGAAADAEsACQAJDMAhFQAA/AIJncYAAAEAXwCexgAAAgBfAJ/GAAACAFwBoMYAAAIAWwChxgAAAgBTAKLGAAACAGEAo8YAAAIARgCkxgAAAgBKAKXGAAABAFIACgALDDgXhAAABwILncYAAAIAQQCexgAAAQBDAJ/GAAABABQBoMYAAAEACwChxgAAAQBhAKLGAAABACEAo8YAAAEAMACkxgAAAQA9AKXGAAACAFgApsYAAAMAPgGnxgAAAwBLAAENBAQZCgojAA8A+g4A.',['致命']='致命小琪宝:BAEADQQEGQgKEAABDQQEGQkKFAAFALAWAA==.',['舞笛']='舞笛的甜菜:BAEADQQDGQoKMAABDQQEGQoKIwACAHMcAA==.',['萬萬']='萬萬没想到:BAEBDQQEGX8UAAIFAAsMdSEiAAAWAwudxgAAAgBXAJ7GAAACAFoAn8YAAAIAKgGgxgAAAgBiAKHGAAACAFwAosYAAAIATgCjxgAAAQAwAKTGAAACAF8ApcYAAAIAXgCmxgAAAgBdAafGAAABAE8ABQALDHUhIgAAFgMLncYAAAIAVwCexgAAAgBaAJ/GAAACACoBoMYAAAIAYgChxgAAAgBcAKLGAAACAE4Ao8YAAAEAMACkxgAAAgBfAKXGAAACAF4ApsYAAAIAXQGnxgAAAQBPAAENBAQZCgofAAwAbiEA.',['装逼']='装逼王丶:BAEBDQQEGX8ZAAIBAAsMWyUIAABgAwudxgAAAwBbAJ7GAAABAGIAn8YAAAIAHQGgxgAAAwBdAKHGAAADAF4AosYAAAMAYwCjxgAAAgBhAKTGAAACAFwApcYAAAMAYQCmxgAAAgBfAafGAAABADYAAQALDFslCAAAYAMLncYAAAMAWwCexgAAAQBiAJ/GAAACAB0BoMYAAAMAXQChxgAAAwBeAKLGAAADAGMAo8YAAAIAYQCkxgAAAgBcAKXGAAADAGEApsYAAAIAXwGnxgAAAQA2AAENBAQZCgoeAAUALCUA.',['问你']='问你喝醉了没:BAEBDQQEGX8WAAIRAAsMUSEnAAAKAwudxgAAAgBQAJ7GAAACAGAAn8YAAAIAYwGgxgAAAgBfAKHGAAACAF0AosYAAAIAVQCjxgAAAgA/AKTGAAACAFIApcYAAAIAVACmxgAAAgBgAafGAAACAD0AEQALDFEhJwAACgMLncYAAAIAUACexgAAAgBgAJ/GAAACAGMBoMYAAAIAXwChxgAAAgBdAKLGAAACAFUAo8YAAAIAPwCkxgAAAgBSAKXGAAACAFQApsYAAAIAYAGnxgAAAgA9AAENBAQZCgojAAIAcxwA.',['阿拉']='阿拉索阿拉索:BAEBDQQEGX8iAAIDAAwMmiUBAADwAwydxgAAAwBiAJ7GAAADAGMAn8YAAAMAWAGgxgAAAwBjAKHGAAADAGMAosYAAAMAYwCjxgAAAwBiAKTGAAADAGIApcYAAAMAYwCmxgAAAwBfAafGAAADAFsAqMYAAAEASAADAAwMmiUBAADwAwydxgAAAwBiAJ7GAAADAGMAn8YAAAMAWAGgxgAAAwBjAKHGAAADAGMAosYAAAMAYwCjxgAAAwBiAKTGAAADAGIApcYAAAMAYwCmxgAAAwBfAafGAAADAFsAqMYAAAEASAAAAA==.',['零玖']='零玖叁零丶:BAEADQQDGQoKXQABDQQEGQoKCwAHAAAAAA==.零玖叁零丿:BAEADQQDGQoKRgABDQQEGQoKCwAHAAAAAA==.零玖叁零灬:BAEADQQDGQoKCwABDQQEGQoKCwAHAAAAAA==.',['麥小']='麥小兜:BAEADQQDGQoKGAABDQQEGQoKHgAFACwlAA==.',['默小']='默小垚:BAEBDQQEGX8ZAAIWAAsMxR2SAACjAgudxgAAAgAtAJ7GAAADAFsAn8YAAAMAFQGgxgAAAgA9AKHGAAACAFkAosYAAAMAWgCjxgAAAgBIAKTGAAACAFMApcYAAAIATACmxgAAAgBVAafGAAACADUAFgALDMUdkgAAowILncYAAAIALQCexgAAAwBbAJ/GAAADABUBoMYAAAIAPQChxgAAAgBZAKLGAAADAFoAo8YAAAIASACkxgAAAgBTAKXGAAACAEwApsYAAAIAVQGnxgAAAgA1AAENBAQZCgogAA4A3BUA.默小壮:BAEBDQQEGX8YAAMJAAsMwQ6fAAD7AQudxgAAAwBOAJ7GAAACABoAn8YAAAMAIQGgxgAAAgBFAKHGAAACABEAosYAAAMAQQCjxgAAAgAEAKTGAAACACIApcYAAAIABQCmxgAAAgBQAafGAAABAE4ACQAJDMEOnwAA+wEJncYAAAIATgCexgAAAQAaAJ/GAAACACEBoMYAAAIARQChxgAAAQARAKLGAAACAEEAo8YAAAEABACkxgAAAQAiAKXGAAABAAUACgAKDBYIZAEABgEKncYAAAEALwCexgAAAQAuAJ/GAAABABYBocYAAAEABwCixgAAAQAIAKPGAAABAAMApMYAAAEAFgClxgAAAQAJAKbGAAACACsBp8YAAAEAHgABDQQEGQoKIAAOANwVAA==.默小妮:BAEBDQQEGX8eAAIFAAsMZSMaAAAqAwudxgAAAwBcAJ7GAAADAFEAn8YAAAMAFAGgxgAAAwBgAKHGAAADAGEAosYAAAMAYQCjxgAAAgBFAKTGAAADAFsApcYAAAMAYgCmxgAAAwBjAafGAAABACQABQALDGUjGgAAKgMLncYAAAMAXACexgAAAwBRAJ/GAAADABQBoMYAAAMAYAChxgAAAwBhAKLGAAADAGEAo8YAAAIARQCkxgAAAwBbAKXGAAADAGIApsYAAAMAYwGnxgAAAQAkAAENBAQZCgogAA4A3BUA.默小宸:BAEBDQQEGX8fAAMXAAsMdSIEAAAXAwudxgAAAwBeAJ7GAAADAFYAn8YAAAMAXwGgxgAAAwBVAKHGAAADAFMAosYAAAMAXQCjxgAAAgBKAKTGAAADAFwApcYAAAMAXwCmxgAAAwBgAafGAAACAEgAFwALDHUiBAAAFwMLncYAAAMAXgCexgAAAwBWAJ/GAAADAF8BoMYAAAMAVQChxgAAAwBTAKLGAAADAF0Ao8YAAAIASgCkxgAAAgBcAKXGAAADAF8ApsYAAAMAYAGnxgAAAgBIAAIAAQx8HaIBAEsAAaTGAAABAEsAAQ0EBBkKCiAADgDcFQA=.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end