---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 千古
--- DateTime: 2022/9/10 23:13
---







----------------------------------
-- Global Ignore List Variables --
----------------------------------

PTT_Loaded				= false
local gotLoaded			= false
local gotEntering		= false
local gotGroup          = IsInGroup()
local groupWarning      = {}

local function ResetPlayTagDB()

    PlayTagDB = {
        playTagMap		= {},
        playerList      = {},
        playerDateMap   = {},
        playerClassMap  = {},
        bnetPlayerMap   = {},
        playerBnetMap   = {},
        negativeTag     = {"傻逼","傻笔","傻B","傻b","SB","挂机","不上YY","YY不在","黑G","黑金","喷人","骗子","演员","爆粗","黑装备","混子"}

    }

    --GlobalIgnoreImported = false

    --ResetSpamFilters()
end






function PTThasNegativeTag (name)

    local warn_tag={}

    if not name then return warn_tag end


    if PlayTagDB.playTagMap[name] then

        for k2,v2 in pairs(PlayTagDB.negativeTag) do

            if string.match(PlayTagDB.playTagMap[name],v2) then
               -- print(PlayTagDB.playTagMap[name])
                warn_tag[name]=PlayTagDB.playTagMap[name]
            end

        end

    end



    return warn_tag
end




local function ShowMsg (msg)
    print ("|cff33ff99Private Tailor Tag: |cffffffff" .. (msg or "Critical error"))
end




local function ApplicationStartup(self)

    if PTT_Loaded == true or safeToLoad == false then
        return
    end

    ShowMsg("打开配置页面请输入 /PTT")

    --faction = UnitFactionGroup("player")

    if PlayTagDB == nil then
        ResetPlayTagDB()
    end

    -- set missing defaults or upgrade if needed
    loadedTime = GetTime()

    --SyncIgnoreList(GlobalIgnoreDB.chatmsg == nil or GlobalIgnoreDB.chatmsg == false)

    PTT_Loaded = true

    --self:UnregisterEvent("IGNORELIST_UPDATE")
    self:UnregisterEvent("PLAYER_ENTERING_WORLD")
    self:UnregisterEvent("ADDON_LOADED")

    -- Synchronize spam filters with defaults, if enabled


    --鼠标提示
    GameTooltip:HookScript("OnTooltipSetUnit", function(self)

        --print("OnTooltipSetUnit")
        local _, unit = self:GetUnit()
        local systemTag=""
        local tag = ""
        --print(unit)
        if UnitExists(unit)  then
            WP_MouseoverName = UnitName(unit)
            --print(WP_MouseoverName)


            systemTag=PTTSystemTagList[addServer(WP_MouseoverName)]
            tag = PlayTagDB.playTagMap[addServer(WP_MouseoverName)]

            --print(systemTag)


            if tag or systemTag then
                GameTooltip:AddLine("|cff33ff99标签：", 255, 209, 0)
                if systemTag then
                    GameTooltip:AddLine(systemTag)
                end

                --todo:换行，可以按照逗号、顿号 换行
                if tag then
                GameTooltip:AddLine(tag, 255, 209, 0,true)
                end

                --if PlayTagDB.playerBnetMap[addServer(WP_MouseoverName)] and PlayTagDB.bnetPlayerMap



            end


            --战网其他账号下标记
            if(PlayTagDB.playerBnetMap[addServer(WP_MouseoverName)]) then
                local addBnet = true
                local bnet = PlayTagDB.playerBnetMap[addServer(WP_MouseoverName)]


                for k,v in pairs(PlayTagDB.bnetPlayerMap[bnet]) do

                    if v~="" then
                        if k~=addServer(WP_MouseoverName) then
                            if addBnet then
                                GameTooltip:AddLine("同战网其他账号标签：", 0, 204, 221,true)
                                addBnet=false
                            end
                            GameTooltip:AddLine("|cff33ff99"..removeServer(k).." : ".."|cfffff143"..v, 255, 209, 0,true)
                        end


                    end

                end

            end

            --dstr = load_ctop(WP_MouseoverName.."_2")
            --if dstr then
            --    GameTooltip:AddLine(dstr, 255, 209, 0)
            --end

            GameTooltip:Show()
        end
    end)


end






-------------------
-- EVENT HANDLER --
-------------------

local function EventHandler (self, event, sender, arg1, ...)

    --print ("DEBUG event=".. (event or "nil"))
    --print ("DEBUG event=".. (event or "nil") .. " sender=" .. (sender or "nil"))

    --if (event == "CHANNEL_INVITE_REQUEST") or (event == "CHAT_MSG_CHANNEL_NOTICE_USER") then
    --	print ("DEBUG RECEIVED CHANNEL INVITE REQUEST: " .. (arg1 or "nil"))
    --end
    --print("sender:"..sender)
    if event == "ADDON_LOADED" then
        gotLoaded = true
    end

    --if event == "IGNORELIST_UPDATE" then
    --    gotUpdate = true
    --end

    if event == "PLAYER_ENTERING_WORLD" then
        gotEntering = true
    end

    if event == "FRIENDLIST_UPDATE" then
        PTTupdatePlayerBnetID()

    end

    if event == "GROUP_ROSTER_UPDATE" then

        --print("进入 GROUP_ROSTER_UPDATE")
        if gotGroup == true and not IsInGroup() then
            gotGroup     = false
            groupWarning = {}
        elseif gotGroup == false and IsInGroup() then
            gotGroup = true
        elseif gotGroup == true then
            local prefix  = IsInRaid() and "raid" or "party"
            local name    = ""
            local doWarn  = false

            for count = 1, GetNumGroupMembers() do

                --print("----",count)
                name = GetUnitName(prefix..count, true)

                if name then
                    name = addServer(name)

                    if table_length(PTThasNegativeTag(name)) > 0 then
                        doWarn = true
                        groupWarning[name]=PTThasNegativeTag(name)[name]
                    end
                end
            end


            if doWarn then
                local nameList = ""

                for k,v in pairs(groupWarning) do
                    nameList = nameList .. "\n" .. k .." : "..v
                end

                ShowMsg(format("警告: 这个团队有 %d 个玩家存在负面标签: |cffffff00%s", table_length(groupWarning), nameList))

                StaticPopup_Show("PTT_PARTYWARN", table_length(groupWarning), nameList)
            end
        end
    end

    if event == "PARTY_INVITE_REQUEST" and PTT_Loaded == true then

        --print("进入 PARTY_INVITE_REQUEST")
        sender = addServer(sender)

        if PTThasNegativeTag(sender)[sender] then
            --DeclineGroup()
            ShowMsg("警告：来自存在负面评价玩家的邀请 " .. sender .."："..PlayTagDB.playTagMap[sender])

            StaticPopup_Show("PARTY_INVITE_WARN",sender,PlayTagDB.playTagMap[sender])
        end

        return
    end


    if gotLoaded == true and gotEntering == true then
        if safeToLoad ~= true then

            timer = 0

            self:SetScript("OnUpdate", function(Self, elapsed)

                timer = timer + elapsed

                if timer < 5 then
                    --print(timer)
                    return
                end

                self:SetScript("OnUpdate", nil)
                self:Hide()

                safeToLoad = true
            end)

        end

        safeToLoad = true
    end
    --print(safeToLoad)
    if safeToLoad == true then
        ApplicationStartup(self)

    end
end








function SlashCmdList.PTNOTE (msg)

    PTTGUI()

end








-----------------------------
-- PlayTag Main --
-----------------------------

PTTFRAME = CreateFrame("FRAME")

PTTFRAME:RegisterEvent("PLAYER_ENTERING_WORLD")
PTTFRAME:RegisterEvent("ADDON_LOADED")
--PTFRAME:RegisterEvent("IGNORELIST_UPDATE")
PTTFRAME:RegisterEvent("PARTY_INVITE_REQUEST")
--PTFRAME:RegisterEvent("DUEL_REQUESTED")
PTTFRAME:RegisterEvent("GROUP_ROSTER_UPDATE")
PTTFRAME:RegisterEvent("FRIENDLIST_UPDATE")
--PTFRAME:RegisterEvent("CHANNEL_INVITE_REQUEST")

SLASH_PTNOTE1		= "/ptt"
SLASH_PTNOTE2		= "/PrivateTailorTag"
SLASH_PTNOTE3		= "/PTT"

PTTFRAME:SetScript("OnEvent", EventHandler)




