---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 千古
--- DateTime: 2022/9/10 22:55
---

local function PTTUnitMenu (dropdownMenu, which, unit, name, userData, ...)

    --print (which,unit,name,userData)

    if (UIDROPDOWNMENU_MENU_LEVEL > 1) then
        return
    end

    --好友列表
    if (which and (which == "FRIEND")) then

        local info = UIDropDownMenu_CreateInfo()

        info.notCheckable = 1
        info.func = function() StaticPopup_Show("PTT_EDIT_TAG",name) end
        --点击功能，待添加
        --info.func = function() C_FriendList.AddOrDelIgnore(addServer(name)) GILUpdateUI(true) end

        info.text="查看标签"

        UIDropDownMenu_AddButton(info, UIDROPDOWNMENU_MENU_LEVEL)




    --其他地方
    elseif (which and (which == "PLAYER" or which == "RAID_PLAYER" or which == "PARTY" or which == "TARGET")) then

        local target, server = UnitName("target")

        if server then
            if server == "" then
                addServer(target)
            else
                target = target .. "-"..server
            end
        end

        --首字母大写？
        target = Proper(target, true)

        DropDownList1.numButtons = max(0, DropDownList1.numButtons - 1)


        ----目的是为了隔行
        --local info = UIDropDownMenu_CreateInfo()
        --info.text = "---------------"
        --info.notCheckable = true
        --info.disabled = true
        --UIDropDownMenu_AddButton(info, UIDROPDOWNMENU_MENU_LEVEL)

        local info = UIDropDownMenu_CreateInfo()

        info.notCheckable = 1


        if target then
            info.func = function() StaticPopup_Show("PTT_EDIT_TAG",target) end


            info.text= "查看标签"

        end

        UIDropDownMenu_AddButton(info, UIDROPDOWNMENU_MENU_LEVEL)

        --这个标签貌似没有用
        local info = UIDropDownMenu_CreateInfo()
        info.text = "取消"
        info.notCheckable = 1
        UIDropDownMenu_AddButton(info, UIDROPDOWNMENU_MENU_LEVEL)
    end
end

hooksecurefunc("UnitPopup_ShowMenu", PTTUnitMenu)