---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 千古
--- DateTime: 2022/9/16 01:28
---
PTTSystemTagList= {
    --["千古老弓-光芒"] = "|cff33ccff这|cff99ff66是|cffffcc66系|cffff6699统|cffff33ff签",
    ["屁屁打死你-光芒"] = "|cff33ccff一|cff99ff66一|cffffa400一|cffff6699一|cffff0097一",
    ["小坏蛋打死你-光芒"] = "|cff33ccff一|cff99ff66一|cffffa400一|cffff6699一|cffff0097一",
    ["与寂寞有小染-光芒"] = "|cff33ccff一|cff99ff66一|cffffa400一|cffff6699一|cffff0097一",
    ["小丸子打死你-光芒"] = "|cff33ccff一|cff99ff66一|cffffa400一|cffff6699一|cffff0097一",
    ["丸子打死你-光芒"] = "|cff33ccff一|cff99ff66一|cffffa400一|cffff6699一|cffff0097一",



    ["千古-光芒"] = "|cffff0097屁|cffff6699屁|cffffcc66的|cff99ff66千|cff33ccff古",
    ["千丨古-光芒"] = "|cffff0097屁|cffff6699屁|cffffcc66的|cff99ff66千|cff33ccff古"
}


PTTSystemNotTagList= {

    ["屁屁打死你-光芒"] = "1",
    ["小坏蛋打死你-光芒"] = "1",
    ["与寂寞有小染-光芒"] = "1",
    ["小丸子打死你-光芒"] = "1",
    ["丸子打死你-光芒"] = "1",

}

