if not Talented_Data then return end

Talented_Data.PRIEST = {
	{
		numtalents = 22,
		talents = {
			{
				info = {
					name = "Unbreakable Will",
					tips = "Increases your chance to resist Stun, Fear, and Silence effects by an additional %d%%.",
					tipValues = {{3}, {6}, {9}, {12}, {15}},
					column = 2,
					row = 1,
					icon = 135995,
					ranks = 5,
				},
			}, -- [1]
			{
				info = {
					name = "Wand Specialization",
					tips = "Increases your damage with Wands by %d%%.",
					tipValues = {{5}, {10}, {15}, {20}, {25}},
					column = 3,
					row = 1,
					icon = 135463,
					ranks = 5,
				},
			}, -- [2]
			{
				info = {
					name = "Silent Resolve",
					tips = "Reduces the threat generated by your Holy and Discipline spells by %d%% and reduces the chance your spells will be dispelled by %d%%.",
					tipValues = {{4, 4}, {8, 8}, {12, 12}, {16, 16}, {20, 20}},
					column = 1,
					row = 2,
					icon = 136053,
					ranks = 5,
				},
			}, -- [3]
			{
				info = {
					name = "Improved Power Word: Fortitude",
					tips = "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by %d%%.",
					tipValues = {{15}, {30}},
					column = 2,
					row = 2,
					icon = 135987,
					ranks = 2,
				},
			}, -- [4]
			{
				info = {
					name = "Improved Power Word: Shield",
					tips = "Increases the damage absorbed by your Power Word: Shield by %d%%.",
					tipValues = {{5}, {10}, {15}},
					column = 3,
					row = 2,
					icon = 135940,
					ranks = 3,
				},
			}, -- [5]
			{
				info = {
					name = "Martyrdom",
					tips = "Gives you a %d%% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike.  The Focused Casting effect prevents you from losing casting time when taking damage while casting Priest spells and increases resistance to Interrupt effects by %d%%.",
					tipValues = {{50, 10}, {100, 20}},
					column = 4,
					row = 2,
					icon = 136107,
					ranks = 2,
				},
			}, -- [6]
			{
				info = {
					name = "Absolution",
					tips = "Reduces the mana cost of your Dispel Magic, Cure Disease, Abolish Disease and Mass Dispel spells by %d%%.",
					tipValues = {{5}, {10}, {15}},
					column = 1,
					row = 3,
					icon = 135868,
					ranks = 3,
				},
			}, -- [7]
			{
				info = {
					tips = "When activated, reduces the mana cost of your next spell by 100% and increases its critical effect chance by 25% if it is capable of a critical effect.",
					name = "Inner Focus",
					row = 3,
					column = 2,
					exceptional = 1,
					icon = 135863,
					ranks = 1,
				},
			}, -- [8]
			{
				info = {
					name = "Meditation",
					tips = "Allows %d%% of your mana regeneration to continue while casting.",
					tipValues = {{10}, {20}, {30}},
					column = 3,
					row = 3,
					icon = 136090,
					ranks = 3,
				},
			}, -- [9]
			{
				info = {
					name = "Improved Inner Fire",
					tips = "Increases the armor bonus of your Inner Fire spell by %d%%.",
					tipValues = {{10}, {20}, {30}},
					column = 1,
					row = 4,
					icon = 135926,
					ranks = 3,
				},
			}, -- [10]
			{
				info = {
					name = "Mental Agility",
					tips = "Reduces the mana cost of your instant cast spells by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}},
					column = 2,
					row = 4,
					icon = 132156,
					ranks = 5,
				},
			}, -- [11]
			{
				info = {
					name = "Improved Mana Burn",
					tips = "Reduces the casting time of your Mana Burn spell by %.1f sec.",
					tipValues = {{0.5}, {1.0}},
					column = 4,
					row = 4,
					icon = 136170,
					ranks = 2,
				},
			}, -- [12]
			{
				info = {
					name = "Mental Strength",
					tips = "Increases your maximum mana by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}},
					column = 2,
					row = 5,
					icon = 136031,
					ranks = 5,
				},
			}, -- [13]
			{
				info = {
					tips = "Holy power infuses the target, increasing their Spirit by 17 for 30 min.",
					prereqs = {
						{
							column = 3,
							row = 3,
							source = 9,
						}, -- [1]
					},
					name = "Divine Spirit",
					row = 5,
					column = 3,
					exceptional = 1,
					icon = 135898,
					ranks = 1,
				},
			}, -- [14]
			{
				info = {
					prereqs = {
						{
							column = 3,
							row = 5,
							source = 14,
						}, -- [1]
					},
					name = "Improved Divine Spirit",
					tips = "Your Divine Spirit and Prayer of Spirit spells also increase the target's spell damage and healing by an amount equal to %d%% of their total Spirit.",
					tipValues = {{5}, {10}},
					column = 4,
					row = 5,
					icon = 135898,
					ranks = 2,
				},
			}, -- [15]
			{
				info = {
					name = "Focused Power",
					tips = "Your Smite, Mind Blast and Mass Dispel spells have an additional %d%% chance to hit.  In addition, your Mass Dispel cast time is reduced by %.1f sec.",
					tipValues = {{2, 0.5}, {4, 1.0}},
					column = 1,
					row = 6,
					icon = 136158,
					ranks = 2,
				},
			}, -- [16]
			{
				info = {
					name = "Force of Will",
					tips = "Increases your spell damage by %d%% and the critical strike chance of your offensive spells by %d%%.",
					tipValues = {{1, 1}, {2, 2}, {3, 3}, {4, 4}, {5, 5}},
					column = 3,
					row = 6,
					icon = 136092,
					ranks = 5,
				},
			}, -- [17]
			{
				info = {
					name = "Focused Will",
					tips = "After taking a critical hit you gain the Focused Will effect, reducing all damage taken by %d%% and increasing healing effects on you by %d%%.  Stacks up to 3 times.  Lasts 8 sec.",
					tipValues = {{2, 4}, {3, 7}, {4, 10}},
					column = 1,
					row = 7,
					icon = 135737,
					ranks = 3,
				},
			}, -- [18]
			{
				info = {
					tips = "Infuses the target with power, increasing spell casting speed by 20% and reducing the mana cost of all spells by 20%.  Lasts 15 sec.",
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 13,
						}, -- [1]
					},
					name = "Power Infusion",
					row = 7,
					column = 2,
					exceptional = 1,
					icon = 135939,
					ranks = 1,
				},
			}, -- [19]
			{
				info = {
					name = "Reflective Shield",
					tips = "Causes %d%% of the damage absorbed by your Power Word: Shield to reflect back at the attacker.  This damage causes no threat.",
					tipValues = {{10}, {20}, {30}, {40}, {50}},
					column = 3,
					row = 7,
					icon = 135940,
					ranks = 5,
				},
			}, -- [20]
			{
				info = {
					name = "Enlightenment",
					tips = "Increases your total Stamina, Intellect and Spirit by %d%%.",
					tipValues = {{1}, {2}, {3}, {4}, {5}},
					column = 2,
					row = 8,
					icon = 135740,
					ranks = 5,
				},
			}, -- [21]
			{
				info = {
					tips = "Instantly reduces a friendly target's threat by 5%, reduces all damage taken by 40% and increases resistance to Dispel mechanics by 65% for 8 sec.",
					name = "Pain Suppression",
					row = 9,
					column = 2,
					exceptional = 1,
					icon = 135936,
					ranks = 1,
				},
			}, -- [22]
		},
		info = {
			name = "Discipline",
			background = "PriestDiscipline",
		},
	}, -- [1]
	{
		numtalents = 21,
		talents = {
			{
				info = {
					name = "Healing Focus",
					tips = "Gives you a %d%% chance to avoid interruption caused by damage while casting any healing spell.",
					tipValues = {{35}, {70}},
					column = 1,
					row = 1,
					icon = 135918,
					ranks = 2,
				},
			}, -- [1]
			{
				info = {
					name = "Improved Renew",
					tips = "Increases the amount healed by your Renew spell by %d%%.",
					tipValues = {{5}, {10}, {15}},
					column = 2,
					row = 1,
					icon = 135953,
					ranks = 3,
				},
			}, -- [2]
			{
				info = {
					name = "Holy Specialization",
					tips = "Increases the critical effect chance of your Holy spells by %d%%.",
					tipValues = {{1}, {2}, {3}, {4}, {5}},
					column = 3,
					row = 1,
					icon = 135967,
					ranks = 5,
				},
			}, -- [3]
			{
				info = {
					name = "Spell Warding",
					tips = "Reduces all spell damage taken by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}},
					column = 2,
					row = 2,
					icon = 135976,
					ranks = 5,
				},
			}, -- [4]
			{
				info = {
					name = "Divine Fury",
					tips = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by %.1f sec.",
					tipValues = {{0.1}, {0.2}, {0.3}, {0.4}, {0.5}},
					column = 3,
					row = 2,
					icon = 135971,
					ranks = 5,
				},
			}, -- [5]
			{
				info = {
					tips = "Causes an explosion of holy light around the caster, causing 29 to 34 Holy damage to all enemy targets within 10 yards and healing all party members within 10 yards for 54 to 63.  These effects cause no threat.",
					name = "Holy Nova",
					row = 3,
					column = 1,
					exceptional = 1,
					icon = 135922,
					ranks = 1,
				},
			}, -- [6]
			{
				info = {
					name = "Blessed Recovery",
					tips = "After being struck by a melee or ranged critical hit, heal %d%% of the damage taken over 6 sec.",
					tipValues = {{8}, {16}, {25}},
					column = 2,
					row = 3,
					icon = 135877,
					ranks = 3,
				},
			}, -- [7]
			{
				info = {
					name = "Inspiration",
					tips = "Increases your target's armor by %d%% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, Binding Heal, Prayer of Healing, or Circle of Healing spell.",
					tipValues = {{8}, {16}, {25}},
					column = 4,
					row = 3,
					icon = 135928,
					ranks = 3,
				},
			}, -- [8]
			{
				info = {
					name = "Holy Reach",
					tips = "Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing, Holy Nova and Circle of Healing spells by %d%%.",
					tipValues = {{10}, {20}},
					column = 1,
					row = 4,
					icon = 135949,
					ranks = 2,
				},
			}, -- [9]
			{
				info = {
					name = "Improved Healing",
					tips = "Reduces the mana cost of your Lesser Heal, Heal, and Greater Heal spells by %d%%.",
					tipValues = {{5}, {10}, {15}},
					column = 2,
					row = 4,
					icon = 135916,
					ranks = 3,
				},
			}, -- [10]
			{
				info = {
					prereqs = {
						{
							column = 3,
							row = 2,
							source = 5,
						}, -- [1]
					},
					name = "Searing Light",
					tips = "Increases the damage of your Smite and Holy Fire spells by %d%%.",
					tipValues = {{5}, {10}},
					column = 3,
					row = 4,
					icon = 135973,
					ranks = 2,
				},
			}, -- [11]
			{
				info = {
					name = "Healing Prayers",
					tips = "Reduces the mana cost of your Prayer of Healing and Prayer of Mending spell by %d%%.",
					tipValues = {{10}, {20}},
					column = 1,
					row = 5,
					icon = 135943,
					ranks = 2,
				},
			}, -- [12]
			{
				info = {
					tips = "Increases total Spirit by 5% and upon death, the priest becomes the Spirit of Redemption for 15 sec.  The Spirit of Redemption cannot move, attack, be attacked or targeted by any spells or effects.  While in this form the priest can cast any healing spell free of cost.  When the effect ends, the priest dies.",
					name = "Spirit of Redemption",
					row = 5,
					column = 2,
					exceptional = 1,
					icon = 132864,
					ranks = 1,
				},
			}, -- [13]
			{
				info = {
					name = "Spiritual Guidance",
					tips = "Increases spell damage and healing by up to %d%% of your total Spirit.",
					tipValues = {{5}, {10}, {15}, {20}, {25}},
					column = 3,
					row = 5,
					icon = 135977,
					ranks = 5,
				},
			}, -- [14]
			{
				info = {
					name = "Surge of Light",
					tips = "Your spell criticals have a %d%% chance to cause your next Smite spell to be instant cast, cost no mana but be incapable of a critical hit.  This effect lasts 10 sec.",
					tipValues = {{25}, {50}},
					column = 1,
					row = 6,
					icon = 135981,
					ranks = 2,
				},
			}, -- [15]
			{
				info = {
					name = "Spiritual Healing",
					tips = "Increases the amount healed by your healing spells by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}},
					column = 3,
					row = 6,
					icon = 136057,
					ranks = 5,
				},
			}, -- [16]
			{
				info = {
					name = "Holy Concentration",
					tips = "Gives you a %d%% chance to enter a Clearcasting state after casting any Flash Heal, Binding Heal, or Greater Heal spell.  The Clearcasting state reduces the mana cost of your next Flash Heal, Binding Heal, or Greater Heal spell by 100%%.",
					tipValues = {{2}, {4}, {6}},
					column = 1,
					row = 7,
					icon = 135905,
					ranks = 3,
				},
			}, -- [17]
			{
				info = {
					tips = "Creates a Holy Lightwell.  Members of your raid or party can click the Lightwell to restore 801 health over 6 sec.  Any damage taken will cancel the effect.  Lightwell lasts for 3 min or 5 charges.",
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 13,
						}, -- [1]
					},
					name = "Lightwell",
					row = 7,
					column = 2,
					exceptional = 1,
					icon = 135980,
					ranks = 1,
				},
			}, -- [18]
			{
				info = {
					name = "Blessed Resilience",
					tips = "Critical hits made against you have a %d%% chance to prevent you from being critically hit again for 6 sec.",
					tipValues = {{20}, {40}, {60}},
					column = 3,
					row = 7,
					icon = 135878,
					ranks = 3,
				},
			}, -- [19]
			{
				info = {
					name = "Empowered Healing",
					tips = "Your Greater Heal spell gains an additional %d%% and your Flash Heal and Binding Heal gain an additional %d%% of your bonus healing effects.",
					tipValues = {{4, 2}, {8, 4}, {12, 6}, {16, 8}, {20, 10}},
					column = 2,
					row = 8,
					icon = 135913,
					ranks = 5,
				},
			}, -- [20]
			{
				info = {
					tips = "Heals friendly target and that target's party members within 15 yards of the target for 250 to 274.",
					name = "Circle of Healing",
					row = 9,
					column = 2,
					exceptional = 1,
					icon = 135887,
					ranks = 1,
				},
			}, -- [21]
		},
		info = {
			name = "Holy",
			background = "PriestHoly",
		},
	}, -- [2]
	{
		numtalents = 21,
		talents = {
			{
				info = {
					name = "Spirit Tap",
					tips = "Gives you a %d%% chance to gain a 100%% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your mana will regenerate at a 50%% rate while casting.  Lasts 15 sec.",
					tipValues = {{20}, {40}, {60}, {80}, {100}},
					column = 2,
					row = 1,
					icon = 136188,
					ranks = 5,
				},
			}, -- [1]
			{
				info = {
					name = "Blackout",
					tips = "Gives your Shadow damage spells a %d%% chance to stun the target for 3 sec.",
					tipValues = {{2}, {4}, {6}, {8}, {10}},
					column = 3,
					row = 1,
					icon = 136160,
					ranks = 5,
				},
			}, -- [2]
			{
				info = {
					name = "Shadow Affinity",
					tips = "Reduces the threat generated by your Shadow spells by %d%%.",
					tipValues = {{8}, {16}, {25}},
					column = 1,
					row = 2,
					icon = 136205,
					ranks = 3,
				},
			}, -- [3]
			{
				info = {
					name = "Improved Shadow Word: Pain",
					tips = "Increases the duration of your Shadow Word: Pain spell by %d sec.",
					tipValues = {{3}, {6}},
					column = 2,
					row = 2,
					icon = 136207,
					ranks = 2,
				},
			}, -- [4]
			{
				info = {
					name = "Shadow Focus",
					tips = "Reduces your target's chance to resist your Shadow spells by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}},
					column = 3,
					row = 2,
					icon = 136126,
					ranks = 5,
				},
			}, -- [5]
			{
				info = {
					name = "Improved Psychic Scream",
					tips = "Reduces the cooldown of your Psychic Scream spell by %d sec.",
					tipValues = {{2}, {4}},
					column = 1,
					row = 3,
					icon = 136184,
					ranks = 2,
				},
			}, -- [6]
			{
				info = {
					name = "Improved Mind Blast",
					tips = "Reduces the cooldown of your Mind Blast spell by %.1f sec.",
					tipValues = {{0.5}, {1.0}, {1.5}, {2.0}, {2.5}},
					column = 2,
					row = 3,
					icon = 136224,
					ranks = 5,
				},
			}, -- [7]
			{
				info = {
					tips = "Assault the target's mind with Shadow energy, causing 75 Shadow damage over 3 sec and slowing their movement speed by 50%.",
					name = "Mind Flay",
					row = 3,
					column = 3,
					exceptional = 1,
					icon = 136208,
					ranks = 1,
				},
			}, -- [8]
			{
				info = {
					name = "Improved Fade",
					tips = "Decreases the cooldown of your Fade ability by %d sec.",
					tipValues = {{3}, {6}},
					column = 2,
					row = 4,
					icon = 135994,
					ranks = 2,
				},
			}, -- [9]
			{
				info = {
					name = "Shadow Reach",
					tips = "Increases the range of your offensive Shadow spells by %d%%.",
					tipValues = {{10}, {20}},
					column = 3,
					row = 4,
					icon = 136130,
					ranks = 2,
				},
			}, -- [10]
			{
				info = {
					name = "Shadow Weaving",
					tips = "Your Shadow damage spells have a %d%% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 2%% and lasts 15 sec.  Stacks up to 5 times.",
					tipValues = {{20}, {40}, {60}, {80}, {100}},
					column = 4,
					row = 4,
					icon = 136123,
					ranks = 5,
				},
			}, -- [11]
			{
				info = {
					tips = "Silences the target, preventing them from casting spells for 5 sec.",
					prereqs = {
						{
							column = 1,
							row = 3,
							source = 6,
						}, -- [1]
					},
					name = "Silence",
					row = 5,
					column = 1,
					exceptional = 1,
					icon = 136164,
					ranks = 1,
				},
			}, -- [12]
			{
				info = {
					tips = "Afflicts your target with Shadow energy that causes all party members to be healed for 15% of any Shadow spell damage you deal for 1 min.",
					name = "Vampiric Embrace",
					row = 5,
					column = 2,
					exceptional = 1,
					icon = 136230,
					ranks = 1,
				},
			}, -- [13]
			{
				info = {
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 13,
						}, -- [1]
					},
					name = "Improved Vampiric Embrace",
					tips = "Increases the percentage healed by Vampiric Embrace by an additional %d%%.",
					tipValues = {{5}, {10}},
					column = 3,
					row = 5,
					icon = 136165,
					ranks = 2,
				},
			}, -- [14]
			{
				info = {
					name = "Focused Mind",
					tips = "Reduces the mana cost of your Mind Blast, Mind Control and Mind Flay spells by %d%%.",
					tipValues = {{5}, {10}, {15}},
					column = 4,
					row = 5,
					icon = 136035,
					ranks = 3,
				},
			}, -- [15]
			{
				info = {
					name = "Shadow Resilience",
					tips = "Reduces the chance you'll be critically hit by all spells by %d%%.",
					tipValues = {{2}, {4}},
					column = 1,
					row = 6,
					icon = 136162,
					ranks = 2,
				},
			}, -- [16]
			{
				info = {
					name = "Darkness",
					tips = "Increases your Shadow spell damage by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}},
					column = 3,
					row = 6,
					icon = 136223,
					ranks = 5,
				},
			}, -- [17]
			{
				info = {
					tips = "Assume a Shadowform, increasing your Shadow damage by 15% and reducing Physical damage done to you by 15%.  However, you may not cast Holy spells while in this form.",
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 13,
						}, -- [1]
					},
					name = "Shadowform",
					row = 7,
					column = 2,
					exceptional = 1,
					icon = 136200,
					ranks = 1,
				},
			}, -- [18]
			{
				info = {
					name = "Shadow Power",
					tips = "Increases the critical strike chance of your Mind Blast and Shadow Word: Death spells by %d%%.",
					tipValues = {{3}, {6}, {9}, {12}, {15}},
					column = 3,
					row = 7,
					icon = 136204,
					ranks = 5,
				},
			}, -- [19]
			{
				info = {
					name = "Misery",
					tips = "Your Shadow Word: Pain, Mind Flay and Vampiric Touch spells also cause the target to take an additional %d%% spell damage.",
					tipValues = {{1}, {2}, {3}, {4}, {5}},
					column = 3,
					row = 8,
					icon = 136176,
					ranks = 5,
				},
			}, -- [20]
			{
				info = {
					tips = "Causes 450 Shadow damage over 15 sec to your target and causes all party members to gain mana equal to 5% of any Shadow spell damage you deal.",
					prereqs = {
						{
							column = 2,
							row = 7,
							source = 18,
						}, -- [1]
					},
					name = "Vampiric Touch",
					row = 9,
					column = 2,
					exceptional = 1,
					icon = 135978,
					ranks = 1,
				},
			}, -- [21]
		},
		info = {
			name = "Shadow",
			background = "PriestShadow",
		},
	}, -- [3]
}
